country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 1000, "y": 480, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-60, 415, 62, 515],
                "x": 0,
                "y": 514,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 320, "y": 800, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 1000, "y": 179, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [938, -80, 1059, 25],
                "x": 1000,
                "y": 24,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 1000, "y": 534, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 937, "y": 800, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [941, -21, 1059, 82],
                "x": 1000,
                "y": 84,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [942, 158, 1063, 260],
                "x": 1000,
                "y": 255,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [294, -98, 405, -1],
                "x": 349,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [911, 376, 1028, 470],
                "x": 969,
                "y": 471,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 1, "y": 522, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 335, "y": 722, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 976, "y": 224, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 990, "y": 103, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 967, "y": 466, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 903, "y": 700, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 975, "y": 148, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 964, "y": 188, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 364, "y": 47, "track_id": None},
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 939, "y": 461, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-56, 435, 57, 531],
                "x": 2,
                "y": 531,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 351, "y": 652, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 952, "y": 263, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 980, "y": 175, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 935, "y": 408, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 870, "y": 617, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 950, "y": 205, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [865, 40, 984, 134],
                "x": 928,
                "y": 137,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 379, "y": 92, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 909, "y": 450, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-53, 438, 69, 538],
                "x": 4,
                "y": 540,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 367, "y": 591, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 928, "y": 296, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 971, "y": 240, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [848, 265, 968, 361],
                "x": 903,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [780, 443, 899, 544],
                "x": 836,
                "y": 547,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 926, "y": 258, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 892, "y": 100, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 394, "y": 134, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [818, 336, 939, 436],
                "x": 878,
                "y": 437,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 5, "y": 549, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 383, "y": 538, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 904, "y": 323, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 961, "y": 299, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 870, "y": 320, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [738, 388, 858, 490],
                "x": 803,
                "y": 491,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 901, "y": 304, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 857, "y": 75, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [354, 77, 467, 177],
                "x": 409,
                "y": 173,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 848, "y": 424, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 7, "y": 558, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 399, "y": 491, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 880, "y": 344, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 952, "y": 351, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 838, "y": 289, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 769, "y": 447, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [812, 242, 940, 344],
                "x": 877,
                "y": 346,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 821, "y": 62, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 424, "y": 209, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 818, "y": 410, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 8, "y": 566, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 414, "y": 452, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 857, "y": 361, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 942, "y": 397, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 806, "y": 265, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 736, "y": 413, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 852, "y": 382, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 785, "y": 59, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 439, "y": 243, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [723, 299, 844, 391],
                "x": 787,
                "y": 396,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 10, "y": 575, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 430, "y": 420, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 833, "y": 373, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 933, "y": 438, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 774, "y": 248, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 702, "y": 390, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 828, "y": 414, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 750, "y": 65, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 454, "y": 274, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 757, "y": 382, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 11, "y": 583, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [385, 288, 506, 398],
                "x": 446,
                "y": 393,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [749, 281, 870, 385],
                "x": 809,
                "y": 381,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 923, "y": 473, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 741, "y": 237, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 669, "y": 374, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 803, "y": 441, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 714, "y": 80, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 470, "y": 303, "track_id": None},
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 727, "y": 368, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 12, "y": 592, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 462, "y": 372, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [725, 282, 841, 384],
                "x": 785,
                "y": 384,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 913, "y": 503, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [647, 132, 767, 228],
                "x": 709,
                "y": 232,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 635, "y": 366, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 778, "y": 463, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 678, "y": 100, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 485, "y": 329, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [638, 257, 759, 350],
                "x": 696,
                "y": 354,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 14, "y": 600, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 478, "y": 357, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 761, "y": 385, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 904, "y": 527, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 677, "y": 232, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 602, "y": 365, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [697, 382, 814, 479],
                "x": 754,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [584, 27, 702, 124],
                "x": 642,
                "y": 127,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 500, "y": 353, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 666, "y": 342, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 15, "y": 608, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 493, "y": 346, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [676, 282, 797, 386],
                "x": 738,
                "y": 382,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 894, "y": 547, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 645, "y": 237, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 568, "y": 368, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 729, "y": 495, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [549, 56, 662, 162],
                "x": 607,
                "y": 157,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 515, "y": 375, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 636, "y": 330, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-39, 521, 81, 612],
                "x": 17,
                "y": 617,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 509, "y": 340, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [655, 280, 776, 377],
                "x": 714,
                "y": 376,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 885, "y": 562, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [556, 150, 669, 242],
                "x": 612,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [480, 274, 598, 370],
                "x": 535,
                "y": 375,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 705, "y": 504, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 571, "y": 191, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 530, "y": 395, "track_id": None},
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [547, 220, 667, 320],
                "x": 606,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-40, 520, 83, 623],
                "x": 18,
                "y": 625,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 525, "y": 339, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 690, "y": 368, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 875, "y": 573, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 580, "y": 256, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 501, "y": 384, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 680, "y": 510, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 535, "y": 226, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [483, 318, 604, 418],
                "x": 545,
                "y": 413,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [520, 207, 639, 310],
                "x": 575,
                "y": 310,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-45, 537, 79, 638],
                "x": 20,
                "y": 633,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 541, "y": 341, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 666, "y": 358, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 866, "y": 579, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 548, "y": 269, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 468, "y": 395, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 656, "y": 512, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 500, "y": 263, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 560, "y": 430, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 545, "y": 303, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 21, "y": 641, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 557, "y": 346, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 642, "y": 346, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 856, "y": 582, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [451, 188, 571, 282],
                "x": 516,
                "y": 284,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 435, "y": 407, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 631, "y": 510, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 464, "y": 298, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 576, "y": 444, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 515, "y": 297, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 22, "y": 649, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [515, 250, 629, 349],
                "x": 573,
                "y": 354,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 619, "y": 333, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 847, "y": 581, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 483, "y": 301, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 401, "y": 417, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 607, "y": 505, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 428, "y": 332, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [532, 361, 652, 454],
                "x": 591,
                "y": 457,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 484, "y": 294, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 24, "y": 656, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 588, "y": 365, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [539, 216, 656, 317],
                "x": 595,
                "y": 319,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 837, "y": 576, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 451, "y": 317, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 368, "y": 426, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 582, "y": 496, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 392, "y": 363, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 606, "y": 469, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 454, "y": 294, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 25, "y": 664, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [540, 275, 662, 376],
                "x": 604,
                "y": 378,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 571, "y": 304, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 827, "y": 568, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 419, "y": 334, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 334, "y": 431, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 557, "y": 485, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [299, 285, 420, 388],
                "x": 357,
                "y": 390,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 621, "y": 479, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 424, "y": 296, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 27, "y": 672, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 620, "y": 392, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 547, "y": 289, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 818, "y": 557, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [323, 247, 451, 349],
                "x": 387,
                "y": 350,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 301, "y": 432, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [478, 373, 588, 475],
                "x": 533,
                "y": 470,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 321, "y": 412, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 636, "y": 489, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 393, "y": 301, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 28, "y": 680, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 636, "y": 408, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [468, 174, 581, 270],
                "x": 523,
                "y": 275,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 808, "y": 543, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 354, "y": 364, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 267, "y": 428, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 508, "y": 452, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 285, "y": 427, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 651, "y": 497, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 363, "y": 310, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 30, "y": 687, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 652, "y": 425, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 500, "y": 260, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 799, "y": 527, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 322, "y": 376, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 234, "y": 417, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 484, "y": 432, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 250, "y": 434, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 666, "y": 504, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 333, "y": 322, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 31, "y": 695, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 667, "y": 442, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [411, 152, 540, 251],
                "x": 476,
                "y": 247,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [731, 412, 850, 511],
                "x": 789,
                "y": 508,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 290, "y": 385, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 200, "y": 398, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 459, "y": 410, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 214, "y": 432, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 682, "y": 510, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 303, "y": 337, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-24, 601, 93, 699],
                "x": 32,
                "y": 702,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 683, "y": 460, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 452, "y": 235, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [719, 389, 835, 487],
                "x": 780,
                "y": 487,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [196, 291, 316, 387],
                "x": 258,
                "y": 390,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 167, "y": 370, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 435, "y": 385, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [120, 318, 243, 419],
                "x": 178,
                "y": 420,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 697, "y": 515, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 272, "y": 357, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-26, 614, 90, 709],
                "x": 34,
                "y": 710,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 699, "y": 477, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 428, "y": 225, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 770, "y": 464, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 225, "y": 392, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [72, 229, 192, 328],
                "x": 133,
                "y": 331,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 410, "y": 357, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 142, "y": 397, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 712, "y": 520, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 242, "y": 382, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 35, "y": 717, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 715, "y": 494, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 404, "y": 216, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 760, "y": 439, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 193, "y": 389, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [42, 187, 158, 282],
                "x": 100,
                "y": 282,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 386, "y": 328, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 107, "y": 361, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 727, "y": 524, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 212, "y": 411, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-27, 623, 95, 720],
                "x": 37,
                "y": 724,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 731, "y": 509, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [323, 111, 443, 206],
                "x": 380,
                "y": 210,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 751, "y": 413, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 161, "y": 380, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [10, 119, 123, 222],
                "x": 66,
                "y": 220,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [304, 201, 426, 293],
                "x": 361,
                "y": 297,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 71, "y": 312, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [678, 431, 803, 525],
                "x": 742,
                "y": 527,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 181, "y": 444, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 38, "y": 731, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 746, "y": 523, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 357, "y": 207, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 741, "y": 386, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [73, 270, 185, 360],
                "x": 129,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-25, 49, 98, 139],
                "x": 33,
                "y": 144,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 336, "y": 264, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 35, "y": 247, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 757, "y": 531, "track_id": None},
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 151, "y": 483, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-17, 634, 100, 737],
                "x": 40,
                "y": 738,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [704, 433, 824, 530],
                "x": 762,
                "y": 535,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 333, "y": 207, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 732, "y": 357, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [32, 241, 153, 347],
                "x": 96,
                "y": 344,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 0, "y": 54, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 312, "y": 230, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [-58, 63, 64, 165],
                "x": 0,
                "y": 167,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 772, "y": 534, "track_id": None},
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 121, "y": 527, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-23, 648, 100, 746],
                "x": 41,
                "y": 745,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 778, "y": 545, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [247, 112, 365, 212],
                "x": 309,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [665, 231, 777, 329],
                "x": 722,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [8, 219, 121, 310],
                "x": 64,
                "y": 315,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 287, "y": 194, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 788, "y": 537, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 90, "y": 577, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-14, 648, 98, 749],
                "x": 42,
                "y": 752,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 794, "y": 552, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 285, "y": 217, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 713, "y": 299, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [-23, 183, 87, 282],
                "x": 32,
                "y": 278,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 263, "y": 157, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 803, "y": 540, "track_id": None},
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [2, 536, 120, 630],
                "x": 60,
                "y": 633,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-11, 664, 104, 762],
                "x": 44,
                "y": 759,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 810, "y": 556, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 261, "y": 228, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 703, "y": 268, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [-63, 131, 59, 233],
                "x": 0,
                "y": 233,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [180, 23, 300, 121],
                "x": 238,
                "y": 119,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 818, "y": 542, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 30, "y": 694, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 45, "y": 766, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [764, 459, 885, 559],
                "x": 826,
                "y": 557,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 238, "y": 244, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 694, "y": 238, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 214, "y": 80, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 833, "y": 546, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 0, "y": 763, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 47, "y": 773, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [777, 458, 904, 558],
                "x": 841,
                "y": 553,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 214, "y": 265, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [620, 103, 746, 210],
                "x": 684,
                "y": 208,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 189, "y": 40, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 848, "y": 549, "track_id": None},
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 48, "y": 780, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [800, 451, 922, 547],
                "x": 857,
                "y": 546,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 190, "y": 291, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 674, "y": 179, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 165, "y": 0, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 863, "y": 553, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-9, 688, 110, 790],
                "x": 50,
                "y": 786,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 873, "y": 534, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 166, "y": 323, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 665, "y": 149, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 878, "y": 557, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 51, "y": 793, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 889, "y": 516, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [87, 260, 202, 365],
                "x": 142,
                "y": 361,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [597, 25, 710, 120],
                "x": 655,
                "y": 121,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [835, 459, 959, 565],
                "x": 894,
                "y": 562,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 53, "y": 800, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [848, 394, 960, 491],
                "x": 905,
                "y": 493,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 119, "y": 406, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 646, "y": 94, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [852, 471, 972, 573],
                "x": 909,
                "y": 568,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 920, "y": 465, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 95, "y": 457, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 636, "y": 68, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 924, "y": 575, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [878, 333, 995, 432],
                "x": 936,
                "y": 430,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 71, "y": 516, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 627, "y": 43, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [875, 485, 1003, 583],
                "x": 939,
                "y": 582,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 952, "y": 388, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 47, "y": 581, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 617, "y": 20, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [896, 495, 1010, 596],
                "x": 954,
                "y": 591,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [907, 236, 1030, 334],
                "x": 968,
                "y": 339,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 23, "y": 655, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 608, "y": 0, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [914, 499, 1033, 602],
                "x": 969,
                "y": 601,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 984, "y": 283, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-55, 642, 55, 742],
                "x": 0,
                "y": 738,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [921, 511, 1046, 608],
                "x": 984,
                "y": 612,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 219, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 1000, "y": 625, "track_id": None},
        ],
    },
]
