country_balls_amount = 15
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [832, -98, 955, 1],
                "x": 893,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [781, 699, 901, 801],
                "x": 842,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [942, 144, 1059, 245],
                "x": 1000,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [718, -100, 841, 0],
                "x": 779,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-62, 466, 59, 565],
                "x": 0,
                "y": 567,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-59, 282, 59, 382],
                "x": 0,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [164, 699, 283, 797],
                "x": 224,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [940, 75, 1061, 178],
                "x": 1000,
                "y": 176,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [374, -99, 491, -2],
                "x": 433,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [914, 699, 1035, 801],
                "x": 976,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [941, 338, 1059, 438],
                "x": 1000,
                "y": 437,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [58, 699, 182, 802],
                "x": 120,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [940, 28, 1059, 130],
                "x": 1000,
                "y": 129,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-62, 63, 60, 161],
                "x": 0,
                "y": 161,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [270, -99, 392, 2],
                "x": 331,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [829, -57, 950, 45],
                "x": 889,
                "y": 43,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [751, 518, 869, 618],
                "x": 810,
                "y": 619,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [894, 134, 1012, 230],
                "x": 954,
                "y": 232,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [724, -100, 845, 1],
                "x": 785,
                "y": 2,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-57, 477, 62, 577],
                "x": 2,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-47, 341, 74, 440],
                "x": 14,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [167, 595, 290, 695],
                "x": 229,
                "y": 694,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [940, 67, 1057, 170],
                "x": 998,
                "y": 169,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [391, -17, 515, 84],
                "x": 453,
                "y": 82,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [894, 667, 1013, 765],
                "x": 953,
                "y": 767,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [927, 301, 1049, 405],
                "x": 987,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [55, 696, 177, 797],
                "x": 116,
                "y": 795,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [935, 60, 1059, 161],
                "x": 997,
                "y": 161,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-27, 84, 93, 187],
                "x": 35,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [302, -67, 421, 34],
                "x": 362,
                "y": 35,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [824, -15, 948, 85],
                "x": 886,
                "y": 86,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [719, 373, 837, 475],
                "x": 778,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [850, 129, 967, 230],
                "x": 909,
                "y": 229,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 792, "y": 5, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-56, 484, 63, 582],
                "x": 5,
                "y": 584,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-29, 388, 91, 490],
                "x": 29,
                "y": 490,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [174, 502, 295, 601],
                "x": 235,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [935, 64, 1054, 162],
                "x": 996,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [414, 55, 534, 154],
                "x": 473,
                "y": 155,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [871, 637, 989, 735],
                "x": 931,
                "y": 737,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [913, 274, 1035, 372],
                "x": 975,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [53, 690, 173, 789],
                "x": 113,
                "y": 791,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [934, 91, 1052, 190],
                "x": 994,
                "y": 191,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [9, 110, 132, 209],
                "x": 71,
                "y": 208,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [334, -28, 456, 71],
                "x": 394,
                "y": 71,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [821, 28, 945, 128],
                "x": 883,
                "y": 128,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [684, 255, 807, 359],
                "x": 746,
                "y": 357,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 863, "y": 230, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [737, -91, 859, 7],
                "x": 799,
                "y": 9,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-54, 494, 68, 593],
                "x": 8,
                "y": 592,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-17, 431, 106, 531],
                "x": 44,
                "y": 530,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [182, 418, 303, 521],
                "x": 241,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [933, 55, 1053, 155],
                "x": 994,
                "y": 157,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 493, "y": 219, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [850, 609, 968, 710],
                "x": 908,
                "y": 708,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [905, 245, 1025, 345],
                "x": 963,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [50, 687, 172, 787],
                "x": 110,
                "y": 785,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 992, "y": 221, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [45, 130, 169, 230],
                "x": 107,
                "y": 232,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 426, "y": 107, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [822, 71, 939, 169],
                "x": 880,
                "y": 169,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 714, "y": 269, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [758, 139, 877, 237],
                "x": 818,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [745, -87, 863, 16],
                "x": 805,
                "y": 14,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-49, 498, 69, 602],
                "x": 11,
                "y": 600,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 59, "y": 564, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [184, 352, 308, 451],
                "x": 246,
                "y": 450,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [932, 52, 1050, 152],
                "x": 992,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [454, 173, 575, 275],
                "x": 514,
                "y": 275,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [827, 582, 945, 679],
                "x": 886,
                "y": 681,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [892, 225, 1008, 323],
                "x": 950,
                "y": 324,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 106, "y": 780, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [928, 153, 1049, 251],
                "x": 989,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [83, 152, 204, 252],
                "x": 142,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [398, 41, 517, 143],
                "x": 458,
                "y": 142,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [816, 106, 938, 207],
                "x": 876,
                "y": 208,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [621, 109, 741, 208],
                "x": 682,
                "y": 208,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [712, 149, 830, 249],
                "x": 772,
                "y": 247,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 812, "y": 20, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-47, 508, 71, 607],
                "x": 13,
                "y": 608,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [13, 489, 135, 592],
                "x": 73,
                "y": 590,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 252, "y": 390, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [932, 45, 1050, 144],
                "x": 990,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [474, 225, 596, 324],
                "x": 534,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [802, 556, 924, 656],
                "x": 863,
                "y": 656,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [876, 206, 998, 307],
                "x": 938,
                "y": 305,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [41, 673, 163, 774],
                "x": 103,
                "y": 774,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [927, 181, 1045, 280],
                "x": 987,
                "y": 279,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 178, "y": 276, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [429, 75, 552, 175],
                "x": 490,
                "y": 176,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [813, 146, 932, 249],
                "x": 873,
                "y": 247,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 650, "y": 170, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [665, 159, 785, 257],
                "x": 727,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [759, -70, 879, 26],
                "x": 819,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-42, 515, 75, 614],
                "x": 16,
                "y": 616,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 88, "y": 610, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [199, 242, 319, 342],
                "x": 258,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [928, 41, 1046, 141],
                "x": 988,
                "y": 140,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [495, 265, 616, 363],
                "x": 554,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [783, 531, 903, 631],
                "x": 841,
                "y": 633,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [868, 191, 988, 288],
                "x": 926,
                "y": 289,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [41, 666, 162, 767],
                "x": 100,
                "y": 767,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [924, 209, 1044, 307],
                "x": 984,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [154, 197, 276, 295],
                "x": 214,
                "y": 297,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [461, 110, 584, 206],
                "x": 522,
                "y": 208,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [809, 183, 928, 285],
                "x": 870,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [559, 53, 677, 156],
                "x": 618,
                "y": 154,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [621, 172, 739, 274],
                "x": 681,
                "y": 274,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 825, "y": 36, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-40, 525, 77, 624],
                "x": 19,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [41, 524, 164, 623],
                "x": 103,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [204, 199, 324, 299],
                "x": 264,
                "y": 300,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [924, 36, 1044, 134],
                "x": 986,
                "y": 134,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 574, "y": 400, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [757, 514, 879, 611],
                "x": 818,
                "y": 612,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [856, 177, 973, 277],
                "x": 914,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [34, 662, 157, 760],
                "x": 96,
                "y": 760,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [924, 233, 1044, 335],
                "x": 982,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [192, 215, 311, 317],
                "x": 250,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [496, 138, 616, 240],
                "x": 554,
                "y": 238,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [808, 220, 926, 321],
                "x": 867,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [524, 55, 645, 154],
                "x": 586,
                "y": 156,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [577, 191, 698, 291],
                "x": 636,
                "y": 289,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [773, -56, 891, 44],
                "x": 832,
                "y": 46,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-36, 532, 84, 630],
                "x": 22,
                "y": 631,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [56, 533, 178, 630],
                "x": 118,
                "y": 632,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [209, 168, 331, 271],
                "x": 269,
                "y": 269,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [926, 27, 1042, 127],
                "x": 984,
                "y": 129,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [537, 327, 657, 429],
                "x": 595,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [736, 491, 856, 592],
                "x": 796,
                "y": 592,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [839, 164, 960, 264],
                "x": 901,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [35, 651, 152, 753],
                "x": 93,
                "y": 752,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [919, 259, 1041, 360],
                "x": 979,
                "y": 361,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 285, "y": 335, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [523, 162, 645, 265],
                "x": 585,
                "y": 264,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [801, 259, 922, 356],
                "x": 863,
                "y": 357,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [495, 75, 615, 176],
                "x": 554,
                "y": 174,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [532, 206, 651, 303],
                "x": 590,
                "y": 304,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 839, "y": 56, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-36, 541, 86, 637],
                "x": 24,
                "y": 639,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [71, 536, 194, 637],
                "x": 132,
                "y": 636,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [215, 144, 333, 244],
                "x": 275,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [922, 24, 1043, 125],
                "x": 982,
                "y": 124,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [555, 352, 674, 453],
                "x": 615,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [711, 476, 831, 573],
                "x": 773,
                "y": 574,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [831, 160, 950, 259],
                "x": 889,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [30, 643, 148, 744],
                "x": 90,
                "y": 743,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [919, 286, 1035, 389],
                "x": 977,
                "y": 387,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 321, "y": 352, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [557, 189, 679, 288],
                "x": 617,
                "y": 287,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [802, 289, 920, 393],
                "x": 860,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [463, 105, 581, 206],
                "x": 522,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [484, 221, 603, 318],
                "x": 545,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [785, -32, 906, 69],
                "x": 845,
                "y": 68,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-33, 547, 85, 644],
                "x": 27,
                "y": 646,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [88, 537, 205, 635],
                "x": 147,
                "y": 635,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [221, 131, 339, 231],
                "x": 281,
                "y": 232,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [919, 20, 1040, 116],
                "x": 981,
                "y": 118,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [577, 372, 693, 471],
                "x": 635,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [689, 459, 812, 558],
                "x": 751,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [818, 151, 935, 252],
                "x": 877,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [28, 635, 148, 736],
                "x": 86,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [915, 313, 1033, 414],
                "x": 974,
                "y": 413,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [295, 268, 415, 367],
                "x": 357,
                "y": 366,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [591, 208, 711, 307],
                "x": 649,
                "y": 306,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [797, 327, 918, 425],
                "x": 857,
                "y": 425,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [431, 153, 549, 252],
                "x": 491,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [438, 229, 561, 330],
                "x": 500,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [790, -18, 910, 82],
                "x": 852,
                "y": 82,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-28, 553, 92, 654],
                "x": 30,
                "y": 653,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [102, 532, 221, 633],
                "x": 162,
                "y": 631,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [225, 123, 348, 223],
                "x": 287,
                "y": 224,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [919, 13, 1040, 114],
                "x": 979,
                "y": 113,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [593, 388, 715, 487],
                "x": 655,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [668, 444, 788, 544],
                "x": 729,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [804, 149, 927, 251],
                "x": 865,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [23, 625, 143, 724],
                "x": 83,
                "y": 725,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [913, 336, 1033, 436],
                "x": 972,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [330, 279, 451, 377],
                "x": 392,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [619, 220, 743, 319],
                "x": 681,
                "y": 319,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 854, "y": 458, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [397, 202, 520, 306],
                "x": 459,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [392, 243, 516, 339],
                "x": 454,
                "y": 341,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [801, -4, 920, 98],
                "x": 859,
                "y": 96,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-25, 559, 91, 661],
                "x": 33,
                "y": 660,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [116, 524, 238, 625],
                "x": 177,
                "y": 623,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [233, 123, 350, 224],
                "x": 292,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [919, 7, 1039, 110],
                "x": 977,
                "y": 108,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [615, 400, 736, 501],
                "x": 676,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [647, 430, 765, 533],
                "x": 706,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [790, 151, 910, 253],
                "x": 852,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [18, 614, 139, 716],
                "x": 80,
                "y": 715,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [910, 364, 1031, 462],
                "x": 969,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [370, 288, 489, 389],
                "x": 428,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [652, 230, 772, 326],
                "x": 713,
                "y": 328,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 850, "y": 489, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [367, 262, 489, 363],
                "x": 427,
                "y": 364,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 409, "y": 346, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [808, 13, 926, 114],
                "x": 866,
                "y": 112,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-25, 566, 95, 666],
                "x": 35,
                "y": 666,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [133, 511, 252, 612],
                "x": 191,
                "y": 613,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [237, 131, 356, 230],
                "x": 298,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [916, 3, 1034, 103],
                "x": 975,
                "y": 103,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [635, 414, 758, 512],
                "x": 696,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [623, 419, 743, 520],
                "x": 684,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [779, 155, 898, 256],
                "x": 840,
                "y": 254,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 76, "y": 704, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [905, 385, 1029, 485],
                "x": 967,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [405, 298, 525, 396],
                "x": 464,
                "y": 398,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 745, "y": 330, "track_id": None},
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [788, 420, 908, 519],
                "x": 847,
                "y": 520,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 395, "y": 428, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [305, 250, 425, 349],
                "x": 363,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [814, 28, 931, 128],
                "x": 872,
                "y": 130,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-24, 575, 98, 671],
                "x": 38,
                "y": 673,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 206, "y": 600, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [242, 139, 362, 238],
                "x": 304,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [912, -1, 1032, 100],
                "x": 973,
                "y": 99,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [654, 421, 774, 523],
                "x": 716,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [600, 410, 721, 509],
                "x": 661,
                "y": 510,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [769, 160, 888, 260],
                "x": 828,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [12, 592, 132, 693],
                "x": 73,
                "y": 693,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [903, 409, 1024, 509],
                "x": 964,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [441, 305, 561, 404],
                "x": 500,
                "y": 404,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 777, "y": 326, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [783, 451, 902, 548],
                "x": 844,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [305, 394, 423, 492],
                "x": 363,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [257, 244, 380, 345],
                "x": 318,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [818, 46, 939, 146],
                "x": 879,
                "y": 148,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-20, 579, 101, 681],
                "x": 41,
                "y": 679,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [159, 483, 280, 587],
                "x": 221,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [251, 154, 369, 254],
                "x": 310,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [911, -7, 1033, 93],
                "x": 971,
                "y": 94,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [675, 430, 796, 529],
                "x": 736,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [578, 401, 698, 504],
                "x": 639,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [754, 167, 875, 266],
                "x": 815,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [9, 583, 132, 681],
                "x": 70,
                "y": 681,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [903, 429, 1021, 533],
                "x": 962,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [476, 306, 595, 408],
                "x": 535,
                "y": 406,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [747, 215, 866, 314],
                "x": 808,
                "y": 315,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [779, 478, 902, 577],
                "x": 841,
                "y": 579,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [272, 460, 389, 556],
                "x": 331,
                "y": 558,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 272, "y": 332, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [824, 69, 946, 167],
                "x": 886,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-18, 586, 106, 685],
                "x": 44,
                "y": 686,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [177, 470, 294, 568],
                "x": 236,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [254, 178, 375, 279],
                "x": 315,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [908, -11, 1031, 90],
                "x": 969,
                "y": 89,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [699, 437, 819, 536],
                "x": 757,
                "y": 535,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [557, 398, 677, 497],
                "x": 616,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [741, 173, 862, 272],
                "x": 803,
                "y": 274,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [5, 570, 126, 668],
                "x": 66,
                "y": 669,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [899, 455, 1018, 552],
                "x": 959,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [512, 307, 631, 407],
                "x": 571,
                "y": 406,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [781, 196, 899, 297],
                "x": 840,
                "y": 295,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [779, 508, 895, 608],
                "x": 837,
                "y": 607,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [239, 519, 359, 620],
                "x": 299,
                "y": 620,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [166, 213, 285, 313],
                "x": 227,
                "y": 314,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 892, "y": 190, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-14, 593, 108, 692],
                "x": 47,
                "y": 692,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [190, 452, 309, 554],
                "x": 250,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [262, 202, 383, 301],
                "x": 321,
                "y": 301,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [909, -16, 1029, 84],
                "x": 967,
                "y": 85,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [718, 442, 837, 543],
                "x": 777,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [533, 389, 653, 492],
                "x": 594,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [733, 185, 852, 285],
                "x": 791,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [4, 555, 125, 655],
                "x": 63,
                "y": 656,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [894, 473, 1017, 574],
                "x": 956,
                "y": 574,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [548, 301, 668, 403],
                "x": 607,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [813, 169, 930, 267],
                "x": 872,
                "y": 268,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [774, 533, 895, 633],
                "x": 834,
                "y": 634,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [209, 575, 326, 675],
                "x": 267,
                "y": 677,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [119, 189, 243, 287],
                "x": 181,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [838, 112, 958, 214],
                "x": 899,
                "y": 213,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 49, "y": 698, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [207, 435, 327, 534],
                "x": 265,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [266, 228, 389, 331],
                "x": 327,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [906, -18, 1023, 83],
                "x": 965,
                "y": 81,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [735, 450, 857, 551],
                "x": 797,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [509, 389, 633, 491],
                "x": 571,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 779, "y": 296, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 60, "y": 642, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [895, 496, 1013, 596],
                "x": 954,
                "y": 595,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [583, 298, 703, 394],
                "x": 642,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [846, 133, 965, 233],
                "x": 904,
                "y": 232,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [771, 561, 892, 660],
                "x": 831,
                "y": 660,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [176, 624, 293, 728],
                "x": 235,
                "y": 726,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [78, 152, 196, 253],
                "x": 136,
                "y": 251,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 906, "y": 238, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-9, 602, 111, 705],
                "x": 52,
                "y": 704,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [221, 419, 341, 522],
                "x": 280,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [274, 261, 390, 360],
                "x": 332,
                "y": 361,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 964, "y": 76, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [759, 460, 879, 556],
                "x": 817,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [488, 385, 608, 487],
                "x": 549,
                "y": 487,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [705, 211, 825, 312],
                "x": 766,
                "y": 310,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-4, 526, 118, 628],
                "x": 56,
                "y": 628,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [889, 513, 1009, 615],
                "x": 951,
                "y": 615,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [616, 285, 740, 385],
                "x": 678,
                "y": 386,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [874, 88, 994, 186],
                "x": 936,
                "y": 186,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [767, 586, 888, 688],
                "x": 828,
                "y": 686,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [142, 662, 264, 766],
                "x": 203,
                "y": 764,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [30, 107, 150, 206],
                "x": 90,
                "y": 205,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [854, 163, 973, 264],
                "x": 912,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-4, 610, 113, 707],
                "x": 55,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [233, 405, 355, 506],
                "x": 295,
                "y": 504,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [279, 294, 396, 392],
                "x": 338,
                "y": 394,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [904, -26, 1021, 72],
                "x": 962,
                "y": 72,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [779, 468, 900, 570],
                "x": 838,
                "y": 569,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 527, "y": 487, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [693, 224, 813, 327],
                "x": 754,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-5, 515, 111, 613],
                "x": 53,
                "y": 613,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [891, 536, 1007, 635],
                "x": 949,
                "y": 634,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [654, 271, 775, 374],
                "x": 714,
                "y": 372,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 968, "y": 130, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [763, 609, 882, 711],
                "x": 824,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [109, 689, 230, 790],
                "x": 171,
                "y": 789,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-17, 47, 105, 148],
                "x": 45,
                "y": 148,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [860, 191, 980, 290],
                "x": 919,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-2, 617, 120, 716],
                "x": 58,
                "y": 715,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 309, "y": 490, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [285, 328, 406, 429],
                "x": 344,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [900, -30, 1022, 66],
                "x": 960,
                "y": 68,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 858, "y": 582, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [442, 390, 566, 488],
                "x": 504,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [680, 240, 800, 341],
                "x": 742,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-8, 498, 111, 600],
                "x": 50,
                "y": 598,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [884, 553, 1007, 654],
                "x": 946,
                "y": 653,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [691, 252, 810, 354],
                "x": 750,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [939, -38, 1062, 62],
                "x": 1000,
                "y": 64,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [759, 634, 882, 733],
                "x": 821,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [78, 701, 202, 800],
                "x": 140,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-61, -21, 60, 78],
                "x": 0,
                "y": 79,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [864, 222, 987, 323],
                "x": 926,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-1, 622, 122, 719],
                "x": 60,
                "y": 720,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [265, 380, 385, 479],
                "x": 324,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [288, 365, 409, 466],
                "x": 350,
                "y": 466,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [898, -38, 1017, 63],
                "x": 958,
                "y": 64,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [818, 501, 938, 597],
                "x": 878,
                "y": 599,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [422, 390, 543, 492],
                "x": 482,
                "y": 492,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [669, 261, 791, 362],
                "x": 730,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-13, 480, 105, 583],
                "x": 46,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [883, 571, 1002, 674],
                "x": 944,
                "y": 672,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [724, 233, 847, 333],
                "x": 785,
                "y": 331,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [759, 658, 879, 755],
                "x": 818,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [872, 254, 995, 352],
                "x": 933,
                "y": 352,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [3, 626, 122, 724],
                "x": 63,
                "y": 725,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [278, 369, 399, 466],
                "x": 339,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [296, 404, 416, 502],
                "x": 355,
                "y": 503,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [897, -40, 1018, 62],
                "x": 956,
                "y": 61,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [836, 521, 959, 617],
                "x": 898,
                "y": 619,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 459, "y": 497, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [659, 281, 777, 379],
                "x": 717,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-18, 463, 105, 566],
                "x": 43,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [880, 587, 1000, 688],
                "x": 941,
                "y": 689,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [759, 203, 883, 306],
                "x": 821,
                "y": 305,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [755, 679, 873, 777],
                "x": 815,
                "y": 778,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [878, 285, 1000, 384],
                "x": 939,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [5, 628, 126, 732],
                "x": 66,
                "y": 730,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [292, 363, 413, 464],
                "x": 354,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [301, 441, 421, 539],
                "x": 361,
                "y": 540,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [893, -44, 1016, 58],
                "x": 954,
                "y": 57,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [858, 544, 979, 645],
                "x": 919,
                "y": 643,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 437, "y": 504, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 705, "y": 398, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [-22, 449, 102, 547],
                "x": 40,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [880, 607, 999, 709],
                "x": 939,
                "y": 707,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [799, 174, 917, 275],
                "x": 857,
                "y": 274,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 812, "y": 799, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [888, 321, 1004, 422],
                "x": 946,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [7, 636, 127, 736],
                "x": 69,
                "y": 735,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [308, 358, 427, 458],
                "x": 368,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [306, 475, 427, 579],
                "x": 367,
                "y": 577,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [891, -45, 1013, 52],
                "x": 952,
                "y": 53,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [877, 573, 1001, 672],
                "x": 939,
                "y": 673,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [352, 412, 473, 512],
                "x": 414,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [632, 318, 751, 421],
                "x": 693,
                "y": 419,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-26, 430, 98, 528],
                "x": 36,
                "y": 529,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 936, "y": 724, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [830, 137, 952, 236],
                "x": 892,
                "y": 238,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [893, 355, 1014, 457],
                "x": 953,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [11, 640, 133, 741],
                "x": 71,
                "y": 740,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [321, 361, 443, 460],
                "x": 383,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [315, 512, 434, 611],
                "x": 373,
                "y": 613,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [891, -51, 1008, 49],
                "x": 950,
                "y": 50,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [901, 608, 1021, 709],
                "x": 959,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [332, 423, 451, 520],
                "x": 392,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [618, 339, 738, 440],
                "x": 680,
                "y": 440,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-26, 410, 95, 510],
                "x": 33,
                "y": 511,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [876, 638, 993, 742],
                "x": 934,
                "y": 740,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [870, 98, 986, 199],
                "x": 928,
                "y": 197,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [900, 394, 1019, 495],
                "x": 959,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [16, 643, 134, 744],
                "x": 74,
                "y": 744,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [338, 366, 459, 464],
                "x": 398,
                "y": 464,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [316, 547, 437, 649],
                "x": 378,
                "y": 647,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [890, -56, 1010, 48],
                "x": 948,
                "y": 46,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [920, 653, 1041, 749],
                "x": 979,
                "y": 751,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [307, 433, 427, 532],
                "x": 369,
                "y": 532,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [609, 364, 730, 463],
                "x": 668,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-32, 393, 89, 491],
                "x": 30,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [872, 655, 992, 754],
                "x": 931,
                "y": 756,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [906, 51, 1024, 149],
                "x": 964,
                "y": 151,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [904, 436, 1024, 535],
                "x": 966,
                "y": 534,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [15, 647, 135, 751],
                "x": 77,
                "y": 749,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [351, 374, 473, 472],
                "x": 413,
                "y": 474,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [324, 579, 443, 678],
                "x": 384,
                "y": 679,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [886, -59, 1006, 43],
                "x": 947,
                "y": 43,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 1000, "y": 800, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [289, 443, 407, 545],
                "x": 347,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [597, 385, 718, 482],
                "x": 656,
                "y": 484,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-34, 371, 84, 470],
                "x": 26,
                "y": 471,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [867, 669, 989, 769],
                "x": 929,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [941, -1, 1058, 98],
                "x": 1000,
                "y": 99,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [912, 477, 1031, 576],
                "x": 973,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [21, 654, 142, 754],
                "x": 80,
                "y": 753,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 427, "y": 490, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [329, 609, 449, 711],
                "x": 390,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [885, -61, 1005, 42],
                "x": 945,
                "y": 40,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [263, 457, 382, 559],
                "x": 324,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [585, 405, 705, 505],
                "x": 644,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-36, 351, 85, 449],
                "x": 23,
                "y": 450,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [868, 685, 987, 787],
                "x": 926,
                "y": 785,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [920, 522, 1038, 620],
                "x": 979,
                "y": 620,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [21, 658, 141, 755],
                "x": 83,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [382, 411, 502, 510],
                "x": 442,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [336, 634, 455, 735],
                "x": 396,
                "y": 736,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [885, -65, 1001, 36],
                "x": 943,
                "y": 37,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [241, 473, 360, 575],
                "x": 302,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [569, 427, 691, 528],
                "x": 631,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-39, 331, 80, 428],
                "x": 20,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [862, 700, 985, 798],
                "x": 924,
                "y": 799,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [924, 566, 1047, 667],
                "x": 986,
                "y": 665,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [27, 663, 147, 760],
                "x": 85,
                "y": 762,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [399, 439, 518, 539],
                "x": 457,
                "y": 540,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [340, 661, 463, 761],
                "x": 401,
                "y": 759,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 941, "y": 34, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 280, "y": 589, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 619, "y": 552, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 16, "y": 406, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [934, 614, 1051, 715],
                "x": 993,
                "y": 713,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [29, 663, 146, 765],
                "x": 88,
                "y": 765,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [414, 474, 531, 577],
                "x": 472,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [347, 678, 466, 778],
                "x": 407,
                "y": 777,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [878, -70, 1000, 33],
                "x": 939,
                "y": 31,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [199, 505, 318, 608],
                "x": 257,
                "y": 607,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [548, 474, 669, 575],
                "x": 607,
                "y": 575,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 13, "y": 383, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [939, 662, 1061, 762],
                "x": 1000,
                "y": 762,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [31, 669, 149, 767],
                "x": 91,
                "y": 769,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [427, 519, 545, 619],
                "x": 486,
                "y": 619,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [351, 693, 474, 791],
                "x": 413,
                "y": 791,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [878, -71, 999, 28],
                "x": 937,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [173, 529, 294, 628],
                "x": 235,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [535, 497, 653, 596],
                "x": 595,
                "y": 598,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-49, 259, 72, 362],
                "x": 10,
                "y": 360,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [35, 672, 156, 774],
                "x": 94,
                "y": 773,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 501, "y": 670, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [360, 702, 481, 799],
                "x": 419,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [873, -75, 995, 27],
                "x": 935,
                "y": 25,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [153, 549, 273, 645],
                "x": 212,
                "y": 647,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [523, 520, 640, 621],
                "x": 582,
                "y": 620,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-54, 236, 68, 333],
                "x": 6,
                "y": 335,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [38, 674, 154, 776],
                "x": 96,
                "y": 776,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [458, 631, 574, 732],
                "x": 516,
                "y": 730,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [871, -76, 995, 22],
                "x": 933,
                "y": 22,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [131, 569, 251, 669],
                "x": 190,
                "y": 669,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 570, "y": 642, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [-56, 210, 63, 312],
                "x": 3,
                "y": 310,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [39, 678, 160, 782],
                "x": 99,
                "y": 780,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [469, 698, 591, 799],
                "x": 531,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [873, -80, 992, 18],
                "x": 931,
                "y": 20,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [106, 595, 227, 692],
                "x": 167,
                "y": 693,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [498, 562, 617, 665],
                "x": 558,
                "y": 663,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-60, 183, 59, 284],
                "x": 0,
                "y": 285,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [40, 682, 160, 782],
                "x": 102,
                "y": 783,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [869, -80, 988, 17],
                "x": 930,
                "y": 18,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [85, 617, 205, 718],
                "x": 145,
                "y": 718,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 545, "y": 684, "track_id": None},
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [45, 688, 163, 786],
                "x": 105,
                "y": 786,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [867, -85, 990, 16],
                "x": 928,
                "y": 15,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [62, 646, 183, 744],
                "x": 122,
                "y": 744,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 533, "y": 704, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [46, 687, 166, 791],
                "x": 107,
                "y": 789,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [867, -85, 986, 11],
                "x": 926,
                "y": 13,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [40, 673, 162, 771],
                "x": 100,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [459, 621, 583, 722],
                "x": 521,
                "y": 723,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [51, 692, 172, 791],
                "x": 110,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [863, -87, 984, 9],
                "x": 924,
                "y": 11,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [17, 698, 137, 798],
                "x": 78,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 509, "y": 741, "track_id": None},
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [53, 694, 175, 792],
                "x": 113,
                "y": 794,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [863, -90, 981, 10],
                "x": 922,
                "y": 9,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [438, 659, 554, 756],
                "x": 496,
                "y": 758,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 4, "bounding_box": [], "x": 116, "y": 797, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [862, -93, 980, 9],
                "x": 920,
                "y": 7,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [425, 672, 543, 774],
                "x": 484,
                "y": 773,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [60, 702, 178, 801],
                "x": 119,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [857, -93, 977, 4],
                "x": 918,
                "y": 5,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [410, 685, 533, 786],
                "x": 472,
                "y": 787,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 7,
                "bounding_box": [854, -95, 974, 5],
                "x": 916,
                "y": 3,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [398, 701, 522, 800],
                "x": 460,
                "y": 800,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 7,
                "bounding_box": [853, -100, 975, 1],
                "x": 914,
                "y": 1,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 7,
                "bounding_box": [855, -99, 973, -1],
                "x": 913,
                "y": 0,
                "track_id": None,
            }
        ],
    },
]
