country_balls_amount = 15
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 1000, "y": 556, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 118, "y": 0, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 78, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 24, "y": 800, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 0, "y": 454, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 770, "y": 799, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 1000, "y": 47, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 961, "y": 0, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 505, "y": 0, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 0, "y": 295, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 122, "y": 0, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 0, "y": 708, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [937, -89, 1055, 18],
                "x": 1000,
                "y": 15,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 830, "y": 0, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 1000, "y": 150, "track_id": None},
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 999, "y": 537, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 137, "y": 18, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 980, "y": 156, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 23, "y": 790, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 34, "y": 456, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 767, "y": 753, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 967, "y": 116, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 962, "y": 12, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 516, "y": 83, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 27, "y": 324, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 118, "y": 5, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [-28, 585, 89, 684],
                "x": 27,
                "y": 680,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 994, "y": 72, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 800, "y": 73, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [905, 136, 1031, 232],
                "x": 969,
                "y": 236,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 998, "y": 517, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [101, -61, 212, 34],
                "x": 157,
                "y": 35,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 960, "y": 226, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 22, "y": 780, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [4, 355, 130, 457],
                "x": 68,
                "y": 457,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 765, "y": 707, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [875, 77, 992, 181],
                "x": 935,
                "y": 179,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 963, "y": 24, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 527, "y": 159, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 55, "y": 350, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 115, "y": 11, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 54, "y": 656, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 988, "y": 126, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [710, 41, 826, 138],
                "x": 770,
                "y": 140,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 938, "y": 308, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 997, "y": 498, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 176, "y": 51, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [883, 189, 1003, 289],
                "x": 941,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-42, 674, 77, 768],
                "x": 22,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [41, 360, 165, 458],
                "x": 103,
                "y": 459,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 763, "y": 661, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [848, 140, 967, 238],
                "x": 903,
                "y": 235,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 964, "y": 36, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [476, 126, 599, 230],
                "x": 538,
                "y": 227,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 83, "y": 374, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 112, "y": 17, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 81, "y": 634, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 982, "y": 178, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [681, 107, 802, 202],
                "x": 741,
                "y": 202,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 907, "y": 367, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 997, "y": 478, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 196, "y": 66, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 921, "y": 349, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 21, "y": 761, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 137, "y": 460, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 761, "y": 617, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [806, 183, 927, 283],
                "x": 870,
                "y": 286,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 965, "y": 49, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 550, "y": 289, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 111, "y": 396, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [49, -79, 171, 23],
                "x": 109,
                "y": 24,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [43, 511, 170, 610],
                "x": 108,
                "y": 615,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 976, "y": 228, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [656, 164, 776, 264],
                "x": 711,
                "y": 259,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 876, "y": 414, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 996, "y": 459, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 216, "y": 79, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 902, "y": 401, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 20, "y": 751, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 172, "y": 460, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 759, "y": 574, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 838, "y": 331, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 967, "y": 61, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 561, "y": 344, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [76, 319, 200, 415],
                "x": 138,
                "y": 415,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 106, "y": 31, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 135, "y": 598, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 971, "y": 274, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 681, "y": 311, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 845, "y": 449, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [938, 339, 1054, 445],
                "x": 995,
                "y": 440,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 235, "y": 92, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [821, 348, 942, 453],
                "x": 882,
                "y": 448,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 20, "y": 741, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 206, "y": 460, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 757, "y": 532, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 806, "y": 371, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 968, "y": 73, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 572, "y": 393, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 166, "y": 432, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 103, "y": 39, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 162, "y": 583, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 965, "y": 319, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [593, 253, 712, 363],
                "x": 652,
                "y": 358,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 814, "y": 475, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 995, "y": 420, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 255, "y": 104, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 862, "y": 489, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 19, "y": 731, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 241, "y": 460, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 755, "y": 490, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [719, 310, 837, 400],
                "x": 774,
                "y": 405,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 969, "y": 86, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 583, "y": 436, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 194, "y": 447, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [39, -52, 160, 52],
                "x": 100,
                "y": 48,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 189, "y": 570, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 959, "y": 361, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [560, 299, 682, 399],
                "x": 622,
                "y": 399,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 783, "y": 491, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 994, "y": 401, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 274, "y": 115, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 843, "y": 525, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 18, "y": 721, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 275, "y": 459, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 753, "y": 450, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 741, "y": 434, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [911, 2, 1035, 96],
                "x": 970,
                "y": 98,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 595, "y": 473, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 222, "y": 460, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 97, "y": 57, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [155, 458, 272, 558],
                "x": 216,
                "y": 559,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 953, "y": 402, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 592, "y": 436, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 752, "y": 499, "track_id": None},
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 993, "y": 382, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 294, "y": 125, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 823, "y": 556, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 18, "y": 710, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 310, "y": 458, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 751, "y": 410, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [650, 360, 766, 461],
                "x": 709,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [906, 15, 1026, 113],
                "x": 971,
                "y": 111,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 606, "y": 504, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 250, "y": 472, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [32, -29, 159, 63],
                "x": 94,
                "y": 67,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 243, "y": 550, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 948, "y": 440, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [499, 369, 619, 468],
                "x": 563,
                "y": 468,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 721, "y": 501, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [933, 268, 1058, 363],
                "x": 993,
                "y": 363,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [258, 34, 371, 130],
                "x": 314,
                "y": 135,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [740, 484, 859, 582],
                "x": 804,
                "y": 583,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 17, "y": 700, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [284, 355, 406, 453],
                "x": 344,
                "y": 456,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 749, "y": 371, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 677, "y": 477, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [915, 27, 1028, 122],
                "x": 973,
                "y": 123,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [558, 426, 674, 532],
                "x": 617,
                "y": 530,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 277, "y": 482, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [30, -19, 152, 81],
                "x": 91,
                "y": 77,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 270, "y": 542, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 942, "y": 475, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [473, 394, 593, 498],
                "x": 533,
                "y": 495,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 690, "y": 496, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 992, "y": 344, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 333, "y": 143, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 784, "y": 604, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 16, "y": 689, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 379, "y": 454, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 746, "y": 333, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [588, 389, 703, 488],
                "x": 645,
                "y": 491,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 974, "y": 136, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [563, 453, 686, 549],
                "x": 628,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [240, 392, 370, 496],
                "x": 305,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [27, -10, 149, 92],
                "x": 88,
                "y": 88,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [232, 431, 362, 533],
                "x": 297,
                "y": 534,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 936, "y": 509, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 503, "y": 518, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 659, "y": 487, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 991, "y": 326, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 353, "y": 151, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [707, 519, 824, 618],
                "x": 765,
                "y": 621,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-41, 583, 81, 677],
                "x": 16,
                "y": 679,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [358, 354, 471, 452],
                "x": 413,
                "y": 452,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 744, "y": 296, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 612, "y": 501, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 975, "y": 148, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 640, "y": 567, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 333, "y": 498, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 85, "y": 99, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 324, "y": 528, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 930, "y": 540, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [411, 435, 539, 531],
                "x": 474,
                "y": 536,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 628, "y": 474, "track_id": None},
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 990, "y": 307, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [310, 64, 430, 155],
                "x": 372,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [681, 530, 807, 634],
                "x": 745,
                "y": 634,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 15, "y": 668, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 448, "y": 449, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 742, "y": 260, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 580, "y": 506, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [918, 66, 1034, 162],
                "x": 976,
                "y": 161,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 651, "y": 578, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 361, "y": 505, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 82, "y": 111, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [289, 419, 414, 520],
                "x": 351,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [860, 475, 982, 574],
                "x": 924,
                "y": 570,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [382, 451, 506, 548],
                "x": 444,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [540, 362, 658, 462],
                "x": 597,
                "y": 458,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 990, "y": 288, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 392, "y": 166, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [660, 544, 782, 647],
                "x": 725,
                "y": 643,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 14, "y": 657, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [418, 343, 537, 444],
                "x": 482,
                "y": 446,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 740, "y": 224, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 548, "y": 507, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 978, "y": 173, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 662, "y": 585, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [328, 413, 448, 510],
                "x": 388,
                "y": 510,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 79, "y": 123, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 378, "y": 517, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 919, "y": 598, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 415, "y": 559, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 566, "y": 441, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 989, "y": 269, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [349, 77, 474, 168],
                "x": 412,
                "y": 173,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 706, "y": 648, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 14, "y": 646, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [453, 342, 573, 448],
                "x": 517,
                "y": 443,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 738, "y": 190, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [452, 407, 577, 506],
                "x": 516,
                "y": 504,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 979, "y": 186, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 673, "y": 588, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 416, "y": 515, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 76, "y": 137, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 405, "y": 512, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 913, "y": 623, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [330, 461, 446, 559],
                "x": 385,
                "y": 564,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 535, "y": 423, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 988, "y": 251, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 431, "y": 179, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [626, 555, 751, 651],
                "x": 686,
                "y": 650,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 13, "y": 635, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [495, 336, 613, 437],
                "x": 551,
                "y": 439,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 736, "y": 156, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 483, "y": 497, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [919, 101, 1042, 201],
                "x": 980,
                "y": 198,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 685, "y": 587, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 444, "y": 520, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 73, "y": 150, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 432, "y": 507, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 907, "y": 647, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 355, "y": 565, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 504, "y": 405, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 988, "y": 233, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 451, "y": 185, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 667, "y": 648, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 12, "y": 624, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 586, "y": 435, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 734, "y": 123, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 451, "y": 486, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 981, "y": 211, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 696, "y": 583, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 472, "y": 523, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [6, 67, 131, 170],
                "x": 70,
                "y": 165,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [397, 405, 523, 503],
                "x": 459,
                "y": 501,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 901, "y": 669, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 326, "y": 562, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 473, "y": 389, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 987, "y": 214, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [415, 91, 528, 192],
                "x": 470,
                "y": 191,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 647, "y": 642, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 12, "y": 613, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 620, "y": 430, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 732, "y": 91, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [355, 370, 476, 473],
                "x": 419,
                "y": 472,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 982, "y": 224, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 707, "y": 575, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 500, "y": 527, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 67, "y": 180, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 486, "y": 496, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 896, "y": 688, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 296, "y": 555, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 442, "y": 376, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 986, "y": 196, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 490, "y": 196, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 628, "y": 634, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 11, "y": 602, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 655, "y": 425, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 730, "y": 60, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 387, "y": 453, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 984, "y": 236, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 718, "y": 564, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 527, "y": 531, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 64, "y": 196, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 513, "y": 489, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [825, 602, 955, 712],
                "x": 890,
                "y": 707,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [201, 444, 328, 546],
                "x": 266,
                "y": 544,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 411, "y": 366, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [922, 73, 1041, 183],
                "x": 986,
                "y": 178,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 510, "y": 201, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [551, 524, 667, 620],
                "x": 608,
                "y": 623,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 10, "y": 590, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 689, "y": 420, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 728, "y": 29, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 354, "y": 432, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 985, "y": 249, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [668, 449, 794, 555],
                "x": 730,
                "y": 550,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 555, "y": 534, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 61, "y": 212, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 540, "y": 482, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 884, "y": 723, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 237, "y": 530, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [318, 266, 445, 359],
                "x": 380,
                "y": 361,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [925, 62, 1049, 155],
                "x": 985,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [467, 107, 587, 205],
                "x": 529,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [529, 511, 651, 612],
                "x": 588,
                "y": 609,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 10, "y": 579, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 724, "y": 414, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 726, "y": 0, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 322, "y": 407, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 986, "y": 262, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 741, "y": 533, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 583, "y": 538, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 57, "y": 229, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [510, 373, 626, 475],
                "x": 567,
                "y": 473,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 878, "y": 738, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [146, 408, 266, 516],
                "x": 207,
                "y": 512,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 349, "y": 362, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [926, 40, 1042, 138],
                "x": 984,
                "y": 141,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 549, "y": 212, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 569, "y": 593, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 9, "y": 567, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 758, "y": 408, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 290, "y": 380, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [925, 180, 1048, 274],
                "x": 987,
                "y": 275,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 752, "y": 515, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 611, "y": 542, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 54, "y": 247, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [529, 369, 654, 467],
                "x": 594,
                "y": 464,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 872, "y": 751, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 177, "y": 490, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 318, "y": 369, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 983, "y": 123, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 568, "y": 217, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 549, "y": 575, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-50, 455, 70, 558],
                "x": 8,
                "y": 555,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [736, 303, 858, 407],
                "x": 793,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [202, 249, 317, 344],
                "x": 258,
                "y": 349,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 989, "y": 287, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 763, "y": 494, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 638, "y": 547, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 51, "y": 265, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 621, "y": 452, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 867, "y": 762, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 148, "y": 465, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 287, "y": 384, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 983, "y": 105, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 588, "y": 222, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 530, "y": 555, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 8, "y": 543, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [767, 300, 885, 390],
                "x": 827,
                "y": 395,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 225, "y": 316, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 990, "y": 300, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 775, "y": 471, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 666, "y": 552, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 48, "y": 284, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [588, 337, 706, 441],
                "x": 648,
                "y": 439,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 861, "y": 772, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [54, 331, 178, 432],
                "x": 118,
                "y": 436,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 256, "y": 408, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 982, "y": 88, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 608, "y": 228, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 510, "y": 533, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 7, "y": 532, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 862, "y": 388, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 193, "y": 280, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 991, "y": 313, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 786, "y": 447, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 694, "y": 558, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 45, "y": 304, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 675, "y": 424, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 855, "y": 780, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [24, 300, 148, 401],
                "x": 88,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [168, 343, 284, 439],
                "x": 225,
                "y": 443,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 981, "y": 70, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 627, "y": 234, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 491, "y": 509, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 6, "y": 520, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 896, "y": 381, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 161, "y": 241, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 992, "y": 326, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 797, "y": 421, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 722, "y": 565, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 42, "y": 325, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 702, "y": 407, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [786, 692, 914, 788],
                "x": 849,
                "y": 787,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 59, "y": 369, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 194, "y": 488, "track_id": None},
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 981, "y": 52, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 647, "y": 240, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 471, "y": 484, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 6, "y": 507, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 931, "y": 374, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 129, "y": 201, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 993, "y": 339, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 808, "y": 394, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [688, 471, 810, 574],
                "x": 750,
                "y": 573,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 39, "y": 346, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 729, "y": 388, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 844, "y": 792, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 29, "y": 331, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [99, 443, 228, 548],
                "x": 163,
                "y": 545,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 980, "y": 35, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 666, "y": 246, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [395, 361, 514, 454],
                "x": 451,
                "y": 458,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 5, "y": 495, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 965, "y": 366, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 96, "y": 158, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 995, "y": 352, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 820, "y": 367, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [722, 478, 835, 583],
                "x": 777,
                "y": 583,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [-28, 270, 94, 370],
                "x": 36,
                "y": 368,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 756, "y": 366, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [777, 697, 900, 797],
                "x": 838,
                "y": 796,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 0, "y": 290, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 132, "y": 615, "track_id": None},
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [920, -79, 1038, 13],
                "x": 979,
                "y": 17,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 686, "y": 253, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 432, "y": 430, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 4, "y": 483, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [941, 259, 1065, 359],
                "x": 1000,
                "y": 358,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 64, "y": 113, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 996, "y": 365, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 831, "y": 339, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 805, "y": 594, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 33, "y": 391, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 783, "y": 341, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 832, "y": 799, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [37, 600, 166, 700],
                "x": 101,
                "y": 700,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 979, "y": 0, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 706, "y": 260, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 412, "y": 402, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 4, "y": 470, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 32, "y": 67, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [934, 282, 1053, 378],
                "x": 997,
                "y": 378,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 842, "y": 310, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 833, "y": 606, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [-27, 317, 87, 419],
                "x": 30,
                "y": 414,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 810, "y": 313, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 826, "y": 800, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 71, "y": 800, "track_id": None},
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 725, "y": 268, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [328, 272, 452, 369],
                "x": 393,
                "y": 374,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 3, "y": 458, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 0, "y": 19, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [939, 290, 1056, 388],
                "x": 998,
                "y": 391,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 853, "y": 282, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 861, "y": 620, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 27, "y": 438, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 837, "y": 282, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 821, "y": 799, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 745, "y": 276, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 373, "y": 345, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-58, 344, 61, 447],
                "x": 2,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [945, 308, 1060, 398],
                "x": 1000,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [802, 150, 927, 250],
                "x": 865,
                "y": 253,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 888, "y": 637, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 24, "y": 463, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 864, "y": 248, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 764, "y": 285, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 354, "y": 315, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 2, "y": 432, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [819, 124, 931, 224],
                "x": 876,
                "y": 225,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 916, "y": 655, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [-41, 388, 81, 490],
                "x": 21,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 891, "y": 209, "track_id": None},
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 784, "y": 295, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 334, "y": 286, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 1, "y": 420, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 887, "y": 198, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [881, 574, 1001, 670],
                "x": 944,
                "y": 675,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 18, "y": 515, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 918, "y": 167, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [740, 207, 867, 302],
                "x": 804,
                "y": 305,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 314, "y": 257, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 0, "y": 407, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [841, 75, 953, 169],
                "x": 898,
                "y": 172,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 972, "y": 698, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 15, "y": 543, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [883, 24, 1005, 124],
                "x": 945,
                "y": 121,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 823, "y": 317, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 295, "y": 228, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 0, "y": 394, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 910, "y": 147, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [943, 626, 1057, 721],
                "x": 1000,
                "y": 723,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 12, "y": 571, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 972, "y": 71, "track_id": None},
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 843, "y": 329, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 275, "y": 200, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [861, 20, 980, 128],
                "x": 921,
                "y": 123,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 9, "y": 600, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [937, -83, 1060, 21],
                "x": 1000,
                "y": 16,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 862, "y": 342, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 256, "y": 173, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 932, "y": 101, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 6, "y": 630, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 882, "y": 356, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 236, "y": 147, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 943, "y": 81, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 3, "y": 660, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [840, 276, 958, 369],
                "x": 902,
                "y": 371,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 217, "y": 122, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 955, "y": 63, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 0, "y": 692, "track_id": None},
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 921, "y": 388, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [137, 2, 258, 96],
                "x": 197,
                "y": 99,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 966, "y": 48, "track_id": None},
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [884, 304, 996, 403],
                "x": 941,
                "y": 405,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 177, "y": 77, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [916, -63, 1040, 39],
                "x": 977,
                "y": 35,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 960, "y": 424, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 158, "y": 57, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [923, -70, 1050, 25],
                "x": 988,
                "y": 25,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 980, "y": 444, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [76, -65, 197, 44],
                "x": 138,
                "y": 39,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [939, -76, 1060, 22],
                "x": 1000,
                "y": 19,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 465, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 119, "y": 23, "track_id": None},
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [37, -91, 158, 13],
                "x": 99,
                "y": 10,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [19, -95, 135, 5],
                "x": 80,
                "y": 0,
                "track_id": None,
            }
        ],
    },
]
