country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [390, 695, 508, 797],
                "x": 447,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [942, 516, 1065, 610],
                "x": 1000,
                "y": 613,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [661, -98, 779, -1],
                "x": 717,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-60, 677, 63, 767],
                "x": 0,
                "y": 772,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [941, 184, 1064, 291],
                "x": 1000,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [940, 327, 1057, 430],
                "x": 1000,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [942, -44, 1064, 60],
                "x": 1000,
                "y": 57,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [935, 278, 1055, 375],
                "x": 1000,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-58, 413, 60, 516],
                "x": 0,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [10, -97, 128, 5],
                "x": 67,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [403, 696, 520, 795],
                "x": 458,
                "y": 795,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [919, 410, 1039, 507],
                "x": 983,
                "y": 510,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 724, "y": 40, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-62, 645, 56, 753],
                "x": 1,
                "y": 750,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [911, 189, 1032, 287],
                "x": 976,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [909, 282, 1035, 385],
                "x": 974,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [916, -28, 1038, 71],
                "x": 979,
                "y": 74,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [892, 375, 1015, 473],
                "x": 954,
                "y": 470,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-22, 401, 93, 500],
                "x": 35,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [21, -92, 139, 10],
                "x": 83,
                "y": 9,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [409, 691, 531, 792],
                "x": 469,
                "y": 788,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 967, "y": 421, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [673, -18, 790, 75],
                "x": 731,
                "y": 80,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-62, 629, 61, 725],
                "x": 2,
                "y": 728,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [896, 203, 1008, 300],
                "x": 953,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [891, 239, 1010, 346],
                "x": 948,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [899, -11, 1014, 89],
                "x": 959,
                "y": 91,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [852, 434, 972, 532],
                "x": 908,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [15, 398, 136, 496],
                "x": 71,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [37, -74, 162, 19],
                "x": 100,
                "y": 23,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 480, "y": 780, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [891, 247, 1010, 345],
                "x": 951,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [674, 22, 800, 114],
                "x": 739,
                "y": 118,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-59, 602, 66, 710],
                "x": 3,
                "y": 707,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [875, 207, 994, 309],
                "x": 930,
                "y": 308,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 923, "y": 310, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [877, 6, 998, 113],
                "x": 938,
                "y": 109,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [803, 475, 925, 580],
                "x": 862,
                "y": 577,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [47, 392, 171, 487],
                "x": 107,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [62, -53, 173, 43],
                "x": 117,
                "y": 42,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [435, 668, 549, 765],
                "x": 492,
                "y": 770,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [876, 178, 990, 282],
                "x": 935,
                "y": 278,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [690, 55, 809, 156],
                "x": 746,
                "y": 156,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-56, 585, 65, 689],
                "x": 4,
                "y": 686,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [844, 213, 962, 315],
                "x": 906,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [832, 181, 955, 285],
                "x": 897,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [856, 29, 977, 127],
                "x": 918,
                "y": 126,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 817, "y": 599, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [87, 390, 197, 492],
                "x": 142,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [74, -35, 193, 66],
                "x": 133,
                "y": 66,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [445, 660, 564, 761],
                "x": 503,
                "y": 759,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [856, 120, 977, 226],
                "x": 919,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [693, 94, 815, 193],
                "x": 754,
                "y": 192,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-49, 567, 71, 664],
                "x": 6,
                "y": 665,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [828, 230, 943, 323],
                "x": 883,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [812, 165, 934, 262],
                "x": 871,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [843, 43, 960, 140],
                "x": 898,
                "y": 144,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [708, 499, 832, 607],
                "x": 771,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [113, 402, 234, 498],
                "x": 178,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [89, -6, 211, 90],
                "x": 150,
                "y": 93,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [453, 649, 577, 745],
                "x": 514,
                "y": 746,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [841, 77, 966, 181],
                "x": 903,
                "y": 178,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [696, 127, 817, 224],
                "x": 761,
                "y": 228,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 7, "y": 644, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [803, 235, 922, 344],
                "x": 860,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [787, 147, 908, 250],
                "x": 846,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [817, 57, 932, 164],
                "x": 877,
                "y": 162,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [670, 497, 785, 599],
                "x": 725,
                "y": 596,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [150, 409, 269, 505],
                "x": 214,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [104, 21, 230, 126],
                "x": 167,
                "y": 123,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [468, 634, 583, 731],
                "x": 526,
                "y": 732,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [827, 46, 951, 147],
                "x": 887,
                "y": 142,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [704, 163, 828, 264],
                "x": 769,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-49, 519, 69, 628],
                "x": 8,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [778, 248, 896, 351],
                "x": 837,
                "y": 350,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [759, 138, 876, 242],
                "x": 820,
                "y": 242,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 857, "y": 179, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [619, 482, 740, 577],
                "x": 679,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [191, 415, 314, 515],
                "x": 250,
                "y": 519,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [124, 57, 242, 160],
                "x": 183,
                "y": 156,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [480, 619, 595, 714],
                "x": 537,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [810, 20, 930, 116],
                "x": 870,
                "y": 116,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [721, 197, 841, 289],
                "x": 776,
                "y": 294,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-54, 499, 70, 599],
                "x": 9,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [758, 265, 872, 367],
                "x": 813,
                "y": 362,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 794, "y": 238, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [779, 99, 902, 197],
                "x": 837,
                "y": 196,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [569, 453, 697, 549],
                "x": 634,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [223, 430, 343, 529],
                "x": 285,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [145, 87, 257, 186],
                "x": 200,
                "y": 191,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 548, "y": 700, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [794, -6, 910, 102],
                "x": 854,
                "y": 98,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [726, 224, 847, 321],
                "x": 784,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-52, 488, 66, 589],
                "x": 11,
                "y": 584,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [735, 278, 848, 374],
                "x": 790,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [706, 143, 829, 241],
                "x": 769,
                "y": 239,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [756, 112, 872, 210],
                "x": 816,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [526, 429, 645, 528],
                "x": 588,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [257, 449, 382, 546],
                "x": 321,
                "y": 545,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 217, "y": 229, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [499, 580, 623, 684],
                "x": 559,
                "y": 682,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [774, -14, 897, 85],
                "x": 838,
                "y": 87,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [729, 250, 848, 354],
                "x": 791,
                "y": 355,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-45, 464, 67, 565],
                "x": 12,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [710, 287, 827, 382],
                "x": 767,
                "y": 386,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [688, 145, 798, 244],
                "x": 743,
                "y": 244,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 796, "y": 230, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [482, 398, 607, 495],
                "x": 542,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [302, 456, 420, 563],
                "x": 357,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [173, 169, 293, 270],
                "x": 233,
                "y": 267,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [509, 562, 630, 669],
                "x": 571,
                "y": 664,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [764, -21, 887, 86],
                "x": 822,
                "y": 84,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [736, 287, 858, 380],
                "x": 798,
                "y": 383,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-48, 443, 78, 549],
                "x": 13,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [680, 296, 799, 397],
                "x": 744,
                "y": 399,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [657, 157, 776, 251],
                "x": 717,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [714, 151, 837, 241],
                "x": 776,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [432, 374, 559, 471],
                "x": 496,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [331, 473, 451, 573],
                "x": 392,
                "y": 571,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [195, 210, 311, 308],
                "x": 250,
                "y": 307,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [519, 542, 646, 641],
                "x": 582,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [751, -12, 862, 82],
                "x": 806,
                "y": 87,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 806, "y": 409, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-50, 429, 73, 529],
                "x": 14,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [659, 312, 775, 411],
                "x": 720,
                "y": 411,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [628, 166, 756, 263],
                "x": 692,
                "y": 265,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 755, "y": 262, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 451, "y": 454, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [369, 485, 490, 580],
                "x": 428,
                "y": 583,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [205, 250, 322, 345],
                "x": 267,
                "y": 348,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [536, 527, 654, 620],
                "x": 593,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [725, -3, 852, 98],
                "x": 790,
                "y": 96,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [755, 338, 868, 432],
                "x": 813,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-40, 408, 71, 508],
                "x": 16,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [633, 318, 752, 425],
                "x": 697,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [606, 174, 721, 274],
                "x": 666,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [672, 174, 798, 276],
                "x": 735,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [346, 350, 464, 442],
                "x": 405,
                "y": 446,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [402, 489, 525, 590],
                "x": 464,
                "y": 592,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [226, 285, 338, 385],
                "x": 283,
                "y": 388,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [550, 508, 663, 600],
                "x": 605,
                "y": 603,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [718, 11, 835, 108],
                "x": 774,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [765, 354, 886, 457],
                "x": 821,
                "y": 455,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-46, 384, 82, 482],
                "x": 17,
                "y": 487,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [619, 336, 735, 437],
                "x": 674,
                "y": 434,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [579, 201, 700, 292],
                "x": 641,
                "y": 296,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [649, 195, 772, 286],
                "x": 714,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [299, 357, 421, 447],
                "x": 359,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [441, 502, 557, 603],
                "x": 500,
                "y": 599,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [235, 328, 360, 429],
                "x": 300,
                "y": 428,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 616, "y": 582, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [693, 30, 821, 127],
                "x": 757,
                "y": 128,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [772, 372, 886, 477],
                "x": 828,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-40, 363, 76, 465],
                "x": 18,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [591, 347, 708, 445],
                "x": 651,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [551, 215, 673, 316],
                "x": 615,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [638, 205, 757, 304],
                "x": 694,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [250, 379, 375, 473],
                "x": 313,
                "y": 474,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [476, 507, 590, 608],
                "x": 535,
                "y": 603,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [260, 370, 381, 467],
                "x": 317,
                "y": 467,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [568, 462, 688, 560],
                "x": 627,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [683, 54, 806, 154],
                "x": 741,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [772, 396, 901, 489],
                "x": 836,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-37, 353, 83, 445],
                "x": 19,
                "y": 450,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 627, "y": 455, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [530, 232, 649, 336],
                "x": 589,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [619, 213, 736, 315],
                "x": 674,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [207, 420, 332, 516],
                "x": 268,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [510, 497, 634, 601],
                "x": 571,
                "y": 602,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [271, 406, 396, 506],
                "x": 333,
                "y": 506,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [575, 438, 703, 539],
                "x": 638,
                "y": 537,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [666, 77, 786, 180],
                "x": 725,
                "y": 177,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 843, "y": 509, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-44, 327, 78, 431],
                "x": 21,
                "y": 431,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 604, "y": 465, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [509, 255, 624, 358],
                "x": 564,
                "y": 356,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [595, 223, 710, 332],
                "x": 653,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [162, 478, 278, 582],
                "x": 222,
                "y": 583,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [551, 501, 671, 601],
                "x": 607,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [294, 439, 407, 544],
                "x": 350,
                "y": 542,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [591, 416, 705, 514],
                "x": 650,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [648, 101, 773, 209],
                "x": 709,
                "y": 206,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [796, 420, 907, 517],
                "x": 851,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-43, 311, 82, 416],
                "x": 22,
                "y": 413,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 581, "y": 474, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [477, 273, 595, 379],
                "x": 538,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [574, 238, 689, 344],
                "x": 633,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [120, 577, 234, 678],
                "x": 176,
                "y": 676,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [577, 490, 697, 582],
                "x": 642,
                "y": 586,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [305, 473, 429, 574],
                "x": 367,
                "y": 576,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [597, 388, 716, 492],
                "x": 661,
                "y": 490,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [629, 133, 751, 240],
                "x": 693,
                "y": 236,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [803, 434, 922, 535],
                "x": 858,
                "y": 533,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-42, 300, 88, 397],
                "x": 23,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [495, 381, 617, 481],
                "x": 558,
                "y": 481,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 512, "y": 400, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [548, 250, 674, 349],
                "x": 613,
                "y": 349,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [74, 700, 196, 795],
                "x": 131,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [622, 474, 738, 572],
                "x": 678,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [319, 508, 445, 611],
                "x": 383,
                "y": 608,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [609, 367, 737, 465],
                "x": 672,
                "y": 467,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [617, 165, 741, 264],
                "x": 677,
                "y": 269,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 865, "y": 541, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-39, 276, 85, 382],
                "x": 24,
                "y": 378,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 534, "y": 488, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [428, 322, 543, 427],
                "x": 487,
                "y": 422,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [529, 252, 649, 353],
                "x": 592,
                "y": 357,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [656, 450, 773, 551],
                "x": 714,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [345, 540, 457, 635],
                "x": 400,
                "y": 636,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [627, 341, 747, 448],
                "x": 684,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [599, 206, 716, 298],
                "x": 661,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [808, 452, 938, 544],
                "x": 873,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-34, 261, 85, 362],
                "x": 26,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [450, 389, 571, 496],
                "x": 511,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [406, 345, 526, 444],
                "x": 461,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [513, 269, 628, 363],
                "x": 572,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [691, 411, 806, 511],
                "x": 750,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [362, 565, 482, 665],
                "x": 417,
                "y": 661,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [637, 317, 750, 415],
                "x": 695,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [579, 236, 706, 331],
                "x": 644,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [815, 452, 938, 554],
                "x": 880,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-30, 241, 83, 348],
                "x": 27,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [431, 399, 547, 500],
                "x": 488,
                "y": 496,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 435, "y": 462, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 552, "y": 370, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [723, 370, 841, 470],
                "x": 785,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [369, 583, 489, 682],
                "x": 433,
                "y": 683,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [645, 300, 768, 396],
                "x": 706,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [569, 274, 687, 365],
                "x": 628,
                "y": 369,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [833, 445, 943, 552],
                "x": 888,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-32, 227, 84, 329],
                "x": 28,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [403, 401, 524, 499],
                "x": 465,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [349, 385, 471, 481],
                "x": 410,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [467, 276, 586, 378],
                "x": 531,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [766, 329, 885, 423],
                "x": 821,
                "y": 426,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [388, 596, 506, 694],
                "x": 450,
                "y": 699,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [658, 276, 772, 368],
                "x": 717,
                "y": 372,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [547, 296, 677, 400],
                "x": 612,
                "y": 401,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [837, 451, 956, 548],
                "x": 895,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-29, 204, 94, 304],
                "x": 29,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [379, 400, 502, 494],
                "x": 441,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [328, 393, 442, 499],
                "x": 384,
                "y": 497,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 511, "y": 377, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [794, 263, 922, 366],
                "x": 857,
                "y": 368,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [402, 610, 529, 706],
                "x": 467,
                "y": 711,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [674, 254, 791, 346],
                "x": 729,
                "y": 349,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [531, 328, 655, 433],
                "x": 596,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [847, 437, 966, 546],
                "x": 903,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-33, 194, 91, 287],
                "x": 31,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [353, 394, 474, 500],
                "x": 418,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [297, 411, 419, 509],
                "x": 358,
                "y": 510,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [426, 281, 554, 374],
                "x": 490,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [837, 198, 952, 301],
                "x": 892,
                "y": 299,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 483, "y": 718, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [679, 221, 799, 331],
                "x": 740,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [525, 361, 638, 458],
                "x": 580,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [851, 428, 966, 530],
                "x": 910,
                "y": 533,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-29, 177, 96, 272],
                "x": 32,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [334, 393, 460, 497],
                "x": 395,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [273, 417, 397, 521],
                "x": 333,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [407, 280, 529, 383],
                "x": 470,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [867, 118, 985, 219],
                "x": 928,
                "y": 220,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [444, 620, 558, 718],
                "x": 500,
                "y": 718,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [691, 205, 815, 298],
                "x": 751,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [503, 386, 624, 481],
                "x": 564,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [855, 424, 973, 523],
                "x": 918,
                "y": 521,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 33, "y": 259, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [309, 390, 434, 486],
                "x": 372,
                "y": 488,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [242, 434, 371, 534],
                "x": 307,
                "y": 529,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 450, "y": 376, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [900, 32, 1020, 123],
                "x": 964,
                "y": 128,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [462, 609, 576, 716],
                "x": 517,
                "y": 713,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [698, 178, 824, 278],
                "x": 763,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [485, 412, 608, 506],
                "x": 548,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [868, 408, 986, 507],
                "x": 925,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-24, 143, 95, 241],
                "x": 34,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [284, 379, 410, 483],
                "x": 348,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [224, 437, 337, 536],
                "x": 282,
                "y": 533,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 429, "y": 372, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [945, -75, 1061, 22],
                "x": 1000,
                "y": 24,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [471, 598, 592, 697],
                "x": 533,
                "y": 701,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [713, 163, 836, 264],
                "x": 774,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [476, 420, 586, 520],
                "x": 531,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [868, 392, 992, 489],
                "x": 932,
                "y": 487,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-25, 130, 92, 223],
                "x": 36,
                "y": 227,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [260, 368, 380, 475],
                "x": 325,
                "y": 471,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [192, 429, 313, 531],
                "x": 256,
                "y": 532,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [353, 269, 466, 369],
                "x": 409,
                "y": 366,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [494, 587, 613, 683],
                "x": 550,
                "y": 682,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [730, 142, 848, 237],
                "x": 785,
                "y": 239,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [456, 437, 570, 533],
                "x": 515,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [884, 360, 995, 469],
                "x": 940,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-27, 112, 92, 212],
                "x": 37,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [239, 363, 362, 458],
                "x": 302,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [168, 423, 292, 524],
                "x": 230,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [329, 263, 447, 354],
                "x": 389,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [502, 550, 623, 660],
                "x": 567,
                "y": 655,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [731, 115, 855, 216],
                "x": 796,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [444, 448, 561, 542],
                "x": 499,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [885, 336, 1009, 442],
                "x": 947,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-25, 101, 103, 195],
                "x": 38,
                "y": 196,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [214, 339, 336, 444],
                "x": 279,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [141, 413, 261, 520],
                "x": 205,
                "y": 517,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 368, "y": 349, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [519, 524, 640, 623],
                "x": 583,
                "y": 620,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [744, 96, 867, 200],
                "x": 808,
                "y": 199,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [424, 448, 539, 553],
                "x": 483,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [900, 305, 1020, 411],
                "x": 955,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-16, 82, 101, 185],
                "x": 39,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [191, 325, 317, 426],
                "x": 255,
                "y": 425,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [123, 406, 244, 497],
                "x": 179,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [286, 232, 413, 338],
                "x": 348,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [540, 478, 656, 582],
                "x": 600,
                "y": 577,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [755, 86, 883, 180],
                "x": 819,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [404, 438, 532, 544],
                "x": 467,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [901, 276, 1023, 376],
                "x": 962,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-24, 71, 102, 161],
                "x": 41,
                "y": 166,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [171, 305, 287, 404],
                "x": 232,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [93, 376, 214, 483],
                "x": 153,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [269, 221, 391, 320],
                "x": 328,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [562, 426, 672, 530],
                "x": 617,
                "y": 525,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [770, 66, 895, 160],
                "x": 830,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [396, 427, 508, 531],
                "x": 451,
                "y": 531,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 970, "y": 340, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-19, 52, 103, 153],
                "x": 42,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [148, 282, 272, 376],
                "x": 209,
                "y": 380,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [73, 354, 188, 449],
                "x": 128,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [244, 207, 366, 311],
                "x": 307,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [573, 366, 690, 459],
                "x": 633,
                "y": 463,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [783, 49, 900, 148],
                "x": 842,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [373, 416, 492, 513],
                "x": 435,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [921, 198, 1036, 296],
                "x": 977,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-16, 32, 100, 138],
                "x": 43,
                "y": 136,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [122, 254, 243, 349],
                "x": 186,
                "y": 353,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 102, "y": 417, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [224, 185, 345, 293],
                "x": 287,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [590, 297, 707, 390],
                "x": 650,
                "y": 392,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [788, 31, 911, 133],
                "x": 853,
                "y": 131,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [357, 381, 474, 481],
                "x": 418,
                "y": 484,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [923, 150, 1044, 251],
                "x": 985,
                "y": 254,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 44, "y": 122, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [102, 227, 223, 320],
                "x": 162,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [21, 275, 135, 377],
                "x": 76,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [202, 167, 321, 269],
                "x": 266,
                "y": 267,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [611, 211, 727, 314],
                "x": 667,
                "y": 310,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [805, 14, 929, 114],
                "x": 864,
                "y": 117,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [339, 342, 461, 442],
                "x": 402,
                "y": 447,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 992, "y": 205, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 46, "y": 107, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [74, 187, 196, 294],
                "x": 139,
                "y": 289,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 51, "y": 326, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [187, 147, 309, 239],
                "x": 246,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [626, 120, 739, 216],
                "x": 683,
                "y": 218,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [811, 1, 931, 109],
                "x": 875,
                "y": 105,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [329, 300, 445, 401],
                "x": 386,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [938, 54, 1063, 152],
                "x": 1000,
                "y": 152,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-9, -2, 110, 89],
                "x": 47,
                "y": 93,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [53, 152, 171, 248],
                "x": 116,
                "y": 252,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-31, 171, 86, 270],
                "x": 25,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [161, 113, 291, 220],
                "x": 226,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [636, 12, 757, 111],
                "x": 700,
                "y": 115,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [832, -8, 946, 88],
                "x": 887,
                "y": 93,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [306, 248, 428, 346],
                "x": 370,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-12, -22, 111, 74],
                "x": 48,
                "y": 79,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 93, "y": 211, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 0, "y": 202, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [147, 91, 266, 187],
                "x": 205,
                "y": 187,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [657, -101, 772, 3],
                "x": 717,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [840, -18, 956, 80],
                "x": 898,
                "y": 84,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [289, 179, 410, 280],
                "x": 354,
                "y": 275,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-14, -40, 105, 64],
                "x": 49,
                "y": 65,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 69, "y": 166, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [127, 55, 244, 157],
                "x": 185,
                "y": 156,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [844, -28, 971, 73],
                "x": 909,
                "y": 75,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [276, 94, 401, 196],
                "x": 338,
                "y": 195,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-13, -51, 116, 50],
                "x": 51,
                "y": 52,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-13, 16, 103, 117],
                "x": 46,
                "y": 117,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [105, 20, 223, 119],
                "x": 165,
                "y": 121,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [859, -34, 985, 64],
                "x": 921,
                "y": 69,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [263, 1, 384, 106],
                "x": 322,
                "y": 104,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-13, -65, 115, 41],
                "x": 52,
                "y": 39,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-40, -33, 86, 69],
                "x": 23,
                "y": 64,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [85, -14, 207, 89],
                "x": 144,
                "y": 84,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [875, -31, 996, 63],
                "x": 932,
                "y": 64,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [251, -96, 369, -4],
                "x": 306,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-5, -72, 114, 22],
                "x": 53,
                "y": 25,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-56, -91, 63, 3],
                "x": 0,
                "y": 8,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [64, -55, 187, 46],
                "x": 124,
                "y": 43,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [881, -39, 1004, 57],
                "x": 943,
                "y": 61,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-11, -85, 111, 16],
                "x": 54,
                "y": 12,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [41, -101, 166, -5],
                "x": 104,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [891, -39, 1017, 58],
                "x": 954,
                "y": 60,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-7, -101, 121, 4],
                "x": 56,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [902, -35, 1028, 57],
                "x": 966,
                "y": 61,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [919, -34, 1034, 69],
                "x": 977,
                "y": 65,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [925, -27, 1043, 71],
                "x": 988,
                "y": 70,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [939, -22, 1060, 73],
                "x": 1000,
                "y": 77,
                "track_id": None,
            }
        ],
    },
]
