country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 325, "y": 799, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 0, "y": 777, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [261, 701, 379, 798],
                "x": 320,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-58, -24, 61, 77],
                "x": 0,
                "y": 76,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 56, "y": 0, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 1000, "y": 77, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 123, "y": 800, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 1000, "y": 605, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [941, 314, 1059, 413],
                "x": 1000,
                "y": 412,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [241, 701, 360, 802],
                "x": 301,
                "y": 800,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 332, "y": 687, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-47, 656, 73, 756],
                "x": 15,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [263, 669, 381, 766],
                "x": 321,
                "y": 768,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-54, 35, 64, 134],
                "x": 4,
                "y": 135,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 100, "y": 32, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [896, 89, 1019, 189],
                "x": 958,
                "y": 191,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 144, "y": 739, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 997, "y": 615, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [912, 385, 1033, 489],
                "x": 971,
                "y": 487,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [267, 617, 387, 717],
                "x": 328,
                "y": 717,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 339, "y": 599, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 30, "y": 735, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [262, 635, 381, 739],
                "x": 322,
                "y": 737,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 9, "y": 191, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 145, "y": 67, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [856, 186, 978, 288],
                "x": 916,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [108, 587, 228, 683],
                "x": 166,
                "y": 685,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 995, "y": 625, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [881, 447, 1001, 546],
                "x": 942,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [297, 541, 417, 640],
                "x": 356,
                "y": 640,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [286, 432, 407, 534],
                "x": 347,
                "y": 532,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 46, "y": 712, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 323, "y": 706, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 14, "y": 245, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 190, "y": 105, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 875, "y": 366, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [127, 536, 248, 637],
                "x": 188,
                "y": 635,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 993, "y": 635, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 914, "y": 596, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [321, 471, 441, 570],
                "x": 383,
                "y": 569,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 354, "y": 485, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 61, "y": 687, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 325, "y": 676, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 19, "y": 297, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [176, 43, 295, 146],
                "x": 235,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [773, 329, 892, 432],
                "x": 833,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [149, 493, 268, 590],
                "x": 210,
                "y": 591,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 991, "y": 645, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 885, "y": 632, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 411, "y": 505, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [304, 357, 420, 453],
                "x": 362,
                "y": 455,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 77, "y": 660, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [264, 544, 384, 646],
                "x": 326,
                "y": 646,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 24, "y": 345, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 280, "y": 185, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [733, 381, 850, 480],
                "x": 791,
                "y": 479,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 232, "y": 552, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 988, "y": 654, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 857, "y": 657, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 438, "y": 447, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [311, 342, 427, 440],
                "x": 369,
                "y": 441,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 92, "y": 633, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 327, "y": 616, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-32, 291, 89, 392],
                "x": 29,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [264, 128, 383, 224],
                "x": 325,
                "y": 226,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 750, "y": 515, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 254, "y": 518, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [924, 565, 1046, 665],
                "x": 986,
                "y": 663,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 828, "y": 671, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [404, 296, 527, 394],
                "x": 466,
                "y": 395,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 377, "y": 441, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 108, "y": 604, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [271, 486, 389, 586],
                "x": 329,
                "y": 587,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 34, "y": 435, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 370, "y": 267, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 708, "y": 539, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [216, 388, 338, 489],
                "x": 276,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 984, "y": 672, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [738, 573, 862, 676],
                "x": 800,
                "y": 675,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 493, "y": 351, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [325, 352, 444, 452],
                "x": 384,
                "y": 452,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 123, "y": 575, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [271, 458, 391, 559],
                "x": 330,
                "y": 559,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 38, "y": 476, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 415, "y": 307, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 666, "y": 553, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 298, "y": 464, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 982, "y": 680, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 771, "y": 671, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 521, "y": 313, "track_id": None},
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [333, 373, 451, 471],
                "x": 391,
                "y": 472,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 139, "y": 544, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 331, "y": 531, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 43, "y": 514, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 460, "y": 345, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 625, "y": 557, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 320, "y": 442, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 979, "y": 688, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 742, "y": 658, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 548, "y": 282, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 399, "y": 501, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 154, "y": 513, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 333, "y": 503, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 48, "y": 550, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [446, 280, 566, 381],
                "x": 505,
                "y": 380,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 583, "y": 553, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [284, 325, 402, 426],
                "x": 342,
                "y": 425,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [916, 594, 1036, 698],
                "x": 977,
                "y": 696,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 714, "y": 639, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 576, "y": 259, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 406, "y": 534, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [111, 382, 230, 482],
                "x": 170,
                "y": 482,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 334, "y": 476, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 53, "y": 584, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 550, "y": 413, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 541, "y": 542, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 364, "y": 412, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 975, "y": 704, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 685, "y": 613, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [542, 145, 663, 243],
                "x": 603,
                "y": 243,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 414, "y": 572, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 185, "y": 450, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 335, "y": 449, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 58, "y": 616, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 595, "y": 441, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 500, "y": 525, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 386, "y": 402, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [912, 609, 1033, 711],
                "x": 973,
                "y": 711,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 657, "y": 582, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 631, "y": 235, "track_id": None},
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 421, "y": 610, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 201, "y": 418, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [279, 322, 398, 425],
                "x": 337,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 63, "y": 645, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [580, 366, 698, 465],
                "x": 640,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [396, 402, 519, 501],
                "x": 458,
                "y": 503,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [347, 298, 466, 398],
                "x": 408,
                "y": 396,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 970, "y": 718, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [569, 446, 686, 547],
                "x": 628,
                "y": 546,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 658, "y": 235, "track_id": None},
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 429, "y": 649, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 216, "y": 386, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 338, "y": 397, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 68, "y": 672, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 685, "y": 484, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 416, "y": 479, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 429, "y": 393, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 968, "y": 724, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [539, 405, 662, 508],
                "x": 600,
                "y": 506,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 686, "y": 242, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 436, "y": 684, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 232, "y": 354, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 339, "y": 371, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 72, "y": 696, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 730, "y": 497, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 375, "y": 452, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 451, "y": 392, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 966, "y": 730, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 571, "y": 463, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 713, "y": 258, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [384, 616, 503, 715],
                "x": 443,
                "y": 715,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 247, "y": 322, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 341, "y": 346, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 77, "y": 719, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 775, "y": 503, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 333, "y": 425, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [413, 296, 535, 393],
                "x": 473,
                "y": 395,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 964, "y": 736, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 542, "y": 419, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 741, "y": 283, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [390, 638, 511, 739],
                "x": 451,
                "y": 740,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [203, 190, 323, 289],
                "x": 263,
                "y": 291,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 342, "y": 321, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [21, 638, 140, 737],
                "x": 82,
                "y": 739,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 820, "y": 502, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 291, "y": 398, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 495, "y": 399, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 961, "y": 742, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 514, "y": 373, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 768, "y": 315, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 458, "y": 756, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 278, "y": 260, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 343, "y": 297, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [29, 655, 148, 756],
                "x": 87,
                "y": 757,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 865, "y": 493, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 250, "y": 373, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 517, "y": 407, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 959, "y": 747, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 485, "y": 327, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [734, 255, 858, 355],
                "x": 796,
                "y": 357,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 466, "y": 761, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 294, "y": 230, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 344, "y": 273, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 92, "y": 773, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 910, "y": 475, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [147, 252, 268, 350],
                "x": 208,
                "y": 351,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 539, "y": 416, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 957, "y": 752, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [396, 183, 516, 280],
                "x": 457,
                "y": 281,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 823, "y": 407, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 473, "y": 754, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 309, "y": 201, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 346, "y": 250, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 97, "y": 787, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 955, "y": 447, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 166, "y": 333, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 561, "y": 427, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 955, "y": 757, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 428, "y": 237, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [791, 368, 910, 468],
                "x": 851,
                "y": 467,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [420, 632, 542, 730],
                "x": 481,
                "y": 732,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 325, "y": 172, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [288, 128, 407, 227],
                "x": 347,
                "y": 227,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 102, "y": 799, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 410, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 125, "y": 321, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 583, "y": 439, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 952, "y": 762, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 400, "y": 194, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [819, 436, 939, 534],
                "x": 878,
                "y": 536,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 488, "y": 694, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [278, 46, 398, 143],
                "x": 340,
                "y": 145,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 348, "y": 204, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 83, "y": 315, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [544, 356, 667, 453],
                "x": 605,
                "y": 454,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 950, "y": 766, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 371, "y": 155, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 906, "y": 614, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 495, "y": 636, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 356, "y": 119, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 350, "y": 182, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 41, "y": 317, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 627, "y": 469, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 948, "y": 770, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 342, "y": 120, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [871, 602, 995, 703],
                "x": 933,
                "y": 702,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [444, 457, 565, 560],
                "x": 503,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [312, -3, 430, 93],
                "x": 371,
                "y": 95,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 351, "y": 160, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 0, "y": 329, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 649, "y": 485, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [884, 674, 1004, 772],
                "x": 946,
                "y": 774,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 314, "y": 90, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 961, "y": 799, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [450, 356, 571, 459],
                "x": 510,
                "y": 458,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 387, "y": 72, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [292, 39, 414, 140],
                "x": 352,
                "y": 139,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [610, 404, 733, 505],
                "x": 671,
                "y": 503,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 943, "y": 777, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [223, -34, 344, 66],
                "x": 285,
                "y": 65,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 518, "y": 332, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 402, "y": 51, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 354, "y": 118, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 693, "y": 521, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [882, 681, 1003, 779],
                "x": 941,
                "y": 780,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 257, "y": 46, "track_id": None},
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 525, "y": 180, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [357, -69, 476, 30],
                "x": 418,
                "y": 32,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [295, -5, 416, 97],
                "x": 355,
                "y": 97,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 714, "y": 539, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 939, "y": 783, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 228, "y": 35, "track_id": None},
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 533, "y": 0, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 433, "y": 15, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 356, "y": 77, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [677, 456, 797, 555],
                "x": 736,
                "y": 557,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 937, "y": 786, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 200, "y": 32, "track_id": None},
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 449, "y": 0, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 358, "y": 57, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 758, "y": 576, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 934, "y": 788, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [109, -60, 231, 37],
                "x": 171,
                "y": 38,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [297, -64, 418, 38],
                "x": 359,
                "y": 37,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 780, "y": 594, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 932, "y": 791, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [80, -48, 203, 53],
                "x": 142,
                "y": 54,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 360, "y": 18, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 802, "y": 612, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 930, "y": 793, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [53, -17, 172, 79],
                "x": 114,
                "y": 81,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 362, "y": 0, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 824, "y": 629, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 928, "y": 794, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 85, "y": 119, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 6, "bounding_box": [], "x": 846, "y": 645, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 925, "y": 796, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [-3, 71, 118, 169],
                "x": 57,
                "y": 170,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 6,
                "bounding_box": [809, 558, 928, 661],
                "x": 868,
                "y": 660,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 923, "y": 797, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 28, "y": 234, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 6,
                "bounding_box": [831, 574, 950, 674],
                "x": 890,
                "y": 674,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [862, 699, 980, 800],
                "x": 921,
                "y": 798,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-58, 212, 58, 313],
                "x": 0,
                "y": 312,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 6, "bounding_box": [], "x": 912, "y": 687, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 919, "y": 799, "track_id": None},
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 6, "bounding_box": [], "x": 934, "y": 697, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 916, "y": 799, "track_id": None},
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 6,
                "bounding_box": [898, 607, 1014, 706],
                "x": 956,
                "y": 706,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 914, "y": 800, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {"cb_id": 6, "bounding_box": [], "x": 978, "y": 713, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 912, "y": 800, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 6, "bounding_box": [], "x": 1000, "y": 717, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 910, "y": 799, "track_id": None},
        ],
    },
]
