country_balls_amount = 15
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 1000, "y": 179, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 0, "y": 745, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 709, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [950, 241, 1055, 327],
                "x": 1000,
                "y": 334,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 769, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 0, "y": 98, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 1000, "y": 374, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [946, 221, 1057, 310],
                "x": 1000,
                "y": 320,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 1000, "y": 538, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 920, "y": 800, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 727, "y": 799, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 0, "y": 616, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [948, 387, 1062, 500],
                "x": 1000,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [948, 83, 1055, 187],
                "x": 1000,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [938, 114, 1069, 208],
                "x": 1000,
                "y": 204,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 976, "y": 316, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 38, "y": 701, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 4, "y": 665, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [915, 196, 1029, 298],
                "x": 979,
                "y": 298,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 975, "y": 755, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 20, "y": 119, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 975, "y": 348, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 996, "y": 349, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 970, "y": 482, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [862, 659, 969, 771],
                "x": 918,
                "y": 769,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 696, "y": 674, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 34, "y": 558, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 970, "y": 463, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 979, "y": 203, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [916, 204, 1042, 307],
                "x": 977,
                "y": 306,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 953, "y": 406, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 76, "y": 659, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-60, 530, 72, 630],
                "x": 9,
                "y": 623,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [891, 173, 1025, 266],
                "x": 958,
                "y": 266,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [892, 646, 1007, 729],
                "x": 950,
                "y": 737,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-11, 44, 100, 132],
                "x": 41,
                "y": 140,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 950, "y": 325, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [926, 271, 1051, 375],
                "x": 993,
                "y": 377,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 941, "y": 434, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 917, "y": 740, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 666, "y": 572, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 68, "y": 513, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 941, "y": 434, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [899, 130, 1010, 221],
                "x": 959,
                "y": 221,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 955, "y": 395, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 930, "y": 455, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 115, "y": 620, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 13, "y": 582, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 937, "y": 240, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 925, "y": 716, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 62, "y": 161, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 925, "y": 305, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 989, "y": 404, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 911, "y": 394, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 916, "y": 711, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 636, "y": 492, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 103, "y": 479, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [860, 306, 979, 405],
                "x": 911,
                "y": 410,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 938, "y": 238, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 933, "y": 470, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 907, "y": 471, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 153, "y": 584, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-41, 440, 71, 538],
                "x": 18,
                "y": 543,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 917, "y": 217, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 900, "y": 693, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 83, "y": 181, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 900, "y": 287, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 986, "y": 431, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 882, "y": 360, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 915, "y": 683, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 605, "y": 432, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [77, 364, 190, 458],
                "x": 137,
                "y": 456,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 882, "y": 390, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 918, "y": 255, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [840, 435, 967, 528],
                "x": 910,
                "y": 534,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [820, 351, 933, 456],
                "x": 883,
                "y": 459,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 192, "y": 549, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 22, "y": 506, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 896, "y": 199, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 875, "y": 668, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 104, "y": 201, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [822, 168, 931, 268],
                "x": 875,
                "y": 271,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 983, "y": 457, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 852, "y": 333, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [863, 560, 970, 648],
                "x": 913,
                "y": 655,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [511, 287, 632, 394],
                "x": 575,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [120, 344, 232, 439],
                "x": 172,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [792, 265, 913, 373],
                "x": 853,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [836, 182, 965, 264],
                "x": 897,
                "y": 272,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 888, "y": 586, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 860, "y": 425, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 230, "y": 517, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 27, "y": 470, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 875, "y": 184, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 850, "y": 640, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 125, "y": 221, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 850, "y": 258, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 979, "y": 482, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [770, 220, 879, 315],
                "x": 823,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [846, 530, 967, 625],
                "x": 912,
                "y": 628,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 545, "y": 364, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 206, "y": 435, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 823, "y": 362, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 877, "y": 288, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 866, "y": 628, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 837, "y": 375, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 269, "y": 487, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-20, 334, 94, 441],
                "x": 31,
                "y": 435,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 855, "y": 173, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 825, "y": 612, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 145, "y": 240, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 825, "y": 246, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [916, 413, 1033, 511],
                "x": 976,
                "y": 507,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 794, "y": 295, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [855, 506, 962, 605],
                "x": 911,
                "y": 602,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [452, 261, 574, 358],
                "x": 514,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [179, 337, 303, 435],
                "x": 241,
                "y": 435,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 794, "y": 354, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 857, "y": 303, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 843, "y": 660, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 814, "y": 316, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [246, 353, 360, 451],
                "x": 307,
                "y": 460,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 36, "y": 402, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 834, "y": 166, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 800, "y": 582, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 166, "y": 258, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 800, "y": 236, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 972, "y": 530, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 764, "y": 283, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 910, "y": 576, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 484, "y": 355, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 275, "y": 441, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 764, "y": 350, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 836, "y": 318, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 821, "y": 682, "track_id": None},
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [731, 161, 860, 262],
                "x": 791,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [287, 344, 397, 442],
                "x": 346,
                "y": 435,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 40, "y": 371, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [763, 55, 882, 171],
                "x": 813,
                "y": 162,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 775, "y": 551, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [135, 178, 247, 275],
                "x": 187,
                "y": 276,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 775, "y": 228, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 969, "y": 553, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [668, 176, 800, 282],
                "x": 735,
                "y": 276,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 908, "y": 551, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 454, "y": 367, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 310, "y": 452, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 735, "y": 350, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 816, "y": 333, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 799, "y": 697, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 767, "y": 194, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [321, 307, 438, 407],
                "x": 384,
                "y": 412,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 45, "y": 341, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 792, "y": 161, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 750, "y": 520, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 208, "y": 293, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 750, "y": 222, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [915, 476, 1032, 566],
                "x": 966,
                "y": 575,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 705, "y": 272, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [852, 434, 960, 530],
                "x": 907,
                "y": 526,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [374, 299, 485, 383],
                "x": 424,
                "y": 389,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 344, "y": 467, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 706, "y": 353, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [725, 238, 854, 338],
                "x": 795,
                "y": 347,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 776, "y": 703, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 744, "y": 143, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 423, "y": 391, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 49, "y": 312, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 772, "y": 164, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 725, "y": 488, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 229, "y": 309, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [658, 125, 789, 225],
                "x": 725,
                "y": 217,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 962, "y": 597, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 676, "y": 272, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [853, 396, 961, 500],
                "x": 906,
                "y": 502,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 393, "y": 417, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 379, "y": 484, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 676, "y": 360, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 775, "y": 360, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 754, "y": 703, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 721, "y": 108, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 461, "y": 372, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 54, "y": 285, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 751, "y": 169, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 700, "y": 456, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [198, 229, 310, 318],
                "x": 250,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [638, 105, 767, 213],
                "x": 700,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [897, 515, 1028, 621],
                "x": 959,
                "y": 617,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 647, "y": 274, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 905, "y": 479, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 363, "y": 451, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 413, "y": 503, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 647, "y": 371, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [692, 264, 818, 382],
                "x": 755,
                "y": 373,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 732, "y": 696, "track_id": None},
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [633, -7, 750, 101],
                "x": 698,
                "y": 94,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 500, "y": 356, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 58, "y": 259, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 730, "y": 177, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [614, 329, 736, 428],
                "x": 675,
                "y": 425,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [216, 239, 330, 343],
                "x": 270,
                "y": 340,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 675, "y": 211, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 955, "y": 637, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 617, "y": 279, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [853, 347, 958, 453],
                "x": 904,
                "y": 456,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 333, "y": 489, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [397, 424, 518, 525],
                "x": 448,
                "y": 522,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 617, "y": 385, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [675, 291, 798, 380],
                "x": 734,
                "y": 386,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [649, 583, 778, 690],
                "x": 709,
                "y": 683,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 675, "y": 107, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 538, "y": 342, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 63, "y": 235, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [657, 81, 773, 191],
                "x": 710,
                "y": 187,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 650, "y": 394, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 291, "y": 355, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [592, 107, 714, 205],
                "x": 650,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [900, 560, 1005, 650],
                "x": 952,
                "y": 657,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [519, 176, 655, 280],
                "x": 588,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [836, 343, 966, 437],
                "x": 902,
                "y": 434,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 302, "y": 528, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 482, "y": 540, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 588, "y": 402, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 714, "y": 398, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 687, "y": 666, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [600, 58, 719, 161],
                "x": 651,
                "y": 154,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 576, "y": 330, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 67, "y": 212, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 689, "y": 200, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 625, "y": 364, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 312, "y": 368, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [571, 110, 692, 208],
                "x": 625,
                "y": 209,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 949, "y": 675, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 558, "y": 293, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [844, 321, 951, 412],
                "x": 901,
                "y": 412,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [213, 471, 326, 558],
                "x": 272,
                "y": 567,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 517, "y": 557, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [493, 330, 611, 414],
                "x": 559,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 693, "y": 409, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 665, "y": 644, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 628, "y": 240, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 615, "y": 320, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 72, "y": 190, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [612, 114, 734, 222],
                "x": 668,
                "y": 215,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 600, "y": 335, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 333, "y": 381, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 600, "y": 210, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 945, "y": 693, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 529, "y": 302, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 900, "y": 391, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [181, 508, 311, 596],
                "x": 242,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [488, 465, 614, 581],
                "x": 551,
                "y": 571,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 529, "y": 448, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 673, "y": 420, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 642, "y": 619, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 605, "y": 373, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [593, 207, 716, 303],
                "x": 653,
                "y": 313,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 76, "y": 169, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 647, "y": 232, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 575, "y": 308, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 354, "y": 393, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 575, "y": 211, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [885, 610, 995, 700],
                "x": 942,
                "y": 710,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 500, "y": 311, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 899, "y": 370, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 212, "y": 637, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 586, "y": 581, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [444, 385, 553, 467],
                "x": 500,
                "y": 475,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 653, "y": 431, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 620, "y": 591, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 582, "y": 557, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [622, 207, 747, 305],
                "x": 692,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [18, 40, 138, 144],
                "x": 81,
                "y": 150,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 627, "y": 251, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 550, "y": 282, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 375, "y": 404, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [494, 118, 602, 220],
                "x": 550,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [885, 620, 989, 718],
                "x": 938,
                "y": 727,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [419, 213, 521, 323],
                "x": 470,
                "y": 319,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 897, "y": 350, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [113, 568, 245, 659],
                "x": 181,
                "y": 665,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 620, "y": 587, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 470, "y": 505, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [569, 350, 691, 444],
                "x": 632,
                "y": 440,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 598, "y": 561, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [502, 693, 624, 807],
                "x": 559,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 730, "y": 304, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 85, "y": 132, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 606, "y": 272, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 525, "y": 259, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 395, "y": 415, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [463, 114, 580, 224],
                "x": 525,
                "y": 215,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 935, "y": 743, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 441, "y": 327, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 896, "y": 331, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 151, "y": 685, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 655, "y": 586, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 441, "y": 539, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 612, "y": 450, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 575, "y": 529, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 769, "y": 303, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 90, "y": 115, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 585, "y": 293, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 500, "y": 238, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 416, "y": 424, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 500, "y": 218, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 932, "y": 758, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 411, "y": 334, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 895, "y": 312, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 121, "y": 696, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [630, 482, 755, 573],
                "x": 689,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [342, 468, 467, 565],
                "x": 412,
                "y": 575,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 591, "y": 459, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 553, "y": 497, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [743, 209, 875, 308],
                "x": 807,
                "y": 304,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 94, "y": 99, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 565, "y": 317, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [414, 117, 532, 220],
                "x": 475,
                "y": 220,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [386, 341, 496, 442],
                "x": 437,
                "y": 433,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 475, "y": 221, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 928, "y": 772, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 382, "y": 339, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 894, "y": 294, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 90, "y": 696, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 724, "y": 562, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 382, "y": 615, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 571, "y": 467, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 531, "y": 465, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 846, "y": 308, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 99, "y": 85, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 544, "y": 341, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 450, "y": 204, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 458, "y": 441, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 450, "y": 224, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 925, "y": 786, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 352, "y": 341, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 893, "y": 276, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [3, 591, 126, 692],
                "x": 60,
                "y": 683,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [691, 445, 812, 535],
                "x": 758,
                "y": 537,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 353, "y": 657, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 551, "y": 475, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 508, "y": 433, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [825, 203, 943, 315],
                "x": 884,
                "y": 313,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 103, "y": 72, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [470, 272, 585, 368],
                "x": 523,
                "y": 366,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [370, 89, 493, 192],
                "x": 425,
                "y": 192,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 479, "y": 447, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 425, "y": 227, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 922, "y": 800, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [271, 247, 386, 348],
                "x": 323,
                "y": 341,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 891, "y": 259, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 30, "y": 655, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [733, 400, 853, 506],
                "x": 793,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [257, 594, 393, 696],
                "x": 323,
                "y": 702,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 530, "y": 482, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 486, "y": 403, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 923, "y": 321, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 108, "y": 59, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 502, "y": 393, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 400, "y": 184, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 500, "y": 453, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 400, "y": 229, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [230, 247, 345, 348],
                "x": 294,
                "y": 338,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [823, 150, 946, 237],
                "x": 890,
                "y": 243,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 0, "y": 611, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 827, "y": 454, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 294, "y": 749, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [446, 395, 576, 499],
                "x": 510,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 464, "y": 376, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 961, "y": 331, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 112, "y": 48, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 482, "y": 419, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 375, "y": 180, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 520, "y": 458, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [313, 139, 444, 226],
                "x": 375,
                "y": 232,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 264, "y": 331, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 889, "y": 227, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 862, "y": 395, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 265, "y": 800, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 489, "y": 496, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [390, 245, 494, 342],
                "x": 441,
                "y": 351,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 343, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 117, "y": 38, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 461, "y": 446, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 350, "y": 179, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 541, "y": 461, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 350, "y": 234, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 235, "y": 320, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 888, "y": 211, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 896, "y": 322, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 469, "y": 501, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 419, "y": 329, "track_id": None},
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 121, "y": 29, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [388, 380, 498, 484],
                "x": 440,
                "y": 474,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 325, "y": 184, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 562, "y": 464, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 325, "y": 236, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 205, "y": 304, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 886, "y": 196, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [871, 126, 983, 239],
                "x": 931,
                "y": 235,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 448, "y": 507, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 397, "y": 312, "track_id": None},
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [63, -82, 190, 22],
                "x": 126,
                "y": 21,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 420, "y": 501, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 300, "y": 193, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 583, "y": 465, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [238, 143, 352, 229],
                "x": 300,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [116, 174, 241, 278],
                "x": 176,
                "y": 283,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 885, "y": 182, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 965, "y": 131, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 428, "y": 512, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 374, "y": 300, "track_id": None},
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [72, -95, 196, 14],
                "x": 130,
                "y": 14,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 399, "y": 529, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 275, "y": 207, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [550, 357, 672, 455],
                "x": 604,
                "y": 465,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 275, "y": 237, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 147, "y": 256, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 884, "y": 168, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 1000, "y": 12, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [357, 423, 473, 515],
                "x": 408,
                "y": 516,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 352, "y": 293, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 135, "y": 8, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 378, "y": 556, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 250, "y": 227, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 625, "y": 464, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [188, 136, 305, 238],
                "x": 250,
                "y": 236,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 117, "y": 223, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 883, "y": 155, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 387, "y": 520, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 330, "y": 293, "track_id": None},
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 139, "y": 4, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 357, "y": 583, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 225, "y": 252, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 645, "y": 462, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [170, 125, 275, 235],
                "x": 225,
                "y": 234,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [34, 81, 151, 180],
                "x": 88,
                "y": 184,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 882, "y": 142, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 367, "y": 523, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 307, "y": 300, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [80, -101, 195, -7],
                "x": 144,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 337, "y": 609, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 200, "y": 283, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 666, "y": 459, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 200, "y": 231, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 58, "y": 137, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 880, "y": 130, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [281, 434, 415, 526],
                "x": 346,
                "y": 526,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 285, "y": 315, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [249, 527, 371, 631],
                "x": 316,
                "y": 634,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 175, "y": 321, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 687, "y": 454, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 175, "y": 227, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 29, "y": 82, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 879, "y": 118, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 326, "y": 528, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [213, 246, 319, 332],
                "x": 263,
                "y": 338,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 295, "y": 659, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 150, "y": 365, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 708, "y": 448, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 150, "y": 222, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [-70, -86, 60, 19],
                "x": 0,
                "y": 20,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 878, "y": 107, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 306, "y": 530, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 240, "y": 371, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 275, "y": 682, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 125, "y": 417, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 729, "y": 441, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [56, 110, 181, 213],
                "x": 125,
                "y": 214,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 877, "y": 96, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 285, "y": 531, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 218, "y": 413, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 254, "y": 704, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [41, 371, 165, 483],
                "x": 100,
                "y": 475,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 750, "y": 433, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [50, 109, 165, 199],
                "x": 100,
                "y": 206,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 875, "y": 86, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 265, "y": 531, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 196, "y": 467, "track_id": None},
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 233, "y": 725, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 75, "y": 541, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [716, 327, 836, 423],
                "x": 770,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 75, "y": 195, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 874, "y": 77, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 244, "y": 532, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [107, 427, 238, 527],
                "x": 173,
                "y": 531,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 212, "y": 744, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 50, "y": 615, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [730, 315, 859, 405],
                "x": 791,
                "y": 412,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 50, "y": 183, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 873, "y": 68, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 224, "y": 531, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 151, "y": 608, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 192, "y": 761, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 25, "y": 697, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 812, "y": 399, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 25, "y": 168, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 872, "y": 59, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 204, "y": 530, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [59, 591, 196, 701],
                "x": 129,
                "y": 697,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 171, "y": 776, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 0, "y": 788, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [768, 277, 895, 387],
                "x": 833,
                "y": 385,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 0, "y": 152, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 871, "y": 51, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 183, "y": 529, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 107, "y": 800, "track_id": None},
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 150, "y": 789, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 854, "y": 369, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 869, "y": 43, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 163, "y": 527, "track_id": None},
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 130, "y": 800, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 875, "y": 352, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [804, -73, 921, 40],
                "x": 868,
                "y": 36,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 142, "y": 524, "track_id": None},
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {"cb_id": 5, "bounding_box": [], "x": 895, "y": 334, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [800, -80, 918, 36],
                "x": 867,
                "y": 29,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 122, "y": 521, "track_id": None},
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {"cb_id": 5, "bounding_box": [], "x": 916, "y": 313, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [816, -79, 919, 28],
                "x": 866,
                "y": 23,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [51, 417, 165, 520],
                "x": 102,
                "y": 518,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [884, 195, 987, 302],
                "x": 937,
                "y": 292,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 864, "y": 17, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 81, "y": 514, "track_id": None},
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {"cb_id": 5, "bounding_box": [], "x": 958, "y": 268, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 863, "y": 12, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 61, "y": 509, "track_id": None},
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {"cb_id": 5, "bounding_box": [], "x": 979, "y": 243, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 862, "y": 8, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 40, "y": 504, "track_id": None},
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {"cb_id": 5, "bounding_box": [], "x": 1000, "y": 217, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 861, "y": 3, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 20, "y": 499, "track_id": None},
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {"cb_id": 9, "bounding_box": [], "x": 860, "y": 0, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [-56, 400, 52, 494],
                "x": 0,
                "y": 493,
                "track_id": None,
            },
        ],
    },
]
