country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 0, "y": 468, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [82, 699, 198, 798],
                "x": 140,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [940, 211, 1059, 310],
                "x": 1000,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [940, 586, 1062, 684],
                "x": 1000,
                "y": 685,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [938, 385, 1060, 484],
                "x": 1000,
                "y": 485,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-38, 340, 79, 440],
                "x": 21,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [96, 614, 219, 713],
                "x": 158,
                "y": 714,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [916, 260, 1035, 360],
                "x": 977,
                "y": 362,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [916, 517, 1033, 616],
                "x": 975,
                "y": 616,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [909, 417, 1028, 519],
                "x": 968,
                "y": 517,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-19, 312, 102, 412],
                "x": 43,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [118, 537, 239, 635],
                "x": 177,
                "y": 636,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [892, 308, 1013, 409],
                "x": 954,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [891, 457, 1010, 556],
                "x": 951,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [875, 438, 994, 535],
                "x": 936,
                "y": 536,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 65, "y": 392, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [134, 464, 255, 563],
                "x": 196,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [873, 349, 992, 445],
                "x": 931,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [868, 407, 986, 505],
                "x": 926,
                "y": 507,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 904, "y": 543, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [26, 271, 147, 373],
                "x": 86,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [156, 399, 276, 502],
                "x": 214,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [851, 378, 968, 481],
                "x": 909,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [842, 367, 961, 465],
                "x": 902,
                "y": 466,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 872, "y": 539, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [50, 258, 167, 354],
                "x": 108,
                "y": 356,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [172, 342, 295, 442],
                "x": 233,
                "y": 442,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [828, 406, 948, 508],
                "x": 886,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [819, 333, 939, 434],
                "x": 877,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [781, 426, 900, 525],
                "x": 841,
                "y": 527,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [70, 240, 190, 344],
                "x": 130,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [191, 290, 311, 388],
                "x": 252,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [802, 428, 922, 529],
                "x": 863,
                "y": 528,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [792, 307, 912, 407],
                "x": 853,
                "y": 408,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 809, "y": 507, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [93, 230, 213, 329],
                "x": 152,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [212, 242, 328, 343],
                "x": 270,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [782, 445, 900, 544],
                "x": 840,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [768, 288, 891, 389],
                "x": 829,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [719, 381, 835, 482],
                "x": 777,
                "y": 482,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 173, "y": 321, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [229, 205, 351, 303],
                "x": 289,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [756, 455, 879, 552],
                "x": 818,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [745, 277, 866, 380],
                "x": 804,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [686, 351, 806, 452],
                "x": 745,
                "y": 453,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [133, 214, 253, 314],
                "x": 195,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [246, 169, 367, 267],
                "x": 308,
                "y": 267,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [733, 459, 857, 562],
                "x": 795,
                "y": 561,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [721, 271, 838, 371],
                "x": 780,
                "y": 372,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 713, "y": 422, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [155, 209, 275, 312],
                "x": 217,
                "y": 310,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [266, 135, 385, 237],
                "x": 326,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [714, 463, 831, 563],
                "x": 772,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [696, 273, 816, 370],
                "x": 755,
                "y": 372,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [624, 291, 744, 389],
                "x": 682,
                "y": 390,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [181, 205, 299, 307],
                "x": 239,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [284, 109, 406, 212],
                "x": 345,
                "y": 211,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [692, 461, 811, 563],
                "x": 750,
                "y": 561,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [670, 276, 791, 375],
                "x": 731,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [590, 258, 708, 362],
                "x": 650,
                "y": 360,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [202, 207, 318, 304],
                "x": 260,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [306, 89, 423, 190],
                "x": 364,
                "y": 190,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [666, 454, 786, 556],
                "x": 727,
                "y": 555,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [647, 283, 768, 386],
                "x": 707,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [560, 234, 678, 332],
                "x": 618,
                "y": 332,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [222, 206, 341, 304],
                "x": 282,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [323, 74, 441, 174],
                "x": 383,
                "y": 173,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 704, "y": 547, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [622, 295, 744, 398],
                "x": 682,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [524, 210, 644, 310],
                "x": 586,
                "y": 308,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [242, 207, 362, 306],
                "x": 304,
                "y": 308,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [340, 63, 462, 160],
                "x": 401,
                "y": 161,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [623, 435, 740, 537],
                "x": 681,
                "y": 536,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 658, "y": 411, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [495, 190, 613, 288],
                "x": 554,
                "y": 290,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [265, 213, 385, 314],
                "x": 326,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [358, 52, 480, 150],
                "x": 420,
                "y": 152,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 659, "y": 522, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [572, 329, 695, 426],
                "x": 633,
                "y": 428,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [465, 182, 583, 278],
                "x": 523,
                "y": 280,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [285, 216, 405, 318],
                "x": 347,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [380, 46, 498, 147],
                "x": 439,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [578, 406, 697, 507],
                "x": 636,
                "y": 506,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 609, "y": 447, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [429, 180, 551, 279],
                "x": 491,
                "y": 279,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 369, "y": 323, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [395, 47, 519, 143],
                "x": 457,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [551, 389, 672, 489],
                "x": 613,
                "y": 488,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [523, 369, 646, 465],
                "x": 585,
                "y": 467,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [397, 188, 519, 290],
                "x": 459,
                "y": 289,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [331, 232, 452, 332],
                "x": 391,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [415, 45, 534, 144],
                "x": 476,
                "y": 146,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 590, "y": 469, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [500, 385, 620, 486],
                "x": 560,
                "y": 487,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 427, "y": 311, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [351, 236, 473, 337],
                "x": 413,
                "y": 338,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 495, "y": 150, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [510, 347, 629, 448],
                "x": 568,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [478, 409, 595, 507],
                "x": 536,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [333, 249, 455, 348],
                "x": 395,
                "y": 348,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [372, 248, 495, 349],
                "x": 434,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [451, 54, 573, 155],
                "x": 513,
                "y": 156,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [484, 327, 604, 429],
                "x": 545,
                "y": 428,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [449, 430, 569, 529],
                "x": 511,
                "y": 528,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [304, 298, 426, 398],
                "x": 364,
                "y": 400,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [394, 256, 514, 355],
                "x": 456,
                "y": 356,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 532, "y": 165, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [462, 306, 580, 405],
                "x": 522,
                "y": 407,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 487, "y": 546, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 332, "y": 470, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [420, 264, 538, 364],
                "x": 478,
                "y": 366,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [492, 76, 609, 177],
                "x": 551,
                "y": 175,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [440, 285, 561, 383],
                "x": 500,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [403, 463, 521, 561],
                "x": 462,
                "y": 563,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 300, "y": 558, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 500, "y": 377, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [510, 89, 630, 189],
                "x": 570,
                "y": 188,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [415, 265, 539, 364],
                "x": 477,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [379, 475, 498, 577],
                "x": 438,
                "y": 577,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 268, "y": 668, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 521, "y": 387, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [530, 103, 646, 204],
                "x": 588,
                "y": 202,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 454, "y": 344, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 414, "y": 589, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [179, 699, 296, 800],
                "x": 237,
                "y": 799,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [485, 299, 602, 399],
                "x": 543,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [549, 115, 665, 216],
                "x": 607,
                "y": 217,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [370, 223, 489, 324],
                "x": 431,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [328, 496, 448, 597],
                "x": 389,
                "y": 597,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [507, 307, 625, 409],
                "x": 565,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [564, 135, 687, 232],
                "x": 626,
                "y": 233,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 409, "y": 307, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 365, "y": 600, "track_id": None},
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 586, "y": 419, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [584, 149, 706, 252],
                "x": 644,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [326, 189, 448, 292],
                "x": 386,
                "y": 291,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 340, "y": 599, "track_id": None},
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [546, 332, 666, 428],
                "x": 608,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [604, 169, 721, 267],
                "x": 663,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [301, 175, 424, 277],
                "x": 363,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [254, 491, 375, 594],
                "x": 316,
                "y": 593,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [571, 341, 692, 441],
                "x": 630,
                "y": 440,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [623, 184, 744, 286],
                "x": 682,
                "y": 286,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 340, "y": 265, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [233, 478, 353, 579],
                "x": 292,
                "y": 580,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 652, "y": 449, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 700, "y": 304, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 318, "y": 256, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 267, "y": 562, "track_id": None},
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [611, 360, 735, 456],
                "x": 673,
                "y": 458,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 719, "y": 322, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [237, 149, 354, 250],
                "x": 295,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [185, 438, 302, 537],
                "x": 243,
                "y": 536,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [636, 368, 757, 467],
                "x": 695,
                "y": 466,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [678, 238, 798, 337],
                "x": 738,
                "y": 339,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 272, "y": 248, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [158, 403, 280, 503],
                "x": 218,
                "y": 502,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 717, "y": 474, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 756, "y": 355, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [189, 152, 310, 251],
                "x": 250,
                "y": 250,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [134, 358, 252, 458],
                "x": 194,
                "y": 460,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [677, 381, 799, 480],
                "x": 739,
                "y": 480,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 775, "y": 371, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 227, "y": 256, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [110, 308, 229, 409],
                "x": 170,
                "y": 409,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [700, 384, 818, 486],
                "x": 760,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [732, 286, 853, 383],
                "x": 794,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [144, 167, 263, 268],
                "x": 204,
                "y": 266,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [86, 250, 207, 349],
                "x": 145,
                "y": 348,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 782, "y": 489, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [754, 299, 875, 396],
                "x": 813,
                "y": 397,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 181, "y": 282, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 121, "y": 278, "track_id": None},
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [744, 393, 864, 493],
                "x": 804,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [773, 306, 893, 409],
                "x": 831,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [98, 204, 219, 303],
                "x": 159,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [36, 97, 158, 194],
                "x": 96,
                "y": 196,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [766, 394, 888, 493],
                "x": 826,
                "y": 492,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [788, 319, 912, 416],
                "x": 850,
                "y": 417,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [75, 226, 196, 328],
                "x": 136,
                "y": 328,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 72, "y": 104, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [787, 393, 905, 492],
                "x": 847,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [809, 326, 927, 426],
                "x": 869,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [53, 260, 171, 360],
                "x": 113,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-10, -99, 109, -2],
                "x": 48,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 869, "y": 488, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [827, 329, 949, 426],
                "x": 887,
                "y": 428,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 90, "y": 399, "track_id": None},
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [833, 384, 952, 485],
                "x": 891,
                "y": 484,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [847, 328, 967, 430],
                "x": 906,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [6, 345, 128, 444],
                "x": 68,
                "y": 444,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [851, 377, 971, 479],
                "x": 913,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [864, 330, 986, 429],
                "x": 925,
                "y": 428,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-13, 394, 105, 496],
                "x": 45,
                "y": 496,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [876, 368, 996, 468],
                "x": 934,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [884, 325, 1003, 422],
                "x": 943,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 22, "y": 555, "track_id": None},
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 956, "y": 457, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [901, 315, 1022, 414],
                "x": 962,
                "y": 414,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 623, "track_id": None},
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [918, 344, 1038, 445],
                "x": 978,
                "y": 444,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [921, 304, 1043, 401],
                "x": 981,
                "y": 402,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [938, 329, 1061, 429],
                "x": 1000,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [941, 284, 1058, 387],
                "x": 1000,
                "y": 385,
                "track_id": None,
            },
        ],
    },
]
