country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [938, -76, 1058, 31],
                "x": 1000,
                "y": 26,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-12, 702, 115, 794],
                "x": 53,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 52, "y": 800, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [609, -99, 730, 5],
                "x": 674,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-58, 245, 64, 342],
                "x": 0,
                "y": 345,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [931, -12, 1053, 88],
                "x": 995,
                "y": 85,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-11, 692, 116, 793],
                "x": 51,
                "y": 791,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [9, 676, 127, 771],
                "x": 72,
                "y": 776,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [613, -9, 728, 94],
                "x": 671,
                "y": 93,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 25, "y": 366, "track_id": None},
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 991, "y": 140, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 49, "y": 782, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [28, 656, 153, 757],
                "x": 92,
                "y": 752,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [611, 85, 731, 177],
                "x": 668,
                "y": 180,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 51, "y": 385, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [925, 91, 1051, 194],
                "x": 987,
                "y": 193,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 47, "y": 773, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [54, 633, 168, 732],
                "x": 112,
                "y": 728,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [609, 158, 728, 256],
                "x": 666,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [19, 300, 140, 404],
                "x": 76,
                "y": 402,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [922, 138, 1047, 247],
                "x": 983,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-20, 659, 103, 758],
                "x": 45,
                "y": 763,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 132, "y": 704, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [598, 237, 719, 332],
                "x": 663,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [41, 320, 160, 416],
                "x": 102,
                "y": 417,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 978, "y": 291, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-14, 650, 104, 759],
                "x": 43,
                "y": 754,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [92, 576, 210, 681],
                "x": 152,
                "y": 680,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 661, "y": 398, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 128, "y": 430, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [912, 234, 1031, 338],
                "x": 974,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-13, 642, 98, 747],
                "x": 42,
                "y": 744,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [117, 554, 233, 654],
                "x": 173,
                "y": 656,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [598, 360, 719, 454],
                "x": 658,
                "y": 457,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 153, "y": 441, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [907, 276, 1025, 379],
                "x": 970,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-23, 629, 105, 734],
                "x": 40,
                "y": 734,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 193, "y": 633, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 656, "y": 510, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [114, 349, 234, 450],
                "x": 179,
                "y": 451,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 966, "y": 419, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-18, 625, 102, 719],
                "x": 38,
                "y": 723,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [153, 510, 276, 614],
                "x": 213,
                "y": 609,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [596, 454, 711, 562],
                "x": 653,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [142, 361, 264, 462],
                "x": 205,
                "y": 459,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [898, 353, 1024, 457],
                "x": 961,
                "y": 457,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 36, "y": 713, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 233, "y": 586, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [592, 502, 715, 594],
                "x": 650,
                "y": 599,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 230, "y": 465, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [897, 388, 1012, 488],
                "x": 957,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-21, 599, 98, 707],
                "x": 34,
                "y": 702,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [193, 461, 313, 560],
                "x": 253,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [593, 534, 708, 640],
                "x": 648,
                "y": 635,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [191, 369, 319, 474],
                "x": 256,
                "y": 470,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [891, 425, 1018, 532],
                "x": 953,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-28, 594, 87, 688],
                "x": 32,
                "y": 691,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [213, 442, 334, 544],
                "x": 273,
                "y": 540,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 645, "y": 665, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [224, 368, 342, 477],
                "x": 282,
                "y": 473,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [894, 454, 1014, 554],
                "x": 949,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-32, 582, 86, 682],
                "x": 31,
                "y": 680,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 294, "y": 517, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [587, 590, 698, 691],
                "x": 643,
                "y": 690,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [245, 375, 371, 475],
                "x": 307,
                "y": 475,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 944, "y": 588, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-32, 566, 85, 669],
                "x": 29,
                "y": 669,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [249, 394, 373, 496],
                "x": 314,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [585, 605, 698, 715],
                "x": 640,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [275, 371, 398, 471],
                "x": 333,
                "y": 476,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [879, 520, 999, 618],
                "x": 940,
                "y": 615,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-38, 562, 84, 653],
                "x": 27,
                "y": 657,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [278, 375, 393, 469],
                "x": 334,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [583, 623, 701, 722],
                "x": 638,
                "y": 725,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [297, 375, 413, 472],
                "x": 358,
                "y": 475,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [873, 537, 992, 637],
                "x": 936,
                "y": 640,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-36, 542, 84, 647],
                "x": 25,
                "y": 645,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [291, 349, 416, 451],
                "x": 354,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [571, 632, 697, 738],
                "x": 635,
                "y": 736,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 384, "y": 474, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [870, 563, 992, 666],
                "x": 932,
                "y": 663,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-39, 538, 80, 634],
                "x": 23,
                "y": 633,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [312, 334, 435, 437],
                "x": 374,
                "y": 432,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 633, "y": 742, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [354, 367, 474, 466],
                "x": 410,
                "y": 471,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 927, "y": 684, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-41, 525, 78, 617],
                "x": 21,
                "y": 621,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [334, 317, 459, 417],
                "x": 394,
                "y": 412,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [575, 639, 691, 744],
                "x": 630,
                "y": 743,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 435, "y": 468, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [866, 602, 978, 708],
                "x": 923,
                "y": 703,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-43, 505, 79, 603],
                "x": 20,
                "y": 608,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [352, 287, 475, 391],
                "x": 415,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [562, 646, 684, 738],
                "x": 627,
                "y": 741,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [399, 365, 524, 465],
                "x": 461,
                "y": 464,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [859, 620, 976, 715],
                "x": 919,
                "y": 720,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-44, 490, 75, 592],
                "x": 18,
                "y": 595,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [373, 270, 496, 379],
                "x": 435,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [563, 633, 681, 738],
                "x": 625,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [431, 354, 545, 454],
                "x": 487,
                "y": 459,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 915, "y": 736, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-41, 482, 75, 586],
                "x": 16,
                "y": 582,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 455, "y": 356, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 622, "y": 724, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [447, 352, 572, 449],
                "x": 512,
                "y": 453,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [854, 654, 974, 745],
                "x": 910,
                "y": 750,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-43, 465, 78, 572],
                "x": 14,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [415, 238, 535, 338],
                "x": 475,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [558, 608, 675, 713],
                "x": 620,
                "y": 711,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [480, 344, 594, 451],
                "x": 538,
                "y": 447,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [851, 665, 963, 762],
                "x": 906,
                "y": 762,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 12, "y": 555, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 495, "y": 322, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 617, "y": 694, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [507, 340, 625, 443],
                "x": 564,
                "y": 440,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [837, 675, 964, 774],
                "x": 902,
                "y": 772,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-54, 437, 67, 541],
                "x": 10,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [452, 206, 578, 308],
                "x": 515,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [558, 577, 672, 672],
                "x": 615,
                "y": 674,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 589, "y": 433, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [841, 676, 962, 779],
                "x": 898,
                "y": 780,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-55, 426, 74, 522],
                "x": 9,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [480, 189, 594, 290],
                "x": 536,
                "y": 293,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [553, 550, 677, 647],
                "x": 612,
                "y": 651,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [552, 325, 677, 427],
                "x": 615,
                "y": 425,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [837, 687, 955, 792],
                "x": 893,
                "y": 788,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-57, 418, 64, 517],
                "x": 7,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [493, 180, 621, 278],
                "x": 556,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [546, 529, 665, 625],
                "x": 609,
                "y": 625,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [585, 316, 703, 412],
                "x": 641,
                "y": 417,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [834, 689, 951, 795],
                "x": 889,
                "y": 793,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-58, 404, 63, 502],
                "x": 5,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [511, 163, 633, 267],
                "x": 576,
                "y": 267,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [545, 500, 669, 592],
                "x": 607,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [608, 304, 722, 407],
                "x": 666,
                "y": 409,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [823, 692, 944, 794],
                "x": 885,
                "y": 797,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-58, 388, 66, 486],
                "x": 3,
                "y": 484,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 596, "y": 256, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [548, 462, 669, 567],
                "x": 604,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [634, 297, 754, 397],
                "x": 692,
                "y": 401,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [817, 702, 946, 803],
                "x": 881,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 1, "y": 469, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [556, 145, 673, 247],
                "x": 616,
                "y": 245,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 602, "y": 533, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [659, 295, 777, 390],
                "x": 717,
                "y": 393,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-64, 351, 61, 456],
                "x": 0,
                "y": 454,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 636, "y": 237, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [537, 400, 655, 499],
                "x": 599,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [683, 280, 807, 386],
                "x": 743,
                "y": 385,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 657, "y": 229, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [538, 362, 653, 467],
                "x": 597,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [710, 275, 834, 383],
                "x": 769,
                "y": 378,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [614, 126, 742, 221],
                "x": 677,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [533, 322, 649, 423],
                "x": 594,
                "y": 424,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 794, "y": 370, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [641, 121, 759, 223],
                "x": 697,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [535, 281, 652, 384],
                "x": 592,
                "y": 385,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 820, "y": 363, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [660, 119, 776, 212],
                "x": 717,
                "y": 214,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [528, 243, 652, 341],
                "x": 589,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [782, 251, 902, 354],
                "x": 846,
                "y": 356,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [675, 113, 792, 213],
                "x": 737,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [525, 201, 644, 298],
                "x": 586,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [812, 249, 926, 351],
                "x": 871,
                "y": 350,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [701, 114, 815, 209],
                "x": 757,
                "y": 211,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [523, 160, 649, 257],
                "x": 584,
                "y": 260,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 897, "y": 344, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [720, 111, 835, 216],
                "x": 778,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [525, 116, 641, 219],
                "x": 581,
                "y": 217,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [864, 241, 978, 335],
                "x": 923,
                "y": 339,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [737, 110, 857, 218],
                "x": 798,
                "y": 215,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [521, 72, 637, 174],
                "x": 579,
                "y": 173,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [892, 231, 1010, 331],
                "x": 948,
                "y": 335,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [753, 115, 875, 216],
                "x": 818,
                "y": 219,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [521, 33, 633, 130],
                "x": 576,
                "y": 130,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [914, 235, 1034, 329],
                "x": 974,
                "y": 331,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [783, 130, 901, 228],
                "x": 838,
                "y": 225,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 574, "y": 86, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 328, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [793, 136, 913, 229],
                "x": 858,
                "y": 232,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [512, -53, 633, 45],
                "x": 571,
                "y": 43,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [823, 144, 940, 247],
                "x": 878,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [514, -95, 630, -5],
                "x": 569,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [838, 158, 955, 249],
                "x": 899,
                "y": 253,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [863, 171, 982, 262],
                "x": 919,
                "y": 266,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [881, 183, 1003, 286],
                "x": 939,
                "y": 281,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [901, 202, 1016, 298],
                "x": 959,
                "y": 298,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [922, 213, 1034, 317],
                "x": 979,
                "y": 317,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 339, "track_id": None}
        ],
    },
]
