country_balls_amount = 15
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 0, "y": 711, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 6, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-58, 702, 62, 801],
                "x": 2,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 0, "y": 472, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 556, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 439, "y": 0, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [942, 138, 1058, 239],
                "x": 1000,
                "y": 237,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 1000, "y": 633, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 833, "y": 0, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 761, "y": 799, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 1000, "y": 115, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [-61, 285, 61, 386],
                "x": 0,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-60, 67, 58, 164],
                "x": 0,
                "y": 166,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 1000, "y": 70, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 0, "y": 717, "track_id": None},
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 14, "y": 648, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 979, "y": 52, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-57, 699, 62, 797],
                "x": 1,
                "y": 798,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 2, "y": 487, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [915, 382, 1036, 482],
                "x": 974,
                "y": 483,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 450, "y": 6, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [930, 168, 1049, 272],
                "x": 990,
                "y": 270,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [921, 476, 1040, 574],
                "x": 982,
                "y": 575,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 834, "y": 3, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 736, "y": 723, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 113, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 6, "y": 358, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 4, "y": 209, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [900, 8, 1021, 106],
                "x": 960,
                "y": 108,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 28, "y": 743, "track_id": None},
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 28, "y": 591, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 959, "y": 94, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-57, 697, 62, 795],
                "x": 1,
                "y": 797,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-55, 405, 63, 505],
                "x": 4,
                "y": 503,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 948, "y": 421, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [400, -85, 521, 14],
                "x": 461,
                "y": 15,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [922, 199, 1043, 301],
                "x": 981,
                "y": 301,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 964, "y": 524, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 835, "y": 7, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 711, "y": 653, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 110, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 13, "y": 332, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [-53, 153, 67, 251],
                "x": 9,
                "y": 252,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 920, "y": 144, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 57, "y": 758, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 43, "y": 540, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 938, "y": 133, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 796, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 7, "y": 518, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 923, "y": 368, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 473, "y": 27, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 972, "y": 331, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [885, 381, 1008, 482],
                "x": 946,
                "y": 480,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 837, "y": 11, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 687, "y": 588, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 108, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 20, "y": 308, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [-49, 193, 73, 294],
                "x": 13,
                "y": 293,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 880, "y": 179, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 86, "y": 762, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 57, "y": 494, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 918, "y": 167, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 795, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 9, "y": 532, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 897, "y": 324, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 484, "y": 41, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 963, "y": 361, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 928, "y": 443, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 838, "y": 16, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 662, "y": 529, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 105, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 27, "y": 284, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 18, "y": 334, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 840, "y": 212, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 115, "y": 756, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 71, "y": 453, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 897, "y": 198, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 794, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 12, "y": 547, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 871, "y": 287, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 496, "y": 57, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 954, "y": 390, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 910, "y": 412, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 840, "y": 22, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 638, "y": 476, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 103, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 34, "y": 262, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 22, "y": 373, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 800, "y": 243, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [82, 643, 203, 743],
                "x": 144,
                "y": 742,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 86, "y": 417, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 877, "y": 226, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 793, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-45, 462, 72, 559],
                "x": 14,
                "y": 561,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 846, "y": 259, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 507, "y": 74, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [886, 315, 1004, 419],
                "x": 945,
                "y": 417,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 893, "y": 387, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 841, "y": 29, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 613, "y": 428, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 100, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 40, "y": 240, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 27, "y": 410, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [702, 171, 822, 271],
                "x": 760,
                "y": 271,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 173, "y": 722, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 100, "y": 386, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 857, "y": 250, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 792, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 17, "y": 574, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 820, "y": 237, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 519, "y": 94, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 936, "y": 445, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 875, "y": 367, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 843, "y": 36, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 589, "y": 385, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 98, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 47, "y": 220, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [-30, 345, 93, 445],
                "x": 32,
                "y": 447,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 720, "y": 297, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [143, 598, 261, 695],
                "x": 202,
                "y": 696,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 114, "y": 358, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 836, "y": 271, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 791, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 19, "y": 587, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 794, "y": 223, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [469, 13, 590, 115],
                "x": 530,
                "y": 115,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 927, "y": 471, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 857, "y": 353, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 844, "y": 44, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [503, 247, 626, 347],
                "x": 564,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [940, -3, 1061, 94],
                "x": 999,
                "y": 95,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-4, 103, 113, 202],
                "x": 54,
                "y": 201,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 36, "y": 482, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 680, "y": 321, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 231, "y": 667, "track_id": None},
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 129, "y": 335, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [757, 190, 877, 288],
                "x": 816,
                "y": 289,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 790, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 21, "y": 600, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 769, "y": 214, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 542, "y": 137, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [860, 396, 980, 494],
                "x": 918,
                "y": 496,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 839, "y": 343, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 846, "y": 53, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 540, "y": 314, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 93, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 61, "y": 182, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 41, "y": 517, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 640, "y": 342, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [198, 537, 318, 637],
                "x": 260,
                "y": 635,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 143, "y": 315, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 795, "y": 304, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 789, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 24, "y": 613, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [682, 111, 802, 212],
                "x": 743,
                "y": 210,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 553, "y": 161, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 909, "y": 521, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [762, 236, 881, 336],
                "x": 821,
                "y": 338,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 847, "y": 62, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 515, "y": 287, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 90, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 68, "y": 165, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 45, "y": 550, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 600, "y": 360, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 289, "y": 602, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 158, "y": 299, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 775, "y": 317, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-58, 688, 62, 789],
                "x": 1,
                "y": 788,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 26, "y": 625, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 717, "y": 212, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 564, "y": 185, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 900, "y": 545, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 803, "y": 336, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [788, -27, 909, 74],
                "x": 849,
                "y": 72,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 490, "y": 263, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 87, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 75, "y": 148, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 50, "y": 582, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 560, "y": 375, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 318, "y": 569, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 172, "y": 287, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [697, 226, 817, 326],
                "x": 755,
                "y": 328,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 787, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 29, "y": 636, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 692, "y": 218, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 576, "y": 211, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [833, 470, 950, 569],
                "x": 891,
                "y": 568,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 786, "y": 339, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 850, "y": 83, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 466, "y": 245, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [941, -16, 1061, 83],
                "x": 999,
                "y": 85,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 81, "y": 133, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 54, "y": 613, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [458, 288, 582, 385],
                "x": 520,
                "y": 386,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 347, "y": 538, "track_id": None},
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 186, "y": 277, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 734, "y": 336, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 786, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 31, "y": 648, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [604, 126, 727, 228],
                "x": 666,
                "y": 228,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 587, "y": 237, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [820, 490, 942, 590],
                "x": 882,
                "y": 590,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 768, "y": 344, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 852, "y": 95, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 441, "y": 231, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 82, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 88, "y": 118, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 59, "y": 643, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 480, "y": 395, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 375, "y": 510, "track_id": None},
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 201, "y": 270, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 714, "y": 342, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 785, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 34, "y": 659, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 641, "y": 241, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 599, "y": 264, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 872, "y": 611, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 750, "y": 353, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [794, 7, 912, 105],
                "x": 853,
                "y": 107,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 417, "y": 221, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 80, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 95, "y": 105, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 64, "y": 671, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 440, "y": 399, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 404, "y": 486, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [155, 167, 274, 266],
                "x": 215,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [631, 245, 751, 347],
                "x": 693,
                "y": 347,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 784, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 36, "y": 669, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 615, "y": 257, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 610, "y": 291, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 863, "y": 632, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 732, "y": 364, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 854, "y": 120, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 392, "y": 216, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 77, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 102, "y": 92, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 68, "y": 699, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 400, "y": 401, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 433, "y": 468, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 229, "y": 263, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 673, "y": 349, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 783, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 39, "y": 680, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 589, "y": 276, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 622, "y": 319, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 854, "y": 651, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [655, 276, 772, 378],
                "x": 714,
                "y": 377,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 856, "y": 133, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 368, "y": 215, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [937, -24, 1058, 76],
                "x": 999,
                "y": 75,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 109, "y": 80, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 73, "y": 726, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 360, "y": 398, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 462, "y": 457, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [183, 162, 306, 265],
                "x": 244,
                "y": 263,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 653, "y": 351, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1, "y": 782, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-17, 588, 99, 689],
                "x": 41,
                "y": 690,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 564, "y": 296, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 633, "y": 346, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 845, "y": 670, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 697, "y": 392, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 857, "y": 148, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 343, "y": 218, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 72, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 115, "y": 69, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 77, "y": 751, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [262, 292, 380, 390],
                "x": 320,
                "y": 391,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 491, "y": 455, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 258, "y": 265, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 632, "y": 350, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-62, 682, 59, 782],
                "x": 0,
                "y": 781,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 43, "y": 699, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 538, "y": 317, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [587, 275, 705, 374],
                "x": 645,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [777, 587, 894, 687],
                "x": 836,
                "y": 688,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 679, "y": 409, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 859, "y": 163, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 319, "y": 224, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [940, -29, 1061, 68],
                "x": 999,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [60, -43, 184, 59],
                "x": 122,
                "y": 59,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 82, "y": 776, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 280, "y": 381, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 520, "y": 463, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 273, "y": 268, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 612, "y": 349, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 780, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-14, 606, 108, 707],
                "x": 46,
                "y": 708,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 512, "y": 339, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 656, "y": 401, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 827, "y": 705, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 661, "y": 426, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 860, "y": 179, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 294, "y": 234, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 67, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 129, "y": 50, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 87, "y": 800, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 240, "y": 366, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 549, "y": 483, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 287, "y": 272, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 591, "y": 347, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 779, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 48, "y": 717, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [429, 261, 549, 362],
                "x": 487,
                "y": 361,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 667, "y": 428, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 818, "y": 721, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 643, "y": 444, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 862, "y": 196, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [210, 146, 329, 250],
                "x": 270,
                "y": 248,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 65, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 136, "y": 41, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 200, "y": 346, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 578, "y": 515, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [243, 175, 359, 277],
                "x": 301,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [512, 245, 632, 343],
                "x": 571,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-62, 677, 62, 776],
                "x": 0,
                "y": 778,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 51, "y": 726, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 461, "y": 382, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 679, "y": 455, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 809, "y": 736, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 625, "y": 462, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 863, "y": 213, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 245, "y": 266, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [939, -38, 1057, 64],
                "x": 999,
                "y": 62,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 143, "y": 33, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 160, "y": 322, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [547, 459, 667, 559],
                "x": 607,
                "y": 561,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 316, "y": 283, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 551, "y": 340, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 777, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 53, "y": 734, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [373, 301, 493, 401],
                "x": 435,
                "y": 403,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 690, "y": 480, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 800, "y": 751, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 607, "y": 480, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 865, "y": 231, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 220, "y": 286, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 60, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 150, "y": 26, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 120, "y": 293, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 636, "y": 623, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 330, "y": 290, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 530, "y": 336, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 776, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-6, 642, 114, 740],
                "x": 56,
                "y": 742,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 410, "y": 422, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 702, "y": 505, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 791, "y": 764, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [530, 398, 652, 499],
                "x": 590,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [804, 150, 926, 249],
                "x": 866,
                "y": 250,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 196, "y": 310, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 999, "y": 57, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 156, "y": 20, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 80, "y": 259, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 665, "y": 702, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [286, 197, 402, 299],
                "x": 344,
                "y": 297,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 510, "y": 332, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-58, 676, 59, 776],
                "x": 0,
                "y": 775,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 58, "y": 750, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [324, 339, 442, 440],
                "x": 384,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [652, 429, 775, 529],
                "x": 713,
                "y": 529,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 782, "y": 777, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 572, "y": 515, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 868, "y": 270, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 171, "y": 337, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 55, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 163, "y": 15, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 40, "y": 220, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [634, 701, 756, 799],
                "x": 694,
                "y": 800,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 359, "y": 303, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [430, 227, 550, 329],
                "x": 489,
                "y": 328,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 774, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 60, "y": 757, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 358, "y": 454, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [663, 450, 786, 551],
                "x": 725,
                "y": 551,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 773, "y": 789, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 554, "y": 530, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 869, "y": 291, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 147, "y": 367, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [939, -50, 1057, 52],
                "x": 998,
                "y": 52,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 170, "y": 10, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 0, "y": 176, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 373, "y": 310, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 469, "y": 323, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 773, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [2, 666, 123, 764],
                "x": 63,
                "y": 764,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [272, 365, 395, 466],
                "x": 333,
                "y": 465,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 736, "y": 572, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 764, "y": 799, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [474, 443, 597, 544],
                "x": 536,
                "y": 544,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 871, "y": 312, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [61, 298, 182, 399],
                "x": 122,
                "y": 400,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 50, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [116, -94, 235, 6],
                "x": 177,
                "y": 6,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 387, "y": 316, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 448, "y": 319, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-59, 672, 59, 770],
                "x": 0,
                "y": 772,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [7, 669, 126, 772],
                "x": 65,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [248, 372, 367, 474],
                "x": 307,
                "y": 473,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 748, "y": 592, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 518, "y": 556, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [810, 233, 932, 336],
                "x": 872,
                "y": 334,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 98, "y": 436, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [937, -53, 1058, 46],
                "x": 998,
                "y": 47,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [125, -96, 242, 1],
                "x": 184,
                "y": 2,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 402, "y": 321, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 428, "y": 316, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 771, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 68, "y": 777, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [223, 378, 343, 474],
                "x": 282,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [699, 512, 821, 611],
                "x": 759,
                "y": 610,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 500, "y": 566, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 874, "y": 357, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 73, "y": 474, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 44, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 191, "y": 0, "track_id": None},
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [355, 223, 476, 325],
                "x": 416,
                "y": 325,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 408, "y": 313, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 770, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [10, 681, 131, 785],
                "x": 70,
                "y": 783,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [197, 377, 316, 477],
                "x": 256,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [713, 527, 831, 625],
                "x": 771,
                "y": 626,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 483, "y": 572, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 875, "y": 381, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 49, "y": 514, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 42, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 431, "y": 328, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 387, "y": 311, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-62, 667, 61, 770],
                "x": 0,
                "y": 769,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 73, "y": 789, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 230, "y": 469, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 782, "y": 640, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 465, "y": 576, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [817, 303, 938, 403],
                "x": 876,
                "y": 405,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 24, "y": 557, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [936, -60, 1057, 41],
                "x": 998,
                "y": 39,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 445, "y": 330, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 367, "y": 310, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-62, 667, 60, 769],
                "x": 0,
                "y": 768,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 75, "y": 794, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 205, "y": 456, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 793, "y": 652, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 447, "y": 576, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 878, "y": 430, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 0, "y": 603, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 37, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [401, 229, 521, 330],
                "x": 459,
                "y": 330,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 346, "y": 310, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 767, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 78, "y": 800, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 179, "y": 438, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [747, 561, 863, 660],
                "x": 805,
                "y": 661,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [369, 471, 488, 574],
                "x": 429,
                "y": 572,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 879, "y": 457, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 34, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 474, "y": 327, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 326, "y": 312, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-61, 668, 58, 764],
                "x": 0,
                "y": 766,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [95, 311, 212, 411],
                "x": 153,
                "y": 412,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [758, 566, 874, 670],
                "x": 816,
                "y": 668,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 411, "y": 565, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 881, "y": 483, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 32, "track_id": None},
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 488, "y": 323, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [244, 217, 367, 316],
                "x": 306,
                "y": 315,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 765, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [66, 277, 187, 380],
                "x": 128,
                "y": 379,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 828, "y": 673, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [336, 450, 452, 554],
                "x": 394,
                "y": 552,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 882, "y": 511, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 29, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 502, "y": 316, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [224, 221, 344, 321],
                "x": 285,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-60, 665, 60, 764],
                "x": 0,
                "y": 764,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [42, 236, 161, 336],
                "x": 102,
                "y": 338,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 839, "y": 674, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 376, "y": 534, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 884, "y": 540, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 27, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 517, "y": 306, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [203, 228, 327, 327],
                "x": 265,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [17, 188, 135, 287],
                "x": 76,
                "y": 289,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 851, "y": 673, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 358, "y": 511, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [823, 468, 945, 570],
                "x": 885,
                "y": 569,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 24, "track_id": None},
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 531, "y": 293, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 244, "y": 335, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 51, "y": 231, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 862, "y": 668, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 340, "y": 482, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 887, "y": 600, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 22, "track_id": None},
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 546, "y": 277, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 224, "y": 346, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 25, "y": 163, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 874, "y": 660, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 322, "y": 447, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 888, "y": 631, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 19, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 560, "y": 257, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [144, 258, 264, 360],
                "x": 204,
                "y": 359,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 0, "y": 85, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 885, "y": 649, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 304, "y": 406, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 890, "y": 663, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [938, -84, 1056, 15],
                "x": 998,
                "y": 17,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 574, "y": 234, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 183, "y": 375, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [838, 534, 956, 636],
                "x": 896,
                "y": 634,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 287, "y": 358, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [833, 595, 951, 694],
                "x": 891,
                "y": 696,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [938, -85, 1060, 13],
                "x": 998,
                "y": 14,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 589, "y": 206, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 163, "y": 394, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 908, "y": 615, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 269, "y": 302, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 893, "y": 729, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 12, "track_id": None},
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 603, "y": 174, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 142, "y": 415, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 919, "y": 592, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [192, 140, 313, 237],
                "x": 251,
                "y": 239,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [834, 664, 954, 762],
                "x": 894,
                "y": 764,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [938, -90, 1057, 10],
                "x": 998,
                "y": 9,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 617, "y": 138, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [62, 341, 181, 441],
                "x": 122,
                "y": 440,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 931, "y": 566, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 233, "y": 168, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [837, 699, 957, 801],
                "x": 896,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 7, "track_id": None},
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [573, -4, 694, 96],
                "x": 632,
                "y": 97,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 102, "y": 468, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 942, "y": 534, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 215, "y": 88, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 4, "track_id": None},
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 646, "y": 51, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 81, "y": 500, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 954, "y": 499, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 198, "y": 0, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 2, "track_id": None},
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 661, "y": 0, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [2, 436, 121, 536],
                "x": 61,
                "y": 535,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 965, "y": 458, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 998, "y": 0, "track_id": None},
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 40, "y": 574, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 977, "y": 413, "track_id": None},
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-38, 516, 80, 618],
                "x": 20,
                "y": 617,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [927, 264, 1047, 363],
                "x": 988,
                "y": 364,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 0, "y": 665, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 1000, "y": 309, "track_id": None},
        ],
    },
]
