country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-60, 179, 62, 279],
                "x": 0,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [253, -104, 373, 1],
                "x": 313,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [938, 219, 1058, 318],
                "x": 1000,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-64, -31, 57, 61],
                "x": 0,
                "y": 66,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [944, 693, 1060, 797],
                "x": 1000,
                "y": 795,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 21, "y": 292, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [247, -95, 372, -1],
                "x": 308,
                "y": 3,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [916, 206, 1041, 306],
                "x": 976,
                "y": 301,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-53, 24, 73, 120],
                "x": 12,
                "y": 120,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [908, 635, 1023, 737],
                "x": 967,
                "y": 732,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-13, 203, 102, 297],
                "x": 42,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [243, -95, 358, 11],
                "x": 303,
                "y": 7,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [889, 194, 1014, 286],
                "x": 953,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-35, 74, 80, 172],
                "x": 24,
                "y": 173,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [870, 578, 999, 681],
                "x": 935,
                "y": 676,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [5, 214, 123, 312],
                "x": 63,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [240, -84, 362, 18],
                "x": 298,
                "y": 13,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [865, 185, 989, 282],
                "x": 930,
                "y": 280,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-27, 128, 99, 228],
                "x": 36,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [845, 521, 961, 625],
                "x": 903,
                "y": 626,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [24, 227, 142, 325],
                "x": 85,
                "y": 324,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 293, "y": 20, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [851, 172, 966, 267],
                "x": 906,
                "y": 270,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-10, 167, 108, 270],
                "x": 48,
                "y": 271,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [805, 478, 932, 584],
                "x": 870,
                "y": 581,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [45, 234, 161, 336],
                "x": 106,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [226, -70, 344, 26],
                "x": 288,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [821, 162, 941, 262],
                "x": 883,
                "y": 261,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 60, "y": 316, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [775, 438, 896, 547],
                "x": 838,
                "y": 543,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [69, 243, 184, 346],
                "x": 127,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [227, -64, 340, 34],
                "x": 283,
                "y": 37,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [801, 150, 925, 249],
                "x": 860,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [14, 262, 129, 355],
                "x": 72,
                "y": 359,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 806, "y": 509, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [92, 260, 206, 359],
                "x": 148,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [214, -49, 339, 52],
                "x": 278,
                "y": 48,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [776, 151, 898, 246],
                "x": 837,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [23, 297, 149, 395],
                "x": 84,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [711, 379, 831, 476],
                "x": 774,
                "y": 481,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [112, 274, 227, 370],
                "x": 170,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [215, -38, 332, 62],
                "x": 273,
                "y": 60,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [754, 143, 870, 241],
                "x": 813,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [35, 335, 156, 441],
                "x": 96,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [684, 355, 800, 459],
                "x": 741,
                "y": 457,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [132, 291, 250, 384],
                "x": 191,
                "y": 386,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [208, -22, 325, 75],
                "x": 268,
                "y": 73,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [725, 138, 853, 235],
                "x": 790,
                "y": 234,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 108, "y": 476, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [646, 335, 773, 438],
                "x": 709,
                "y": 439,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 212, "y": 398, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [198, -11, 320, 83],
                "x": 263,
                "y": 88,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [706, 129, 822, 224],
                "x": 767,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [55, 409, 180, 511],
                "x": 120,
                "y": 510,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [613, 319, 738, 426],
                "x": 677,
                "y": 424,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [176, 307, 299, 409],
                "x": 234,
                "y": 411,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [195, 9, 318, 101],
                "x": 258,
                "y": 104,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [688, 126, 804, 220],
                "x": 744,
                "y": 225,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [72, 442, 189, 548],
                "x": 132,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [585, 309, 710, 416],
                "x": 645,
                "y": 414,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [195, 328, 316, 424],
                "x": 255,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [196, 23, 317, 126],
                "x": 253,
                "y": 122,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 720, "y": 221, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [84, 472, 202, 568],
                "x": 144,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [556, 307, 673, 404],
                "x": 612,
                "y": 408,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [221, 340, 331, 440],
                "x": 276,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [187, 39, 309, 137],
                "x": 248,
                "y": 141,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [639, 113, 756, 213],
                "x": 697,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [94, 505, 221, 605],
                "x": 156,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [523, 307, 644, 409],
                "x": 580,
                "y": 406,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [236, 351, 359, 453],
                "x": 297,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [187, 65, 302, 165],
                "x": 243,
                "y": 162,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [614, 115, 735, 213],
                "x": 674,
                "y": 215,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [106, 526, 223, 625],
                "x": 168,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [493, 308, 604, 407],
                "x": 548,
                "y": 407,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 319, "y": 461, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [173, 81, 298, 180],
                "x": 238,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [596, 110, 715, 217],
                "x": 651,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [121, 555, 239, 651],
                "x": 180,
                "y": 652,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [457, 311, 579, 406],
                "x": 516,
                "y": 411,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [284, 371, 405, 470],
                "x": 340,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [170, 111, 294, 205],
                "x": 234,
                "y": 209,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 627, "y": 212, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [128, 574, 255, 673],
                "x": 192,
                "y": 674,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [418, 316, 545, 417],
                "x": 483,
                "y": 418,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [304, 389, 423, 487],
                "x": 361,
                "y": 485,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 229, "y": 235, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [545, 111, 664, 216],
                "x": 604,
                "y": 211,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [143, 590, 269, 689],
                "x": 204,
                "y": 694,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [388, 333, 511, 431],
                "x": 451,
                "y": 428,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [317, 400, 439, 497],
                "x": 382,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [159, 163, 279, 259],
                "x": 224,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [523, 111, 637, 208],
                "x": 581,
                "y": 211,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [155, 618, 278, 714],
                "x": 216,
                "y": 713,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [355, 343, 480, 436],
                "x": 419,
                "y": 441,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [341, 407, 466, 501],
                "x": 404,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [158, 197, 277, 287],
                "x": 219,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [494, 107, 619, 212],
                "x": 558,
                "y": 211,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [169, 632, 287, 729],
                "x": 228,
                "y": 730,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [328, 352, 452, 451],
                "x": 387,
                "y": 455,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [367, 420, 487, 522],
                "x": 425,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [155, 223, 274, 323],
                "x": 214,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [478, 109, 598, 212],
                "x": 534,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [181, 646, 295, 747],
                "x": 240,
                "y": 744,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [295, 372, 418, 474],
                "x": 354,
                "y": 472,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [385, 424, 510, 526],
                "x": 446,
                "y": 526,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [148, 258, 274, 359],
                "x": 209,
                "y": 357,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [456, 113, 571, 211],
                "x": 511,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [195, 659, 317, 754],
                "x": 252,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [265, 390, 387, 494],
                "x": 322,
                "y": 491,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [403, 438, 532, 531],
                "x": 468,
                "y": 535,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 204, "y": 392, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [430, 113, 552, 209],
                "x": 488,
                "y": 214,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [203, 674, 327, 769],
                "x": 264,
                "y": 769,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [230, 417, 355, 510],
                "x": 290,
                "y": 512,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [430, 445, 548, 544],
                "x": 489,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [139, 325, 260, 427],
                "x": 199,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [408, 120, 529, 215],
                "x": 465,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [213, 679, 338, 773],
                "x": 276,
                "y": 778,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [193, 431, 320, 535],
                "x": 258,
                "y": 533,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [448, 451, 569, 552],
                "x": 510,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [138, 365, 250, 469],
                "x": 194,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [384, 119, 505, 219],
                "x": 441,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [227, 689, 351, 791],
                "x": 288,
                "y": 786,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [166, 452, 286, 559],
                "x": 225,
                "y": 556,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [467, 459, 594, 554],
                "x": 531,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [129, 412, 251, 506],
                "x": 189,
                "y": 509,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [356, 116, 475, 218],
                "x": 418,
                "y": 221,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [239, 696, 364, 795],
                "x": 300,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [128, 483, 253, 585],
                "x": 193,
                "y": 580,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 553, "y": 563, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [129, 457, 248, 547],
                "x": 184,
                "y": 552,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [334, 127, 457, 220],
                "x": 395,
                "y": 224,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [251, 698, 367, 801],
                "x": 312,
                "y": 797,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [102, 506, 216, 600],
                "x": 161,
                "y": 604,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [510, 470, 639, 571],
                "x": 574,
                "y": 567,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [116, 501, 240, 592],
                "x": 179,
                "y": 597,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 372, "y": 227, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [259, 700, 389, 804],
                "x": 324,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [66, 525, 193, 624],
                "x": 129,
                "y": 629,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 595, "y": 571, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [114, 549, 229, 641],
                "x": 174,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [287, 135, 411, 226],
                "x": 348,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [32, 556, 157, 656],
                "x": 96,
                "y": 654,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [561, 472, 678, 576],
                "x": 617,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [109, 594, 230, 698],
                "x": 169,
                "y": 694,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 325, "y": 235, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [7, 577, 123, 674],
                "x": 64,
                "y": 679,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [573, 479, 700, 574],
                "x": 638,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [108, 647, 226, 750],
                "x": 164,
                "y": 746,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [240, 139, 364, 238],
                "x": 302,
                "y": 239,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-30, 608, 91, 702],
                "x": 32,
                "y": 704,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [602, 473, 719, 573],
                "x": 659,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [96, 702, 223, 803],
                "x": 160,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 279, "y": 243, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 0, "y": 729, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [625, 470, 738, 571],
                "x": 680,
                "y": 574,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [195, 149, 315, 245],
                "x": 255,
                "y": 248,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 702, "y": 571, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [177, 157, 287, 252],
                "x": 232,
                "y": 252,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [659, 469, 782, 568],
                "x": 723,
                "y": 567,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 209, "y": 257, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [688, 467, 799, 559],
                "x": 744,
                "y": 562,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 186, "y": 262, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [708, 456, 821, 551],
                "x": 765,
                "y": 555,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [103, 166, 227, 266],
                "x": 162,
                "y": 267,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [732, 444, 849, 545],
                "x": 787,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [77, 171, 199, 276],
                "x": 139,
                "y": 272,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [753, 431, 872, 539],
                "x": 808,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [59, 181, 171, 281],
                "x": 116,
                "y": 277,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [766, 429, 893, 528],
                "x": 829,
                "y": 524,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [30, 178, 157, 280],
                "x": 93,
                "y": 283,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [790, 412, 913, 515],
                "x": 851,
                "y": 510,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [10, 193, 129, 283],
                "x": 69,
                "y": 288,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [817, 399, 930, 495],
                "x": 872,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-17, 198, 101, 294],
                "x": 46,
                "y": 293,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [830, 372, 955, 481],
                "x": 893,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-40, 203, 85, 299],
                "x": 23,
                "y": 298,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [853, 360, 972, 461],
                "x": 914,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-59, 202, 60, 302],
                "x": 0,
                "y": 304,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [881, 338, 995, 431],
                "x": 936,
                "y": 436,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [892, 309, 1017, 411],
                "x": 957,
                "y": 412,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [920, 286, 1034, 384],
                "x": 978,
                "y": 387,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [937, 264, 1062, 362],
                "x": 1000,
                "y": 359,
                "track_id": None,
            }
        ],
    },
]
