country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [429, 706, 535, 791],
                "x": 482,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 112, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 321, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-51, 372, 65, 473],
                "x": 0,
                "y": 477,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 918, "y": 0, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 0, "y": 459, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [80, 690, 206, 796],
                "x": 146,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 1000, "y": 338, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 1000, "y": 22, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 195, "y": 0, "track_id": None},
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [431, 659, 534, 767],
                "x": 483,
                "y": 759,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 977, "y": 128, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 997, "y": 303, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 32, "y": 461, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 920, "y": 1, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 13, "y": 475, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [80, 701, 197, 788],
                "x": 140,
                "y": 794,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 997, "y": 323, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [923, -51, 1034, 47],
                "x": 976,
                "y": 42,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 199, "y": 46, "track_id": None},
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 484, "y": 719, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 954, "y": 145, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 995, "y": 286, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 64, "y": 446, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 922, "y": 2, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 26, "y": 489, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 135, "y": 788, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 995, "y": 309, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [890, -41, 1018, 68],
                "x": 953,
                "y": 63,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 203, "y": 91, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 486, "y": 680, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 932, "y": 161, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [931, 160, 1061, 271],
                "x": 993,
                "y": 270,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 96, "y": 434, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 924, "y": 3, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 40, "y": 498, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [63, 674, 194, 777],
                "x": 130,
                "y": 781,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 993, "y": 295, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 930, "y": 83, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [149, 28, 268, 131],
                "x": 207,
                "y": 134,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 487, "y": 642, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [859, 70, 961, 167],
                "x": 909,
                "y": 177,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 990, "y": 254, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [62, 328, 192, 427],
                "x": 129,
                "y": 422,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 926, "y": 5, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 53, "y": 504, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [72, 674, 187, 766],
                "x": 125,
                "y": 774,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 991, "y": 281, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 906, "y": 102, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [156, 83, 275, 168],
                "x": 211,
                "y": 175,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 489, "y": 605, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [833, 96, 948, 201],
                "x": 886,
                "y": 192,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 988, "y": 239, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 161, "y": 412, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [867, -98, 994, 5],
                "x": 928,
                "y": 6,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 66, "y": 507, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [68, 674, 182, 758],
                "x": 120,
                "y": 768,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 989, "y": 268, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [828, 29, 950, 127],
                "x": 883,
                "y": 121,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 215, "y": 215, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 490, "y": 569, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 864, "y": 206, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 986, "y": 224, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 193, "y": 403, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 930, "y": 8, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 80, "y": 507, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 115, "y": 760, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 987, "y": 255, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 860, "y": 139, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [162, 156, 279, 244],
                "x": 220,
                "y": 254,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 492, "y": 535, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 841, "y": 220, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 983, "y": 209, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 225, "y": 396, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 933, "y": 10, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 93, "y": 503, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 110, "y": 753, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 985, "y": 242, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 837, "y": 157, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [162, 186, 290, 289],
                "x": 224,
                "y": 291,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 493, "y": 500, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 819, "y": 233, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 981, "y": 195, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 258, "y": 389, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [882, -87, 1004, 13],
                "x": 935,
                "y": 11,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 106, "y": 498, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 105, "y": 745, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [930, 123, 1034, 220],
                "x": 983,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [754, 68, 878, 184],
                "x": 813,
                "y": 174,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [170, 218, 283, 332],
                "x": 228,
                "y": 326,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 494, "y": 467, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [731, 146, 852, 248],
                "x": 796,
                "y": 246,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 979, "y": 182, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [224, 288, 356, 381],
                "x": 290,
                "y": 383,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 937, "y": 13, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 120, "y": 489, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 100, "y": 737, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [921, 114, 1039, 225],
                "x": 981,
                "y": 217,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [722, 98, 843, 195],
                "x": 790,
                "y": 190,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [178, 253, 294, 354],
                "x": 232,
                "y": 360,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 496, "y": 435, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [708, 161, 840, 265],
                "x": 773,
                "y": 257,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 977, "y": 169, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [271, 269, 390, 378],
                "x": 322,
                "y": 379,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 939, "y": 15, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 133, "y": 478, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 95, "y": 729, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 979, "y": 205, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [697, 105, 821, 199],
                "x": 767,
                "y": 206,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 236, "y": 393, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 497, "y": 404, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [693, 163, 813, 259],
                "x": 751,
                "y": 268,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 974, "y": 156, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [291, 278, 424, 382],
                "x": 354,
                "y": 375,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 941, "y": 16, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 146, "y": 465, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 90, "y": 720, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [911, 98, 1031, 196],
                "x": 977,
                "y": 193,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 744, "y": 221, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 241, "y": 424, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 499, "y": 373, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 728, "y": 277, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [908, 46, 1034, 144],
                "x": 972,
                "y": 144,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 387, "y": 371, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 943, "y": 18, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 160, "y": 451, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [26, 610, 139, 701],
                "x": 85,
                "y": 711,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [906, 84, 1039, 180],
                "x": 975,
                "y": 182,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [670, 126, 772, 241],
                "x": 720,
                "y": 235,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 245, "y": 453, "track_id": None},
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [445, 250, 565, 347],
                "x": 500,
                "y": 344,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 706, "y": 285, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 970, "y": 132, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 419, "y": 369, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [891, -72, 1010, 14],
                "x": 946,
                "y": 20,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 173, "y": 434, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 80, "y": 702, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 973, "y": 171, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 697, "y": 248, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [185, 390, 316, 472],
                "x": 249,
                "y": 482,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 502, "y": 315, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 683, "y": 292, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [897, 28, 1022, 131],
                "x": 967,
                "y": 121,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 451, "y": 366, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 948, "y": 22, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 186, "y": 416, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 75, "y": 693, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 971, "y": 160, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 674, "y": 260, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 253, "y": 508, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [451, 193, 571, 285],
                "x": 503,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [598, 200, 721, 299],
                "x": 660,
                "y": 298,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 965, "y": 110, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 483, "y": 365, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [886, -75, 1007, 28],
                "x": 950,
                "y": 24,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [130, 303, 256, 404],
                "x": 200,
                "y": 396,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 70, "y": 683, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [905, 45, 1021, 151],
                "x": 969,
                "y": 149,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 651, "y": 271, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 257, "y": 534, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [442, 158, 572, 268],
                "x": 504,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [574, 202, 703, 311],
                "x": 638,
                "y": 303,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 963, "y": 100, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 516, "y": 363, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 952, "y": 26, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 213, "y": 376, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 65, "y": 673, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 967, "y": 139, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 627, "y": 281, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 262, "y": 558, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 506, "y": 234, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [547, 199, 668, 311],
                "x": 615,
                "y": 306,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 960, "y": 90, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 548, "y": 362, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 954, "y": 28, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 226, "y": 354, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 60, "y": 662, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [913, 21, 1022, 124],
                "x": 964,
                "y": 129,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 604, "y": 290, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 266, "y": 581, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 507, "y": 209, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 593, "y": 307, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 958, "y": 81, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 580, "y": 361, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 956, "y": 30, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 240, "y": 331, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 55, "y": 652, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [907, 12, 1019, 109],
                "x": 962,
                "y": 119,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 581, "y": 298, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [210, 494, 326, 613],
                "x": 270,
                "y": 603,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 509, "y": 184, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 570, "y": 307, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 956, "y": 72, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 612, "y": 360, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [909, -77, 1011, 28],
                "x": 959,
                "y": 32,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [184, 207, 319, 310],
                "x": 253,
                "y": 308,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 50, "y": 641, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 960, "y": 109, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 558, "y": 305, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [217, 528, 328, 614],
                "x": 274,
                "y": 623,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 510, "y": 161, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 547, "y": 306, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [895, -36, 1012, 73],
                "x": 954,
                "y": 63,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 645, "y": 359, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 961, "y": 35, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 266, "y": 285, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 45, "y": 629, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 958, "y": 100, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 534, "y": 311, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 278, "y": 642, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 512, "y": 138, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [462, 212, 575, 310],
                "x": 525,
                "y": 303,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 951, "y": 55, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 677, "y": 358, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 963, "y": 37, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 280, "y": 261, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 40, "y": 618, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [905, -17, 1022, 88],
                "x": 956,
                "y": 91,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 511, "y": 316, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 283, "y": 660, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [460, 17, 580, 124],
                "x": 513,
                "y": 116,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 502, "y": 298, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [894, -49, 999, 52],
                "x": 949,
                "y": 47,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 709, "y": 356, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 965, "y": 39, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [237, 130, 350, 243],
                "x": 293,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-16, 510, 101, 605],
                "x": 35,
                "y": 606,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 954, "y": 82, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 488, "y": 319, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 287, "y": 677, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 514, "y": 94, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 479, "y": 291, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 947, "y": 40, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 741, "y": 354, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [902, -64, 1022, 51],
                "x": 967,
                "y": 42,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 306, "y": 213, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-26, 495, 94, 593],
                "x": 30,
                "y": 594,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 952, "y": 73, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 465, "y": 321, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 291, "y": 693, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [464, -30, 583, 78],
                "x": 516,
                "y": 74,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 457, "y": 282, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [878, -76, 1010, 24],
                "x": 944,
                "y": 33,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 774, "y": 352, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [899, -57, 1038, 50],
                "x": 969,
                "y": 44,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 320, "y": 189, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 25, "y": 581, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 950, "y": 65, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 441, "y": 322, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 295, "y": 707, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 517, "y": 54, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [369, 167, 502, 263],
                "x": 434,
                "y": 271,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [891, -84, 1000, 33],
                "x": 942,
                "y": 26,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 806, "y": 350, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 971, "y": 47, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 333, "y": 166, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-48, 464, 72, 576],
                "x": 20,
                "y": 568,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 948, "y": 56, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 418, "y": 321, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 299, "y": 721, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [457, -73, 586, 45],
                "x": 519,
                "y": 35,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [352, 168, 474, 263],
                "x": 412,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [871, -71, 998, 14],
                "x": 940,
                "y": 20,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [774, 240, 896, 339],
                "x": 838,
                "y": 347,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 974, "y": 49, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 346, "y": 144, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-55, 452, 83, 551],
                "x": 15,
                "y": 555,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [887, -55, 996, 56],
                "x": 946,
                "y": 48,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 395, "y": 320, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [249, 640, 361, 732],
                "x": 304,
                "y": 733,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 520, "y": 17, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [333, 151, 444, 242],
                "x": 389,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [885, -85, 1004, 24],
                "x": 937,
                "y": 14,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 870, "y": 343, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 976, "y": 52, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 360, "y": 122, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-41, 448, 80, 542],
                "x": 10,
                "y": 542,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 944, "y": 41, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [307, 217, 432, 313],
                "x": 372,
                "y": 316,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 308, "y": 744, "track_id": None},
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 522, "y": 0, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 366, "y": 226, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 935, "y": 9, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [844, 246, 971, 333],
                "x": 903,
                "y": 338,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [911, -43, 1034, 57],
                "x": 978,
                "y": 54,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [319, -2, 443, 95],
                "x": 373,
                "y": 102,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 5, "y": 528, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 942, "y": 33, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 348, "y": 311, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [255, 652, 380, 753],
                "x": 312,
                "y": 754,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 344, "y": 206, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 933, "y": 4, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [872, 241, 1005, 332],
                "x": 935,
                "y": 332,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 980, "y": 57, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [332, -22, 441, 78],
                "x": 386,
                "y": 83,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-65, 418, 50, 508],
                "x": 0,
                "y": 514,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 940, "y": 26, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 325, "y": 305, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 316, "y": 763, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 321, "y": 185, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 931, "y": 0, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 967, "y": 326, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 982, "y": 60, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 400, "y": 65, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [872, -90, 1006, 27],
                "x": 938,
                "y": 19,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 302, "y": 297, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 320, "y": 771, "track_id": None},
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 299, "y": 160, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 1000, "y": 319, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 984, "y": 63, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 413, "y": 49, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [881, -82, 991, 18],
                "x": 936,
                "y": 12,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 279, "y": 288, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [271, 684, 386, 779],
                "x": 325,
                "y": 778,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 276, "y": 133, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 987, "y": 66, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 426, "y": 35, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [872, -104, 997, 1],
                "x": 934,
                "y": 6,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 255, "y": 277, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 329, "y": 784, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [201, -1, 322, 101],
                "x": 253,
                "y": 104,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [922, -33, 1056, 59],
                "x": 989,
                "y": 69,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 440, "y": 22, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [874, -99, 994, -5],
                "x": 932,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 232, "y": 264, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 333, "y": 789, "track_id": None},
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [173, -28, 292, 79],
                "x": 231,
                "y": 72,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [925, -21, 1041, 68],
                "x": 991,
                "y": 72,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 453, "y": 12, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [144, 149, 261, 256],
                "x": 209,
                "y": 249,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 337, "y": 794, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 208, "y": 37, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 993, "y": 75, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 466, "y": 5, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [123, 132, 255, 227],
                "x": 186,
                "y": 233,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 341, "y": 797, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 186, "y": 0, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 995, "y": 78, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 480, "y": 0, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 162, "y": 215, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 346, "y": 800, "track_id": None},
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 4, "bounding_box": [], "x": 997, "y": 81, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [86, 85, 189, 189],
                "x": 139,
                "y": 195,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 85, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 116, "y": 173, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 8,
                "bounding_box": [40, 43, 145, 152],
                "x": 93,
                "y": 150,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 41,
        "data": [{"cb_id": 8, "bounding_box": [], "x": 69, "y": 124, "track_id": None}],
    },
    {
        "frame_id": 42,
        "data": [{"cb_id": 8, "bounding_box": [], "x": 46, "y": 97, "track_id": None}],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 8,
                "bounding_box": [-38, -25, 84, 72],
                "x": 23,
                "y": 67,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 8,
                "bounding_box": [-60, -64, 59, 31],
                "x": 0,
                "y": 36,
                "track_id": None,
            }
        ],
    },
]
