country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [945, 501, 1067, 598],
                "x": 1000,
                "y": 602,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 57, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-50, 235, 67, 323],
                "x": 0,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [505, 709, 636, 808],
                "x": 566,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 560, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [-52, 682, 61, 778],
                "x": 0,
                "y": 777,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [154, 690, 270, 792],
                "x": 218,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [944, 602, 1069, 708],
                "x": 1000,
                "y": 700,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 267, "y": 0, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [933, 672, 1052, 761],
                "x": 1000,
                "y": 762,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 980, "y": 556, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [927, -27, 1042, 80],
                "x": 979,
                "y": 78,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-38, 230, 81, 325],
                "x": 28,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [514, 559, 652, 662],
                "x": 582,
                "y": 669,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [943, 435, 1050, 537],
                "x": 999,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-46, 650, 81, 768],
                "x": 23,
                "y": 759,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [161, 648, 289, 757],
                "x": 225,
                "y": 752,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [915, 570, 1038, 678],
                "x": 971,
                "y": 677,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [221, 86, 341, 173],
                "x": 289,
                "y": 180,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [909, 550, 1024, 648],
                "x": 972,
                "y": 645,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [906, 416, 1029, 520],
                "x": 960,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [904, 5, 1009, 98],
                "x": 958,
                "y": 98,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [6, 228, 108, 335],
                "x": 56,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [538, 455, 667, 572],
                "x": 598,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [948, 425, 1057, 521],
                "x": 998,
                "y": 528,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 46, "y": 740, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [175, 613, 292, 718],
                "x": 233,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [872, 566, 1008, 651],
                "x": 942,
                "y": 656,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [262, 228, 373, 319],
                "x": 312,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [878, 435, 1005, 544],
                "x": 944,
                "y": 543,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [880, 404, 992, 493],
                "x": 940,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [885, 16, 997, 120],
                "x": 937,
                "y": 118,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [18, 233, 140, 340],
                "x": 84,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [545, 369, 665, 473],
                "x": 614,
                "y": 476,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 998, "y": 512, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [19, 619, 135, 715],
                "x": 69,
                "y": 721,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [179, 564, 303, 660],
                "x": 240,
                "y": 670,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [864, 528, 971, 644],
                "x": 914,
                "y": 636,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [284, 328, 398, 425],
                "x": 335,
                "y": 432,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 916, "y": 456, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [855, 383, 979, 491],
                "x": 920,
                "y": 484,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 916, "y": 137, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [44, 222, 177, 342],
                "x": 112,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [572, 303, 686, 401],
                "x": 630,
                "y": 411,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [942, 386, 1051, 506],
                "x": 997,
                "y": 496,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 93, "y": 700, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [198, 533, 313, 631],
                "x": 248,
                "y": 637,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [831, 514, 935, 606],
                "x": 885,
                "y": 616,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [305, 401, 423, 506],
                "x": 358,
                "y": 510,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 888, "y": 382, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 901, "y": 478, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [834, 66, 952, 147],
                "x": 895,
                "y": 156,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 140, "y": 335, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [588, 264, 708, 371],
                "x": 646,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [939, 379, 1055, 487],
                "x": 997,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [65, 587, 180, 678],
                "x": 116,
                "y": 679,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [199, 507, 324, 607],
                "x": 256,
                "y": 607,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [794, 490, 924, 600],
                "x": 857,
                "y": 598,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [330, 451, 431, 567],
                "x": 381,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [792, 220, 917, 320],
                "x": 861,
                "y": 322,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [815, 374, 940, 473],
                "x": 881,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [813, 82, 936, 170],
                "x": 874,
                "y": 173,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [108, 247, 234, 333],
                "x": 168,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [598, 231, 720, 327],
                "x": 662,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [933, 358, 1050, 461],
                "x": 996,
                "y": 464,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [89, 567, 195, 658],
                "x": 139,
                "y": 658,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [204, 485, 327, 591],
                "x": 263,
                "y": 581,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [764, 490, 885, 578],
                "x": 828,
                "y": 581,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 404, "y": 586, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [769, 167, 898, 273],
                "x": 833,
                "y": 273,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 861, "y": 488, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [802, 92, 921, 200],
                "x": 853,
                "y": 190,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [132, 241, 255, 347],
                "x": 196,
                "y": 345,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 678, "y": 319, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [941, 354, 1066, 450],
                "x": 996,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [93, 545, 221, 636],
                "x": 162,
                "y": 636,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [204, 451, 338, 562],
                "x": 271,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [730, 469, 855, 556],
                "x": 800,
                "y": 564,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 427, "y": 593, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [736, 143, 870, 233],
                "x": 805,
                "y": 236,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [775, 413, 894, 494],
                "x": 841,
                "y": 503,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 833, "y": 207, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [154, 242, 284, 344],
                "x": 224,
                "y": 352,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [632, 227, 746, 308],
                "x": 694,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [927, 330, 1056, 441],
                "x": 995,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [117, 517, 252, 615],
                "x": 186,
                "y": 614,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 279, "y": 540, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [717, 447, 826, 556],
                "x": 771,
                "y": 549,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [379, 479, 507, 586],
                "x": 449,
                "y": 582,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 777, "y": 209, "track_id": None},
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [762, 428, 876, 531],
                "x": 821,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [744, 123, 869, 221],
                "x": 812,
                "y": 222,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [191, 250, 322, 359],
                "x": 253,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [653, 217, 771, 319],
                "x": 710,
                "y": 327,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [940, 307, 1049, 412],
                "x": 995,
                "y": 417,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 209, "y": 591, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [220, 426, 339, 524],
                "x": 286,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [682, 433, 794, 542],
                "x": 742,
                "y": 535,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [414, 458, 531, 567],
                "x": 472,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [685, 87, 803, 192],
                "x": 750,
                "y": 192,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [738, 449, 860, 548],
                "x": 802,
                "y": 545,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [726, 127, 851, 227],
                "x": 791,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [224, 274, 338, 372],
                "x": 281,
                "y": 368,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 726, "y": 346, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [925, 304, 1061, 404],
                "x": 994,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [169, 470, 286, 573],
                "x": 232,
                "y": 568,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [226, 418, 350, 504],
                "x": 294,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [661, 426, 783, 518],
                "x": 714,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [426, 417, 548, 520],
                "x": 495,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [653, 76, 784, 178],
                "x": 722,
                "y": 183,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [718, 482, 838, 582],
                "x": 782,
                "y": 572,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [708, 141, 835, 256],
                "x": 770,
                "y": 251,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 309, "y": 378, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [690, 270, 800, 377],
                "x": 742,
                "y": 373,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 994, "y": 386, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 255, "y": 545, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [251, 406, 370, 510],
                "x": 302,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [615, 402, 754, 508],
                "x": 685,
                "y": 509,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [467, 392, 578, 482],
                "x": 518,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [632, 79, 749, 175],
                "x": 694,
                "y": 183,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 762, "y": 600, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [698, 172, 816, 273],
                "x": 749,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [280, 291, 388, 399],
                "x": 337,
                "y": 389,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 758, "y": 406, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [930, 272, 1048, 373],
                "x": 993,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [218, 429, 342, 523],
                "x": 279,
                "y": 523,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [243, 401, 375, 489],
                "x": 309,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [590, 390, 710, 490],
                "x": 657,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [474, 337, 597, 448],
                "x": 541,
                "y": 442,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [599, 89, 730, 199],
                "x": 666,
                "y": 190,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [680, 529, 797, 625],
                "x": 742,
                "y": 630,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 728, "y": 276, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [312, 291, 421, 395],
                "x": 365,
                "y": 401,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 774, "y": 444, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [939, 259, 1060, 360],
                "x": 992,
                "y": 355,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [248, 396, 363, 495],
                "x": 302,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [248, 399, 367, 479],
                "x": 317,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 628, "y": 486, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [514, 298, 633, 393],
                "x": 564,
                "y": 400,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 638, "y": 203, "track_id": None},
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 722, "y": 661, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 707, "y": 287, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [326, 307, 462, 417],
                "x": 393,
                "y": 413,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 791, "y": 484, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [928, 233, 1061, 341],
                "x": 992,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [274, 384, 375, 482],
                "x": 325,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [266, 393, 381, 480],
                "x": 325,
                "y": 486,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [549, 367, 670, 478],
                "x": 600,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [526, 273, 657, 353],
                "x": 587,
                "y": 363,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [561, 115, 679, 218],
                "x": 611,
                "y": 221,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [640, 589, 761, 694],
                "x": 703,
                "y": 690,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [629, 203, 751, 301],
                "x": 686,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [360, 335, 488, 420],
                "x": 421,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [751, 435, 877, 519],
                "x": 807,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [941, 233, 1042, 328],
                "x": 991,
                "y": 325,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 348, "y": 455, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [279, 381, 399, 474],
                "x": 332,
                "y": 484,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [513, 377, 632, 470],
                "x": 571,
                "y": 467,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 610, "y": 333, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [526, 137, 637, 253],
                "x": 583,
                "y": 244,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [615, 623, 734, 723],
                "x": 683,
                "y": 719,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 666, "y": 307, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [390, 345, 519, 451],
                "x": 449,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [763, 476, 883, 576],
                "x": 823,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [929, 216, 1046, 315],
                "x": 991,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [304, 337, 425, 434],
                "x": 372,
                "y": 434,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 340, "y": 484, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [474, 356, 597, 455],
                "x": 542,
                "y": 459,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 632, "y": 315, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [497, 168, 618, 281],
                "x": 555,
                "y": 271,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 663, "y": 745, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [593, 206, 697, 319],
                "x": 645,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [409, 348, 540, 463],
                "x": 478,
                "y": 457,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [789, 500, 907, 598],
                "x": 839,
                "y": 603,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [921, 187, 1055, 294],
                "x": 990,
                "y": 294,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [330, 314, 458, 417],
                "x": 395,
                "y": 413,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 347, "y": 485, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 514, "y": 452, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [605, 201, 725, 314],
                "x": 655,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [460, 204, 592, 296],
                "x": 527,
                "y": 301,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [576, 672, 697, 767],
                "x": 643,
                "y": 767,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [571, 222, 674, 322],
                "x": 624,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [440, 383, 568, 474],
                "x": 506,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [801, 530, 909, 630],
                "x": 855,
                "y": 637,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [930, 172, 1049, 280],
                "x": 990,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [365, 293, 482, 393],
                "x": 418,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [293, 383, 418, 485],
                "x": 355,
                "y": 487,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [421, 336, 544, 444],
                "x": 485,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [617, 231, 746, 323],
                "x": 678,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [433, 232, 560, 341],
                "x": 500,
                "y": 333,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 623, "y": 786, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [540, 227, 665, 330],
                "x": 603,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [466, 398, 597, 489],
                "x": 534,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 871, "y": 665, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [933, 163, 1053, 268],
                "x": 989,
                "y": 264,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 441, "y": 372, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [303, 391, 427, 495],
                "x": 363,
                "y": 490,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [394, 340, 526, 438],
                "x": 457,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [643, 260, 770, 358],
                "x": 701,
                "y": 363,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [414, 263, 533, 356],
                "x": 472,
                "y": 366,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [552, 690, 669, 799],
                "x": 604,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [513, 234, 639, 338],
                "x": 582,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [504, 407, 629, 510],
                "x": 562,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [817, 574, 942, 676],
                "x": 887,
                "y": 684,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [931, 141, 1044, 240],
                "x": 989,
                "y": 249,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [396, 250, 530, 350],
                "x": 465,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [311, 388, 425, 496],
                "x": 370,
                "y": 493,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 428, "y": 435, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 724, "y": 425, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 444, "y": 400, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [504, 245, 626, 330],
                "x": 561,
                "y": 339,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 590, "y": 525, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 903, "y": 694, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [918, 139, 1046, 225],
                "x": 988,
                "y": 234,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [429, 245, 550, 342],
                "x": 488,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [310, 399, 432, 497],
                "x": 378,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [346, 325, 470, 434],
                "x": 400,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [693, 411, 800, 514],
                "x": 747,
                "y": 516,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 416, "y": 434, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [480, 251, 591, 347],
                "x": 540,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [551, 440, 679, 544],
                "x": 618,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [851, 592, 978, 690],
                "x": 919,
                "y": 693,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [925, 120, 1038, 220],
                "x": 988,
                "y": 219,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [445, 216, 566, 312],
                "x": 511,
                "y": 318,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [330, 394, 444, 495],
                "x": 386,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [303, 329, 426, 425],
                "x": 371,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [709, 534, 839, 635],
                "x": 770,
                "y": 640,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [335, 376, 451, 472],
                "x": 388,
                "y": 466,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [461, 238, 586, 346],
                "x": 520,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [585, 453, 711, 567],
                "x": 646,
                "y": 563,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 935, "y": 679, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 987, "y": 204, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 534, "y": 302, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 393, "y": 502, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [280, 320, 402, 418],
                "x": 342,
                "y": 425,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 793, "y": 800, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [292, 388, 419, 504],
                "x": 361,
                "y": 496,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [446, 236, 557, 338],
                "x": 499,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [605, 489, 727, 572],
                "x": 674,
                "y": 582,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 951, "y": 650, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [926, 83, 1054, 199],
                "x": 987,
                "y": 189,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 558, "y": 288, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [349, 397, 471, 500],
                "x": 401,
                "y": 505,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 314, "y": 423, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [279, 421, 394, 524],
                "x": 333,
                "y": 524,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [410, 234, 529, 338],
                "x": 478,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [652, 496, 758, 601],
                "x": 702,
                "y": 602,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [909, 501, 1024, 599],
                "x": 967,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [925, 72, 1040, 165],
                "x": 986,
                "y": 174,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [528, 183, 635, 278],
                "x": 581,
                "y": 275,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 409, "y": 507, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [215, 316, 341, 421],
                "x": 285,
                "y": 422,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 305, "y": 548, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 457, "y": 342, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 731, "y": 623, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 983, "y": 540, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [926, 54, 1037, 154],
                "x": 985,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [536, 162, 661, 255],
                "x": 604,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [349, 417, 472, 500],
                "x": 416,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [200, 317, 308, 421],
                "x": 257,
                "y": 421,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [224, 457, 336, 576],
                "x": 277,
                "y": 567,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [368, 241, 504, 344],
                "x": 436,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [706, 554, 828, 650],
                "x": 759,
                "y": 644,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 1000, "y": 457, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [935, 39, 1046, 145],
                "x": 985,
                "y": 144,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [571, 158, 697, 255],
                "x": 627,
                "y": 252,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [367, 397, 483, 507],
                "x": 424,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [172, 313, 288, 430],
                "x": 228,
                "y": 422,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [199, 473, 303, 576],
                "x": 250,
                "y": 581,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 415, "y": 335, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 787, "y": 666, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [929, 34, 1050, 125],
                "x": 984,
                "y": 130,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [597, 135, 707, 239],
                "x": 651,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [365, 402, 500, 515],
                "x": 432,
                "y": 505,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 200, "y": 423, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 222, "y": 589, "track_id": None},
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [334, 230, 455, 329],
                "x": 394,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [750, 584, 878, 684],
                "x": 815,
                "y": 687,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [923, 12, 1046, 115],
                "x": 984,
                "y": 115,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [615, 127, 724, 231],
                "x": 674,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [373, 411, 509, 492],
                "x": 439,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [103, 316, 221, 424],
                "x": 171,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [144, 481, 260, 584],
                "x": 194,
                "y": 590,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [322, 230, 425, 332],
                "x": 373,
                "y": 322,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [787, 603, 904, 703],
                "x": 843,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [917, 6, 1046, 98],
                "x": 983,
                "y": 100,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [640, 133, 755, 234],
                "x": 697,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [386, 386, 508, 499],
                "x": 447,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [89, 325, 212, 420],
                "x": 142,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [106, 477, 217, 580],
                "x": 166,
                "y": 583,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [290, 203, 423, 303],
                "x": 353,
                "y": 313,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 871, "y": 732, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [918, -11, 1035, 95],
                "x": 983,
                "y": 86,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [670, 127, 780, 224],
                "x": 720,
                "y": 228,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [396, 397, 514, 481],
                "x": 454,
                "y": 487,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 114, "y": 430, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [79, 464, 205, 562],
                "x": 138,
                "y": 568,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 332, "y": 303, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [837, 662, 962, 746],
                "x": 899,
                "y": 754,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [925, -28, 1037, 68],
                "x": 982,
                "y": 71,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [674, 129, 796, 234],
                "x": 744,
                "y": 227,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 462, "y": 476, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [32, 344, 146, 435],
                "x": 85,
                "y": 434,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 111, "y": 543, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [246, 197, 364, 289],
                "x": 311,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [877, 668, 989, 780],
                "x": 927,
                "y": 777,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 982, "y": 57, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 767, "y": 228, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 470, "y": 463, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-10, 339, 120, 445],
                "x": 57,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [32, 417, 151, 503],
                "x": 83,
                "y": 508,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [233, 189, 360, 280],
                "x": 290,
                "y": 279,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 956, "y": 800, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 981, "y": 42, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 790, "y": 231, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [423, 348, 542, 439],
                "x": 477,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-24, 352, 89, 435],
                "x": 28,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-7, 372, 115, 466],
                "x": 55,
                "y": 462,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 269, "y": 265, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [911, -74, 1036, 23],
                "x": 981,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [753, 132, 878, 244],
                "x": 813,
                "y": 236,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 485, "y": 427, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-60, 344, 55, 443],
                "x": 0,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-43, 299, 81, 395],
                "x": 27,
                "y": 404,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [186, 144, 318, 253],
                "x": 248,
                "y": 249,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [927, -76, 1042, 14],
                "x": 980,
                "y": 14,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [771, 136, 898, 246],
                "x": 837,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [439, 295, 560, 400],
                "x": 493,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-56, 242, 70, 323],
                "x": 0,
                "y": 333,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [158, 138, 279, 232],
                "x": 227,
                "y": 232,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [916, -101, 1037, -2],
                "x": 980,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 860, "y": 255, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [450, 280, 557, 386],
                "x": 500,
                "y": 377,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 206, "y": 213, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [818, 171, 947, 258],
                "x": 883,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [439, 257, 576, 344],
                "x": 508,
                "y": 347,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [118, 95, 252, 182],
                "x": 186,
                "y": 192,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [839, 180, 967, 274],
                "x": 906,
                "y": 283,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 516, "y": 312, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [100, 76, 233, 169],
                "x": 165,
                "y": 170,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 930, "y": 302, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [458, 168, 587, 272],
                "x": 523,
                "y": 272,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [79, 39, 199, 142],
                "x": 144,
                "y": 146,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [898, 229, 1014, 316],
                "x": 953,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [463, 133, 587, 232],
                "x": 531,
                "y": 228,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [53, 30, 181, 125],
                "x": 123,
                "y": 120,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [916, 252, 1029, 357],
                "x": 976,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [472, 87, 605, 189],
                "x": 539,
                "y": 179,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [34, 3, 168, 102],
                "x": 102,
                "y": 93,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [933, 273, 1062, 379],
                "x": 1000,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [492, 19, 599, 122],
                "x": 546,
                "y": 125,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 81, "y": 63, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [503, -44, 615, 62],
                "x": 554,
                "y": 65,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-1, -70, 129, 41],
                "x": 60,
                "y": 32,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [496, -102, 628, -3],
                "x": 562,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-13, -103, 110, -3],
                "x": 40,
                "y": 0,
                "track_id": None,
            }
        ],
    },
]
