country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [129, -101, 247, 1],
                "x": 187,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [942, 75, 1059, 178],
                "x": 1000,
                "y": 176,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 590, "y": 0, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [942, 198, 1059, 298],
                "x": 1000,
                "y": 297,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [941, 571, 1061, 672],
                "x": 1000,
                "y": 670,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [938, 513, 1059, 612],
                "x": 1000,
                "y": 612,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-58, 486, 59, 584],
                "x": 0,
                "y": 585,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 821, "y": 800, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [497, -102, 619, 1],
                "x": 557,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [933, -100, 1055, 0],
                "x": 994,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 193, "y": 10, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [938, 70, 1060, 172],
                "x": 999,
                "y": 172,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [531, -83, 650, 18],
                "x": 590,
                "y": 19,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [900, 179, 1016, 278],
                "x": 958,
                "y": 280,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [900, 577, 1021, 679],
                "x": 960,
                "y": 677,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [915, 391, 1035, 489],
                "x": 977,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-29, 396, 94, 498],
                "x": 33,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [765, 697, 884, 798],
                "x": 824,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [506, -88, 629, 13],
                "x": 567,
                "y": 12,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [935, -84, 1053, 16],
                "x": 994,
                "y": 18,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 199, "y": 23, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [936, 69, 1056, 170],
                "x": 998,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [529, -59, 650, 41],
                "x": 590,
                "y": 39,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [856, 166, 976, 267],
                "x": 916,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [859, 569, 978, 669],
                "x": 920,
                "y": 669,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [896, 284, 1017, 383],
                "x": 955,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [7, 321, 128, 421],
                "x": 66,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 828, "y": 798, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [518, -73, 637, 26],
                "x": 577,
                "y": 26,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [936, -63, 1054, 36],
                "x": 994,
                "y": 36,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [147, -64, 266, 38],
                "x": 205,
                "y": 38,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [936, 65, 1055, 164],
                "x": 997,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [530, -40, 651, 59],
                "x": 590,
                "y": 59,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [813, 159, 936, 261],
                "x": 875,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [819, 550, 939, 648],
                "x": 880,
                "y": 648,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [870, 189, 991, 288],
                "x": 932,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [37, 261, 159, 362],
                "x": 99,
                "y": 362,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [772, 697, 892, 797],
                "x": 832,
                "y": 797,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [527, -61, 648, 43],
                "x": 587,
                "y": 41,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [936, -48, 1056, 56],
                "x": 994,
                "y": 54,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [151, -42, 269, 58],
                "x": 211,
                "y": 56,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [938, 58, 1054, 160],
                "x": 996,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [532, -23, 649, 79],
                "x": 590,
                "y": 78,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [772, 151, 891, 254],
                "x": 833,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [782, 518, 900, 614],
                "x": 840,
                "y": 616,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [852, 113, 971, 214],
                "x": 910,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [73, 211, 193, 312],
                "x": 133,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [774, 698, 897, 796],
                "x": 836,
                "y": 796,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [537, -43, 659, 55],
                "x": 598,
                "y": 57,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [932, -30, 1055, 73],
                "x": 994,
                "y": 72,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [158, -22, 279, 78],
                "x": 217,
                "y": 77,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [935, 54, 1056, 155],
                "x": 995,
                "y": 154,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [531, -4, 648, 98],
                "x": 590,
                "y": 98,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [731, 150, 853, 251],
                "x": 791,
                "y": 249,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [739, 478, 859, 577],
                "x": 800,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [826, 46, 947, 150],
                "x": 887,
                "y": 148,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [107, 173, 228, 272],
                "x": 166,
                "y": 272,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 840, "y": 795, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [549, -27, 669, 75],
                "x": 608,
                "y": 74,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [933, -11, 1056, 91],
                "x": 994,
                "y": 90,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 223, "y": 100, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [934, 49, 1056, 152],
                "x": 994,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [530, 16, 651, 118],
                "x": 590,
                "y": 117,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [689, 148, 809, 247],
                "x": 750,
                "y": 248,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [701, 429, 818, 529],
                "x": 760,
                "y": 530,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [804, -4, 926, 96],
                "x": 865,
                "y": 97,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [137, 143, 261, 244],
                "x": 199,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [781, 693, 905, 793],
                "x": 843,
                "y": 793,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [559, -10, 679, 92],
                "x": 618,
                "y": 92,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [932, 7, 1055, 107],
                "x": 994,
                "y": 108,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [168, 26, 289, 125],
                "x": 229,
                "y": 125,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [935, 46, 1054, 148],
                "x": 993,
                "y": 146,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [529, 34, 649, 136],
                "x": 591,
                "y": 136,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [646, 149, 769, 250],
                "x": 708,
                "y": 248,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [659, 378, 780, 478],
                "x": 721,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [784, -45, 905, 56],
                "x": 843,
                "y": 57,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 233, "y": 224, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [789, 693, 909, 794],
                "x": 847,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [569, 11, 688, 113],
                "x": 629,
                "y": 111,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [935, 26, 1054, 125],
                "x": 995,
                "y": 126,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [177, 50, 295, 151],
                "x": 235,
                "y": 152,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [933, 43, 1051, 142],
                "x": 992,
                "y": 141,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 591, "y": 155, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [604, 147, 724, 247],
                "x": 666,
                "y": 249,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [619, 332, 743, 428],
                "x": 681,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [761, -72, 879, 27],
                "x": 820,
                "y": 29,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [207, 111, 326, 211],
                "x": 266,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [793, 689, 910, 791],
                "x": 851,
                "y": 790,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [579, 30, 700, 131],
                "x": 639,
                "y": 131,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [937, 46, 1055, 144],
                "x": 995,
                "y": 144,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [179, 80, 299, 183],
                "x": 241,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [933, 37, 1053, 136],
                "x": 991,
                "y": 137,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [532, 75, 653, 177],
                "x": 591,
                "y": 175,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [563, 154, 686, 250],
                "x": 625,
                "y": 252,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 641, "y": 382, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [740, -90, 856, 11],
                "x": 798,
                "y": 11,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [238, 111, 358, 210],
                "x": 299,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [794, 688, 914, 787],
                "x": 855,
                "y": 788,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 649, "y": 152, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [937, 61, 1055, 163],
                "x": 995,
                "y": 162,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [186, 114, 305, 214],
                "x": 247,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [928, 34, 1051, 132],
                "x": 990,
                "y": 133,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [531, 95, 650, 192],
                "x": 591,
                "y": 194,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [525, 152, 645, 253],
                "x": 583,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [543, 237, 661, 335],
                "x": 601,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [713, -96, 833, 0],
                "x": 775,
                "y": 2,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [273, 113, 393, 216],
                "x": 333,
                "y": 215,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [801, 685, 917, 786],
                "x": 859,
                "y": 786,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [598, 74, 720, 174],
                "x": 660,
                "y": 174,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [934, 82, 1054, 181],
                "x": 995,
                "y": 181,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [195, 143, 313, 247],
                "x": 253,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [929, 30, 1047, 129],
                "x": 989,
                "y": 129,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [533, 113, 649, 214],
                "x": 591,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [482, 159, 603, 256],
                "x": 541,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [501, 201, 620, 297],
                "x": 561,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [693, -97, 812, 3],
                "x": 753,
                "y": 2,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [304, 129, 428, 229],
                "x": 366,
                "y": 227,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [804, 682, 924, 785],
                "x": 862,
                "y": 784,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [608, 97, 728, 195],
                "x": 670,
                "y": 196,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [934, 97, 1056, 199],
                "x": 995,
                "y": 199,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [201, 180, 318, 278],
                "x": 260,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [929, 27, 1046, 124],
                "x": 988,
                "y": 125,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [530, 134, 653, 230],
                "x": 591,
                "y": 232,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [440, 160, 560, 262],
                "x": 500,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [460, 171, 580, 270],
                "x": 521,
                "y": 269,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [672, -88, 793, 12],
                "x": 731,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [341, 144, 458, 244],
                "x": 399,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [807, 679, 925, 779],
                "x": 866,
                "y": 781,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [619, 120, 739, 218],
                "x": 680,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [933, 116, 1053, 215],
                "x": 995,
                "y": 217,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [205, 217, 327, 314],
                "x": 266,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [926, 23, 1047, 121],
                "x": 987,
                "y": 121,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [531, 152, 652, 252],
                "x": 592,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [397, 161, 516, 263],
                "x": 458,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [421, 153, 539, 252],
                "x": 481,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [646, -74, 770, 22],
                "x": 708,
                "y": 24,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [373, 167, 492, 266],
                "x": 433,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [809, 679, 929, 778],
                "x": 870,
                "y": 779,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [631, 140, 752, 241],
                "x": 690,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [936, 137, 1055, 236],
                "x": 995,
                "y": 235,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [211, 252, 331, 353],
                "x": 272,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [925, 18, 1048, 116],
                "x": 986,
                "y": 116,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [534, 169, 654, 271],
                "x": 592,
                "y": 269,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [357, 163, 474, 263],
                "x": 416,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [380, 144, 500, 244],
                "x": 442,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [624, -57, 746, 43],
                "x": 686,
                "y": 44,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [404, 197, 526, 294],
                "x": 466,
                "y": 295,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [814, 677, 935, 774],
                "x": 874,
                "y": 776,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [639, 164, 762, 265],
                "x": 701,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [937, 156, 1055, 253],
                "x": 996,
                "y": 254,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [217, 291, 339, 393],
                "x": 278,
                "y": 393,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [923, 13, 1047, 113],
                "x": 985,
                "y": 112,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [532, 189, 654, 286],
                "x": 592,
                "y": 288,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 375, "y": 263, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [341, 157, 462, 255],
                "x": 402,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [602, -28, 722, 70],
                "x": 663,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [440, 226, 557, 325],
                "x": 499,
                "y": 327,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [818, 673, 940, 774],
                "x": 878,
                "y": 773,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 711, "y": 289, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [934, 171, 1055, 274],
                "x": 996,
                "y": 272,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [223, 333, 343, 434],
                "x": 284,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [926, 6, 1044, 108],
                "x": 984,
                "y": 108,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 592, "y": 307, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [272, 160, 395, 261],
                "x": 333,
                "y": 261,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [301, 188, 420, 288],
                "x": 362,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [582, -3, 701, 100],
                "x": 641,
                "y": 99,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [472, 263, 592, 362],
                "x": 532,
                "y": 362,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [823, 669, 941, 772],
                "x": 881,
                "y": 770,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [662, 212, 781, 312],
                "x": 721,
                "y": 313,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 996, "y": 290, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [231, 374, 348, 478],
                "x": 290,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [921, 5, 1043, 103],
                "x": 983,
                "y": 104,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [531, 227, 652, 326],
                "x": 592,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [230, 156, 353, 256],
                "x": 291,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [262, 240, 380, 340],
                "x": 322,
                "y": 338,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [557, 31, 681, 132],
                "x": 619,
                "y": 132,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [508, 302, 624, 398],
                "x": 566,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [825, 667, 943, 765],
                "x": 885,
                "y": 767,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [674, 238, 791, 337],
                "x": 732,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [935, 210, 1054, 307],
                "x": 996,
                "y": 309,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [237, 419, 355, 517],
                "x": 296,
                "y": 519,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [924, 0, 1040, 98],
                "x": 982,
                "y": 100,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [533, 244, 651, 346],
                "x": 592,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [191, 148, 309, 251],
                "x": 250,
                "y": 250,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [222, 314, 343, 413],
                "x": 282,
                "y": 412,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [535, 66, 657, 166],
                "x": 596,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [541, 338, 659, 438],
                "x": 599,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [830, 662, 947, 766],
                "x": 889,
                "y": 764,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 742, "y": 361, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [938, 228, 1054, 327],
                "x": 996,
                "y": 327,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [244, 461, 363, 565],
                "x": 302,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [919, -1, 1040, 95],
                "x": 981,
                "y": 97,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [534, 264, 653, 363],
                "x": 593,
                "y": 362,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [150, 138, 268, 238],
                "x": 208,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [184, 411, 302, 513],
                "x": 242,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [515, 105, 635, 203],
                "x": 574,
                "y": 205,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [570, 381, 692, 478],
                "x": 632,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [833, 660, 952, 759],
                "x": 893,
                "y": 760,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [691, 283, 814, 384],
                "x": 752,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 243, 1056, 343],
                "x": 996,
                "y": 345,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 308, "y": 609, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 980, "y": 93, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [534, 280, 653, 382],
                "x": 593,
                "y": 381,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 166, "y": 227, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [140, 542, 264, 642],
                "x": 202,
                "y": 641,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [492, 145, 613, 243],
                "x": 551,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [605, 422, 726, 519],
                "x": 666,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [838, 655, 955, 758],
                "x": 897,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [705, 308, 824, 407],
                "x": 763,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 263, 1058, 365],
                "x": 997,
                "y": 364,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [255, 557, 376, 653],
                "x": 314,
                "y": 655,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [918, -12, 1037, 91],
                "x": 979,
                "y": 89,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [531, 301, 652, 399],
                "x": 593,
                "y": 399,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [64, 109, 186, 209],
                "x": 125,
                "y": 209,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [102, 701, 224, 802],
                "x": 163,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [468, 180, 591, 280],
                "x": 529,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [641, 463, 759, 562],
                "x": 699,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [841, 651, 960, 755],
                "x": 900,
                "y": 753,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 773, "y": 432, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [939, 281, 1059, 383],
                "x": 997,
                "y": 382,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [260, 603, 378, 701],
                "x": 320,
                "y": 703,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [919, -13, 1037, 84],
                "x": 978,
                "y": 85,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 593, "y": 417, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [25, 89, 143, 187],
                "x": 83,
                "y": 188,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [447, 220, 564, 317],
                "x": 506,
                "y": 319,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 732, "y": 602, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [845, 647, 963, 751],
                "x": 904,
                "y": 749,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [721, 356, 842, 454],
                "x": 783,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 303, 1055, 402],
                "x": 997,
                "y": 401,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [264, 650, 387, 749],
                "x": 326,
                "y": 751,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [917, -17, 1035, 80],
                "x": 977,
                "y": 81,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 333, 654, 433],
                "x": 593,
                "y": 435,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 41, "y": 162, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [424, 252, 543, 352],
                "x": 484,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [704, 538, 827, 638],
                "x": 766,
                "y": 640,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 908, "y": 745, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [735, 379, 851, 481],
                "x": 793,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 319, 1055, 417],
                "x": 997,
                "y": 419,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [271, 701, 391, 801],
                "x": 333,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [917, -21, 1037, 78],
                "x": 976,
                "y": 77,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [534, 351, 655, 454],
                "x": 593,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-59, 32, 61, 130],
                "x": 0,
                "y": 132,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [403, 287, 523, 385],
                "x": 462,
                "y": 387,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [739, 579, 860, 679],
                "x": 799,
                "y": 677,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 912, "y": 740, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [744, 401, 862, 500],
                "x": 804,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [937, 340, 1057, 437],
                "x": 997,
                "y": 438,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [917, -28, 1034, 72],
                "x": 975,
                "y": 74,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 369, 652, 470],
                "x": 593,
                "y": 471,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 439, "y": 417, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [773, 609, 891, 709],
                "x": 832,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [854, 637, 976, 737],
                "x": 916,
                "y": 735,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [752, 422, 873, 524],
                "x": 814,
                "y": 523,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [937, 354, 1058, 454],
                "x": 997,
                "y": 456,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [913, -30, 1032, 70],
                "x": 974,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 387, 654, 488],
                "x": 594,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [355, 342, 476, 441],
                "x": 417,
                "y": 442,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [808, 642, 924, 739],
                "x": 866,
                "y": 740,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [858, 630, 978, 729],
                "x": 920,
                "y": 731,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [766, 445, 886, 547],
                "x": 824,
                "y": 545,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 373, 1057, 476],
                "x": 997,
                "y": 475,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 973, "y": 66, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [533, 406, 655, 505],
                "x": 594,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [334, 361, 454, 464],
                "x": 394,
                "y": 463,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [838, 664, 957, 765],
                "x": 899,
                "y": 765,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [864, 628, 982, 726],
                "x": 923,
                "y": 726,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [774, 465, 895, 566],
                "x": 835,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [937, 391, 1056, 493],
                "x": 998,
                "y": 493,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [914, -39, 1033, 65],
                "x": 972,
                "y": 63,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [532, 425, 655, 526],
                "x": 594,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [310, 377, 430, 476],
                "x": 372,
                "y": 477,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 932, "y": 785, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [868, 619, 985, 721],
                "x": 927,
                "y": 721,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [787, 483, 906, 586],
                "x": 845,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 414, 1059, 511],
                "x": 998,
                "y": 512,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [913, -42, 1032, 57],
                "x": 971,
                "y": 59,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 442, 656, 540],
                "x": 594,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [292, 386, 411, 483],
                "x": 350,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [904, 697, 1026, 800],
                "x": 966,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [872, 615, 991, 713],
                "x": 931,
                "y": 715,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [796, 503, 917, 604],
                "x": 855,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [937, 428, 1060, 529],
                "x": 998,
                "y": 530,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [909, -46, 1032, 54],
                "x": 970,
                "y": 56,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [536, 458, 653, 560],
                "x": 594,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [268, 386, 386, 484],
                "x": 327,
                "y": 484,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [877, 610, 994, 710],
                "x": 935,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [804, 525, 927, 625],
                "x": 866,
                "y": 623,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [937, 448, 1060, 551],
                "x": 998,
                "y": 549,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [911, -47, 1027, 54],
                "x": 969,
                "y": 52,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [534, 476, 656, 579],
                "x": 594,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [247, 377, 366, 476],
                "x": 305,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [877, 606, 1000, 704],
                "x": 939,
                "y": 704,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [815, 540, 935, 640],
                "x": 876,
                "y": 640,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 470, 1056, 566],
                "x": 998,
                "y": 568,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [910, -50, 1029, 50],
                "x": 968,
                "y": 48,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 496, 654, 593],
                "x": 595,
                "y": 595,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [223, 357, 344, 459],
                "x": 282,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [881, 599, 1000, 699],
                "x": 942,
                "y": 698,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 886, "y": 656, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [939, 485, 1056, 585],
                "x": 998,
                "y": 586,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [907, -55, 1026, 43],
                "x": 967,
                "y": 45,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [533, 515, 654, 614],
                "x": 595,
                "y": 613,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [200, 331, 318, 429],
                "x": 260,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [884, 590, 1007, 691],
                "x": 946,
                "y": 692,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [834, 570, 954, 673],
                "x": 896,
                "y": 671,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [940, 503, 1058, 604],
                "x": 998,
                "y": 605,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [904, -57, 1027, 40],
                "x": 966,
                "y": 42,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 532, 656, 629],
                "x": 595,
                "y": 630,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [176, 289, 298, 393],
                "x": 238,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [889, 587, 1010, 683],
                "x": 950,
                "y": 685,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 907, "y": 684, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [937, 525, 1059, 626],
                "x": 999,
                "y": 624,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [905, -62, 1023, 38],
                "x": 965,
                "y": 38,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 549, 655, 647],
                "x": 595,
                "y": 647,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 215, "y": 340, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [895, 577, 1014, 679],
                "x": 954,
                "y": 679,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [856, 594, 979, 698],
                "x": 917,
                "y": 696,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [938, 545, 1060, 645],
                "x": 999,
                "y": 643,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [903, -67, 1025, 37],
                "x": 964,
                "y": 35,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [534, 564, 654, 662],
                "x": 595,
                "y": 664,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [135, 177, 251, 276],
                "x": 193,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [897, 570, 1018, 670],
                "x": 958,
                "y": 672,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 927, "y": 707, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [940, 560, 1059, 663],
                "x": 999,
                "y": 661,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [905, -71, 1025, 31],
                "x": 963,
                "y": 31,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 582, 656, 680],
                "x": 595,
                "y": 682,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [109, 99, 230, 198],
                "x": 170,
                "y": 198,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [899, 564, 1022, 666],
                "x": 961,
                "y": 665,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [878, 614, 998, 714],
                "x": 938,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [940, 578, 1059, 678],
                "x": 999,
                "y": 680,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [900, -73, 1020, 28],
                "x": 962,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [537, 598, 657, 701],
                "x": 596,
                "y": 699,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [87, 5, 208, 107],
                "x": 148,
                "y": 107,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [904, 559, 1025, 658],
                "x": 965,
                "y": 658,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [886, 622, 1008, 725],
                "x": 948,
                "y": 724,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [939, 601, 1061, 697],
                "x": 999,
                "y": 699,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [899, -74, 1021, 24],
                "x": 961,
                "y": 25,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [538, 615, 655, 717],
                "x": 596,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [66, -101, 185, -1],
                "x": 126,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [907, 552, 1028, 652],
                "x": 969,
                "y": 651,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 958, "y": 730, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 999, "y": 718, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 960, "y": 22, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [536, 633, 656, 731],
                "x": 596,
                "y": 733,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [914, 541, 1034, 642],
                "x": 973,
                "y": 643,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 969, "y": 734, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [939, 634, 1060, 737],
                "x": 1000,
                "y": 736,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [899, -83, 1019, 19],
                "x": 959,
                "y": 18,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 649, 656, 748],
                "x": 596,
                "y": 749,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [915, 534, 1039, 637],
                "x": 977,
                "y": 635,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [920, 635, 1039, 737],
                "x": 979,
                "y": 737,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 958, "y": 15, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [537, 667, 657, 767],
                "x": 596,
                "y": 766,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [922, 527, 1039, 628],
                "x": 980,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [929, 637, 1047, 736],
                "x": 989,
                "y": 737,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [895, -86, 1017, 10],
                "x": 957,
                "y": 12,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [536, 683, 655, 784],
                "x": 596,
                "y": 783,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [926, 519, 1043, 618],
                "x": 984,
                "y": 619,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [942, 636, 1061, 734],
                "x": 1000,
                "y": 735,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [898, -93, 1016, 11],
                "x": 956,
                "y": 9,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [536, 698, 657, 800],
                "x": 597,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [927, 509, 1046, 612],
                "x": 988,
                "y": 610,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 955, "y": 6, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [930, 501, 1053, 600],
                "x": 992,
                "y": 602,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [894, -98, 1013, 3],
                "x": 954,
                "y": 3,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 996, "y": 593, "track_id": None},
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [894, -101, 1013, 2],
                "x": 953,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [942, 486, 1061, 586],
                "x": 1000,
                "y": 584,
                "track_id": None,
            },
        ],
    },
]
