country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 1000, "y": 685, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [283, -95, 394, -5],
                "x": 338,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 180, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 500, "y": 800, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-59, 135, 64, 231],
                "x": 0,
                "y": 236,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 1000, "y": 647, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [926, -95, 1055, 1],
                "x": 990,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [941, 272, 1062, 369],
                "x": 1000,
                "y": 368,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-56, 456, 65, 553],
                "x": 0,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [935, 212, 1055, 309],
                "x": 1000,
                "y": 308,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [912, 484, 1033, 577],
                "x": 975,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [272, -55, 394, 39],
                "x": 335,
                "y": 41,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 993, "y": 182, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [426, 661, 546, 771],
                "x": 489,
                "y": 766,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-44, 211, 82, 310],
                "x": 21,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [901, 537, 1023, 640],
                "x": 965,
                "y": 639,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [935, -91, 1052, 10],
                "x": 990,
                "y": 11,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [910, 316, 1035, 417],
                "x": 972,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-5, 390, 109, 495],
                "x": 50,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [918, 202, 1040, 303],
                "x": 977,
                "y": 303,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 951, "y": 494, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [268, -14, 397, 80],
                "x": 333,
                "y": 82,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [928, 87, 1041, 189],
                "x": 986,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [417, 630, 537, 732],
                "x": 479,
                "y": 734,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 42, "y": 368, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [867, 521, 990, 630],
                "x": 930,
                "y": 625,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [934, -76, 1053, 23],
                "x": 990,
                "y": 23,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [886, 348, 1001, 453],
                "x": 944,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [37, 347, 156, 452],
                "x": 100,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [889, 202, 1013, 302],
                "x": 954,
                "y": 299,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [866, 318, 983, 415],
                "x": 926,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [275, 23, 392, 123],
                "x": 331,
                "y": 121,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [920, 84, 1043, 189],
                "x": 979,
                "y": 187,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 469, "y": 702, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [8, 317, 119, 424],
                "x": 63,
                "y": 420,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 895, "y": 603, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [935, -70, 1055, 32],
                "x": 990,
                "y": 35,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 916, "y": 486, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [89, 316, 213, 425],
                "x": 150,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [873, 196, 986, 292],
                "x": 931,
                "y": 295,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 902, "y": 359, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [269, 61, 386, 161],
                "x": 329,
                "y": 160,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [915, 86, 1029, 193],
                "x": 972,
                "y": 191,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [400, 573, 523, 674],
                "x": 459,
                "y": 671,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 85, "y": 465, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [805, 478, 919, 574],
                "x": 860,
                "y": 576,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 990, "y": 47, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [827, 415, 943, 512],
                "x": 888,
                "y": 515,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [135, 303, 261, 401],
                "x": 200,
                "y": 405,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [850, 186, 965, 292],
                "x": 909,
                "y": 290,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [821, 210, 939, 305],
                "x": 878,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [265, 93, 385, 199],
                "x": 327,
                "y": 197,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [900, 99, 1025, 200],
                "x": 965,
                "y": 196,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 448, "y": 640, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [47, 400, 171, 504],
                "x": 106,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [767, 440, 888, 541],
                "x": 825,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [936, -42, 1046, 56],
                "x": 991,
                "y": 59,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [805, 435, 924, 541],
                "x": 861,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [186, 301, 313, 403],
                "x": 250,
                "y": 400,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 886, "y": 286, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [797, 174, 909, 275],
                "x": 853,
                "y": 270,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 324, "y": 233, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 958, "y": 202, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [383, 514, 496, 606],
                "x": 438,
                "y": 610,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 127, "y": 531, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [729, 411, 849, 514],
                "x": 791,
                "y": 509,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 991, "y": 71, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [778, 458, 890, 562],
                "x": 833,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [240, 309, 364, 403],
                "x": 300,
                "y": 404,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 863, "y": 282, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [766, 142, 887, 244],
                "x": 829,
                "y": 240,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 322, "y": 268, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [896, 106, 1012, 204],
                "x": 951,
                "y": 209,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 428, "y": 581, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [90, 450, 205, 557],
                "x": 148,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [699, 374, 815, 476],
                "x": 756,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [933, -22, 1052, 85],
                "x": 991,
                "y": 83,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [748, 473, 869, 571],
                "x": 805,
                "y": 571,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [285, 311, 407, 413],
                "x": 350,
                "y": 414,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 840, "y": 279, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 805, "y": 220, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [255, 206, 385, 305],
                "x": 320,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [880, 113, 1006, 218],
                "x": 944,
                "y": 217,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [359, 454, 482, 552],
                "x": 418,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [107, 473, 235, 566],
                "x": 170,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [657, 329, 784, 433],
                "x": 721,
                "y": 434,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [930, -7, 1050, 91],
                "x": 991,
                "y": 95,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [713, 484, 837, 585],
                "x": 777,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [338, 324, 465, 425],
                "x": 400,
                "y": 428,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [760, 171, 881, 271],
                "x": 818,
                "y": 275,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [716, 110, 837, 206],
                "x": 780,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [254, 239, 382, 332],
                "x": 318,
                "y": 334,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 937, "y": 226, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [347, 423, 473, 530],
                "x": 408,
                "y": 526,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [136, 474, 249, 582],
                "x": 191,
                "y": 579,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [621, 293, 741, 395],
                "x": 686,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [926, 4, 1052, 108],
                "x": 991,
                "y": 107,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 750, "y": 589, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [389, 345, 510, 444],
                "x": 450,
                "y": 444,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [734, 168, 859, 277],
                "x": 795,
                "y": 272,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 756, "y": 201, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [252, 266, 371, 365],
                "x": 316,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [870, 137, 989, 238],
                "x": 930,
                "y": 235,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [338, 402, 457, 503],
                "x": 397,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [150, 484, 277, 583],
                "x": 212,
                "y": 583,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 651, "y": 358, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 992, "y": 119, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [657, 496, 782, 597],
                "x": 722,
                "y": 592,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [438, 356, 565, 462],
                "x": 500,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [716, 171, 834, 268],
                "x": 772,
                "y": 269,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [674, 105, 787, 199],
                "x": 732,
                "y": 202,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 313, "y": 395, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [859, 140, 980, 250],
                "x": 923,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [328, 379, 448, 473],
                "x": 387,
                "y": 474,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [174, 479, 291, 579],
                "x": 234,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [552, 226, 672, 322],
                "x": 617,
                "y": 322,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [937, 33, 1051, 126],
                "x": 992,
                "y": 131,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [635, 496, 755, 590],
                "x": 694,
                "y": 593,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [495, 369, 615, 474],
                "x": 550,
                "y": 470,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [690, 162, 805, 262],
                "x": 750,
                "y": 266,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [645, 104, 767, 208],
                "x": 707,
                "y": 207,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 311, "y": 423, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [860, 159, 980, 261],
                "x": 916,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [318, 352, 442, 454],
                "x": 377,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [190, 476, 311, 578],
                "x": 255,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [527, 191, 638, 286],
                "x": 582,
                "y": 290,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 992, "y": 143, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [610, 486, 721, 594],
                "x": 666,
                "y": 590,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [545, 375, 655, 477],
                "x": 600,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [664, 166, 788, 262],
                "x": 727,
                "y": 263,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [624, 113, 745, 220],
                "x": 683,
                "y": 217,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [251, 349, 366, 446],
                "x": 309,
                "y": 450,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 909, "y": 268, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [305, 326, 424, 426],
                "x": 367,
                "y": 426,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [211, 460, 340, 570],
                "x": 276,
                "y": 565,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 547, "y": 262, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [931, 54, 1047, 161],
                "x": 992,
                "y": 156,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [581, 481, 703, 585],
                "x": 638,
                "y": 586,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 650, "y": 475, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [640, 158, 762, 267],
                "x": 704,
                "y": 262,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [601, 132, 716, 226],
                "x": 659,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [246, 377, 366, 475],
                "x": 307,
                "y": 475,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 902, "y": 280, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [294, 309, 416, 407],
                "x": 357,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [235, 453, 353, 545],
                "x": 297,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [453, 139, 571, 242],
                "x": 512,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [936, 69, 1057, 172],
                "x": 992,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [553, 479, 668, 579],
                "x": 611,
                "y": 579,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [639, 368, 761, 458],
                "x": 700,
                "y": 463,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [616, 159, 739, 259],
                "x": 681,
                "y": 260,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [570, 145, 693, 247],
                "x": 634,
                "y": 244,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 305, "y": 499, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [840, 195, 956, 295],
                "x": 895,
                "y": 292,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 346, "y": 382, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [264, 427, 379, 536],
                "x": 319,
                "y": 532,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 477, "y": 224, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [936, 75, 1055, 178],
                "x": 993,
                "y": 180,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [518, 467, 646, 573],
                "x": 583,
                "y": 571,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [689, 337, 814, 442],
                "x": 750,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [598, 164, 718, 260],
                "x": 659,
                "y": 259,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 610, "y": 260, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [245, 421, 366, 521],
                "x": 303,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [832, 211, 944, 303],
                "x": 888,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [281, 260, 393, 362],
                "x": 336,
                "y": 362,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [278, 411, 397, 516],
                "x": 340,
                "y": 511,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [382, 111, 505, 221],
                "x": 443,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [932, 90, 1048, 189],
                "x": 993,
                "y": 192,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [494, 459, 619, 558],
                "x": 555,
                "y": 561,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 800, "y": 399, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 636, "y": 259, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 585, "y": 276, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 300, "y": 541, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [825, 220, 939, 323],
                "x": 882,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [262, 242, 381, 347],
                "x": 326,
                "y": 344,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 361, "y": 487, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [345, 119, 463, 217],
                "x": 408,
                "y": 217,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 993, "y": 204, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [470, 447, 592, 551],
                "x": 527,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [792, 247, 911, 339],
                "x": 850,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [558, 156, 673, 258],
                "x": 613,
                "y": 259,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [502, 187, 619, 297],
                "x": 561,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [239, 455, 357, 564],
                "x": 298,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [817, 231, 933, 334],
                "x": 875,
                "y": 334,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 316, "y": 326, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [325, 361, 446, 461],
                "x": 382,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [308, 128, 436, 230],
                "x": 373,
                "y": 227,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [931, 117, 1051, 212],
                "x": 993,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [442, 435, 561, 542],
                "x": 500,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [835, 164, 958, 264],
                "x": 900,
                "y": 266,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [534, 162, 646, 261],
                "x": 590,
                "y": 260,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 537, "y": 306, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [235, 476, 352, 581],
                "x": 296,
                "y": 576,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 868, "y": 348, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [244, 207, 365, 309],
                "x": 306,
                "y": 310,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 404, "y": 432, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 338, "y": 249, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 994, "y": 229, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 472, "y": 527, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 950, "y": 167, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 568, "y": 261, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [451, 218, 568, 315],
                "x": 512,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [229, 488, 351, 593],
                "x": 294,
                "y": 591,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [803, 264, 926, 364],
                "x": 861,
                "y": 363,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [236, 196, 355, 299],
                "x": 295,
                "y": 295,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [370, 300, 484, 407],
                "x": 425,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [239, 179, 359, 279],
                "x": 303,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [938, 145, 1056, 240],
                "x": 994,
                "y": 241,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 444, "y": 515, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 1000, "y": 45, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [489, 162, 601, 258],
                "x": 545,
                "y": 263,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [425, 222, 552, 326],
                "x": 488,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [229, 499, 355, 603],
                "x": 292,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [795, 274, 916, 376],
                "x": 854,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [229, 184, 345, 279],
                "x": 285,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [390, 269, 511, 372],
                "x": 446,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [209, 234, 334, 325],
                "x": 269,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [930, 150, 1052, 257],
                "x": 994,
                "y": 253,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 416, "y": 503, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 522, "y": 266, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 464, "y": 328, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 289, "y": 615, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [785, 299, 911, 392],
                "x": 847,
                "y": 394,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [215, 171, 337, 273],
                "x": 275,
                "y": 270,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [411, 237, 529, 345],
                "x": 468,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [170, 292, 295, 393],
                "x": 234,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [934, 161, 1050, 266],
                "x": 994,
                "y": 266,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [325, 387, 445, 492],
                "x": 388,
                "y": 491,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 500, "y": 270, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [380, 222, 498, 325],
                "x": 439,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [227, 521, 350, 624],
                "x": 287,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [784, 312, 896, 413],
                "x": 840,
                "y": 410,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 265, "y": 259, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [433, 209, 545, 304],
                "x": 489,
                "y": 308,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 199, "y": 467, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [935, 173, 1058, 275],
                "x": 994,
                "y": 278,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [305, 385, 419, 486],
                "x": 361,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [420, 174, 535, 272],
                "x": 477,
                "y": 274,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [359, 221, 473, 319],
                "x": 415,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [227, 528, 341, 628],
                "x": 285,
                "y": 631,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 833, "y": 426, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [196, 155, 316, 246],
                "x": 255,
                "y": 250,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [455, 174, 573, 271],
                "x": 510,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [106, 464, 227, 558],
                "x": 164,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [935, 189, 1055, 285],
                "x": 995,
                "y": 290,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 333, "y": 471, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [389, 181, 509, 279],
                "x": 454,
                "y": 279,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 391, "y": 302, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [227, 538, 343, 637],
                "x": 283,
                "y": 636,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 826, "y": 443, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [180, 148, 300, 243],
                "x": 244,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [471, 150, 591, 240],
                "x": 531,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [64, 565, 190, 671],
                "x": 129,
                "y": 670,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [931, 206, 1052, 300],
                "x": 995,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [249, 366, 367, 463],
                "x": 305,
                "y": 464,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [375, 188, 486, 288],
                "x": 431,
                "y": 286,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [305, 179, 422, 273],
                "x": 366,
                "y": 278,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [221, 544, 337, 634],
                "x": 281,
                "y": 639,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [755, 357, 876, 454],
                "x": 819,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [170, 136, 291, 233],
                "x": 234,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [493, 113, 608, 215],
                "x": 553,
                "y": 216,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 95, "y": 800, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [930, 210, 1053, 320],
                "x": 995,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [215, 361, 333, 454],
                "x": 277,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [347, 198, 471, 288],
                "x": 409,
                "y": 293,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [287, 145, 402, 242],
                "x": 342,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [215, 535, 341, 643],
                "x": 279,
                "y": 640,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [751, 372, 877, 479],
                "x": 812,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [163, 132, 288, 236],
                "x": 224,
                "y": 233,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [517, 91, 633, 187],
                "x": 574,
                "y": 187,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 995, "y": 327, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 250, "y": 454, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [322, 203, 449, 305],
                "x": 386,
                "y": 301,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [261, 98, 374, 206],
                "x": 318,
                "y": 201,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [221, 539, 333, 640],
                "x": 276,
                "y": 638,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [745, 397, 865, 497],
                "x": 805,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [157, 129, 269, 229],
                "x": 214,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [537, 63, 655, 160],
                "x": 595,
                "y": 161,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [933, 245, 1053, 345],
                "x": 995,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [157, 353, 278, 456],
                "x": 222,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [301, 205, 420, 310],
                "x": 363,
                "y": 310,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 293, "y": 146, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [218, 539, 336, 636],
                "x": 274,
                "y": 634,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [740, 406, 863, 506],
                "x": 798,
                "y": 510,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [140, 132, 260, 228],
                "x": 204,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [555, 34, 679, 133],
                "x": 617,
                "y": 137,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [936, 253, 1051, 354],
                "x": 996,
                "y": 352,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 194, "y": 454, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [275, 219, 398, 317],
                "x": 340,
                "y": 320,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [212, -21, 325, 77],
                "x": 269,
                "y": 79,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [209, 524, 336, 624],
                "x": 272,
                "y": 628,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [728, 422, 850, 527],
                "x": 791,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [133, 129, 256, 230],
                "x": 193,
                "y": 232,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 638, "y": 115, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [934, 266, 1051, 365],
                "x": 996,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [105, 361, 230, 462],
                "x": 166,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [254, 233, 376, 334],
                "x": 318,
                "y": 331,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 245, "y": 0, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [206, 519, 329, 619],
                "x": 270,
                "y": 619,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [728, 446, 845, 539],
                "x": 784,
                "y": 544,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 183, "y": 235, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [601, -4, 720, 102],
                "x": 659,
                "y": 97,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [938, 281, 1057, 376],
                "x": 996,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [76, 365, 201, 466],
                "x": 138,
                "y": 467,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [233, 248, 350, 345],
                "x": 295,
                "y": 344,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [212, 510, 326, 606],
                "x": 268,
                "y": 608,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [717, 463, 834, 556],
                "x": 777,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [109, 144, 231, 242],
                "x": 173,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [621, -22, 742, 87],
                "x": 680,
                "y": 82,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 996, "y": 390, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [47, 380, 167, 474],
                "x": 111,
                "y": 478,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 272, "y": 357, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [204, 492, 328, 590],
                "x": 265,
                "y": 595,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [714, 477, 831, 582],
                "x": 771,
                "y": 577,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 163, "y": 247, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [640, -25, 766, 70],
                "x": 702,
                "y": 72,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 997, "y": 402, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [23, 397, 143, 494],
                "x": 83,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [194, 268, 314, 372],
                "x": 250,
                "y": 372,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [201, 474, 321, 578],
                "x": 263,
                "y": 579,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [702, 490, 828, 598],
                "x": 764,
                "y": 594,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [88, 160, 210, 259],
                "x": 153,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [661, -37, 782, 70],
                "x": 723,
                "y": 65,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [937, 319, 1058, 417],
                "x": 997,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-9, 413, 118, 514],
                "x": 55,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [164, 288, 291, 391],
                "x": 227,
                "y": 388,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [205, 457, 317, 555],
                "x": 261,
                "y": 560,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 757, "y": 610, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [77, 172, 206, 266],
                "x": 142,
                "y": 267,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 744, "y": 64, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [939, 323, 1061, 426],
                "x": 997,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-32, 442, 84, 538],
                "x": 27,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [140, 303, 267, 403],
                "x": 204,
                "y": 405,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [204, 444, 317, 534],
                "x": 259,
                "y": 539,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 750, "y": 626, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [72, 175, 189, 278],
                "x": 132,
                "y": 280,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 765, "y": 68, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [939, 339, 1054, 441],
                "x": 997,
                "y": 440,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-65, 475, 57, 575],
                "x": 0,
                "y": 570,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [122, 325, 245, 421],
                "x": 181,
                "y": 424,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 257, "y": 515, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 743, "y": 642, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [60, 195, 178, 291],
                "x": 122,
                "y": 295,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [725, -27, 850, 79],
                "x": 787,
                "y": 78,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [941, 354, 1053, 457],
                "x": 997,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [100, 339, 214, 439],
                "x": 159,
                "y": 444,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 255, "y": 488, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [671, 559, 795, 653],
                "x": 736,
                "y": 658,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [50, 214, 175, 314],
                "x": 112,
                "y": 313,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 808, "y": 93, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [941, 366, 1053, 466],
                "x": 998,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [80, 369, 200, 463],
                "x": 136,
                "y": 466,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [197, 358, 307, 454],
                "x": 252,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [671, 572, 791, 676],
                "x": 729,
                "y": 673,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 102, "y": 332, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 829, "y": 116, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 998, "y": 478, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [49, 394, 177, 486],
                "x": 113,
                "y": 489,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 250, "y": 426, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [667, 591, 778, 685],
                "x": 722,
                "y": 688,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [28, 252, 151, 350],
                "x": 91,
                "y": 354,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 851, "y": 145, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 998, "y": 490, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 90, "y": 513, "track_id": None},
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [190, 289, 311, 395],
                "x": 248,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [650, 598, 777, 702],
                "x": 715,
                "y": 702,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [25, 279, 136, 377],
                "x": 81,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [809, 87, 929, 181],
                "x": 872,
                "y": 182,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [937, 398, 1063, 508],
                "x": 998,
                "y": 503,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [12, 444, 124, 543],
                "x": 68,
                "y": 539,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 246, "y": 353, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [649, 611, 767, 715],
                "x": 708,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [9, 303, 129, 400],
                "x": 71,
                "y": 405,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [828, 124, 953, 226],
                "x": 893,
                "y": 226,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 998, "y": 516, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-14, 466, 107, 563],
                "x": 45,
                "y": 567,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [179, 208, 304, 312],
                "x": 244,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [645, 635, 756, 729],
                "x": 701,
                "y": 730,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 61, "y": 434, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [850, 178, 977, 277],
                "x": 914,
                "y": 279,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 999, "y": 528, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-38, 492, 87, 597],
                "x": 22,
                "y": 596,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [186, 168, 303, 265],
                "x": 241,
                "y": 267,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 694, "y": 743, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-11, 365, 112, 462],
                "x": 51,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [873, 244, 993, 344],
                "x": 936,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [942, 438, 1060, 541],
                "x": 999,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-65, 531, 58, 623],
                "x": 0,
                "y": 627,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 239, "y": 220, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [627, 654, 751, 759],
                "x": 687,
                "y": 756,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-23, 396, 102, 503],
                "x": 40,
                "y": 499,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 957, "y": 411, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [940, 450, 1064, 551],
                "x": 999,
                "y": 554,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [178, 73, 296, 170],
                "x": 237,
                "y": 170,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 680, "y": 768, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-25, 431, 92, 537],
                "x": 30,
                "y": 535,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 978, "y": 491, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [943, 463, 1063, 563],
                "x": 999,
                "y": 567,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [179, 18, 298, 117],
                "x": 235,
                "y": 116,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [618, 679, 732, 777],
                "x": 673,
                "y": 779,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 20, "y": 574, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [945, 481, 1065, 580],
                "x": 1000,
                "y": 581,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 1000, "y": 580, "track_id": None},
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 233, "y": 60, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [608, 688, 721, 791],
                "x": 666,
                "y": 790,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-51, 511, 75, 620],
                "x": 10,
                "y": 615,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [172, -101, 287, 2],
                "x": 231,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [600, 698, 721, 804],
                "x": 660,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 0, "y": 660, "track_id": None},
        ],
    },
]
