country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-52, 211, 63, 311],
                "x": 0,
                "y": 316,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-67, 696, 64, 792],
                "x": 0,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-64, -2, 62, 94],
                "x": 0,
                "y": 104,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-60, 10, 59, 110],
                "x": 0,
                "y": 108,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [85, 690, 216, 798],
                "x": 147,
                "y": 799,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-52, 236, 66, 332],
                "x": 3,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-17, 635, 89, 722],
                "x": 38,
                "y": 727,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-33, 10, 84, 101],
                "x": 20,
                "y": 105,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-49, -9, 67, 81],
                "x": 11,
                "y": 84,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [115, 631, 232, 729],
                "x": 171,
                "y": 722,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-46, 254, 64, 358],
                "x": 6,
                "y": 357,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [9, 566, 127, 662],
                "x": 76,
                "y": 662,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-10, 4, 108, 99],
                "x": 40,
                "y": 107,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-38, -24, 79, 70],
                "x": 23,
                "y": 68,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [140, 561, 246, 649],
                "x": 195,
                "y": 654,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-45, 286, 69, 384],
                "x": 9,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [51, 507, 174, 605],
                "x": 115,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-8, 2, 117, 115],
                "x": 61,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-33, -39, 105, 59],
                "x": 35,
                "y": 57,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [168, 495, 279, 590],
                "x": 220,
                "y": 595,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 12, "y": 396, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [96, 453, 216, 551],
                "x": 153,
                "y": 555,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [17, 22, 147, 109],
                "x": 81,
                "y": 114,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-14, -53, 105, 52],
                "x": 47,
                "y": 53,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [181, 440, 314, 541],
                "x": 244,
                "y": 545,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-51, 309, 82, 425],
                "x": 16,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [124, 408, 258, 512],
                "x": 192,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [48, 14, 156, 116],
                "x": 102,
                "y": 119,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-7, -45, 126, 51],
                "x": 59,
                "y": 55,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [211, 403, 334, 509],
                "x": 268,
                "y": 502,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-31, 332, 87, 443],
                "x": 19,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [171, 381, 292, 468],
                "x": 230,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [56, 28, 183, 134],
                "x": 122,
                "y": 125,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [3, -38, 131, 64],
                "x": 71,
                "y": 63,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [239, 358, 357, 470],
                "x": 293,
                "y": 466,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-46, 347, 92, 441],
                "x": 22,
                "y": 451,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 269, "y": 445, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [81, 24, 194, 136],
                "x": 142,
                "y": 132,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [16, -24, 139, 79],
                "x": 83,
                "y": 75,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [254, 333, 370, 446],
                "x": 317,
                "y": 437,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-37, 372, 87, 458],
                "x": 25,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [247, 328, 364, 410],
                "x": 307,
                "y": 419,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [112, 39, 231, 134],
                "x": 163,
                "y": 139,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [27, 1, 148, 93],
                "x": 95,
                "y": 93,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [289, 317, 404, 423],
                "x": 341,
                "y": 414,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-26, 391, 92, 477],
                "x": 28,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [290, 292, 410, 402],
                "x": 346,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [131, 55, 243, 141],
                "x": 183,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [50, 8, 160, 112],
                "x": 106,
                "y": 115,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [302, 305, 432, 398],
                "x": 366,
                "y": 397,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 32, "y": 501, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [327, 282, 441, 374],
                "x": 384,
                "y": 381,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [152, 46, 260, 145],
                "x": 204,
                "y": 155,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [59, 52, 175, 149],
                "x": 118,
                "y": 142,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [328, 281, 455, 388],
                "x": 390,
                "y": 385,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 35, "y": 517, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [372, 269, 492, 375],
                "x": 423,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [167, 65, 274, 166],
                "x": 224,
                "y": 164,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [66, 77, 182, 182],
                "x": 130,
                "y": 173,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [351, 267, 470, 370],
                "x": 415,
                "y": 377,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-18, 423, 89, 535],
                "x": 38,
                "y": 532,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [407, 261, 524, 354],
                "x": 461,
                "y": 357,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [182, 76, 314, 179],
                "x": 244,
                "y": 173,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [90, 115, 199, 202],
                "x": 142,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [385, 278, 493, 380],
                "x": 439,
                "y": 373,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-15, 457, 94, 540],
                "x": 41,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [447, 257, 565, 342],
                "x": 500,
                "y": 349,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [203, 91, 319, 189],
                "x": 265,
                "y": 183,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [104, 153, 210, 254],
                "x": 154,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [400, 265, 517, 380],
                "x": 463,
                "y": 372,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-25, 461, 95, 567],
                "x": 44,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [469, 248, 604, 333],
                "x": 538,
                "y": 343,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 285, "y": 192, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [106, 182, 236, 288],
                "x": 166,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [432, 282, 558, 379],
                "x": 488,
                "y": 374,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-10, 483, 106, 570],
                "x": 48,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [523, 238, 632, 342],
                "x": 576,
                "y": 338,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [252, 110, 359, 192],
                "x": 306,
                "y": 202,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [127, 227, 232, 329],
                "x": 178,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [454, 270, 580, 372],
                "x": 512,
                "y": 378,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-6, 491, 101, 582],
                "x": 51,
                "y": 589,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [548, 224, 683, 343],
                "x": 615,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [275, 111, 391, 203],
                "x": 326,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [124, 273, 243, 384],
                "x": 190,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [470, 289, 599, 383],
                "x": 536,
                "y": 384,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [0, 503, 119, 610],
                "x": 54,
                "y": 603,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [600, 233, 711, 341],
                "x": 653,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [284, 127, 397, 218],
                "x": 346,
                "y": 222,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [139, 328, 265, 418],
                "x": 201,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [503, 281, 626, 385],
                "x": 561,
                "y": 391,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-5, 517, 124, 621],
                "x": 57,
                "y": 615,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [639, 227, 760, 336],
                "x": 692,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [306, 136, 429, 226],
                "x": 367,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [163, 368, 266, 465],
                "x": 213,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [526, 291, 649, 388],
                "x": 585,
                "y": 398,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-7, 526, 117, 635],
                "x": 60,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [679, 229, 791, 323],
                "x": 730,
                "y": 324,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 387, "y": 241, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [163, 432, 289, 524],
                "x": 225,
                "y": 526,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [558, 310, 674, 406],
                "x": 610,
                "y": 405,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [12, 529, 118, 639],
                "x": 64,
                "y": 639,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 769, "y": 318, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [358, 153, 463, 255],
                "x": 408,
                "y": 250,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 237, "y": 580, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [584, 308, 684, 411],
                "x": 634,
                "y": 411,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [4, 544, 126, 660],
                "x": 67,
                "y": 651,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 807, "y": 311, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [370, 154, 492, 263],
                "x": 428,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [191, 530, 299, 634],
                "x": 249,
                "y": 634,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [588, 307, 713, 425],
                "x": 658,
                "y": 416,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [15, 553, 140, 665],
                "x": 70,
                "y": 662,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [782, 193, 899, 299],
                "x": 846,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [390, 178, 513, 266],
                "x": 448,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [200, 595, 316, 698],
                "x": 261,
                "y": 689,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [618, 326, 740, 421],
                "x": 683,
                "y": 420,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [13, 568, 125, 669],
                "x": 73,
                "y": 672,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [818, 188, 951, 296],
                "x": 884,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [417, 169, 520, 282],
                "x": 469,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [222, 640, 340, 754],
                "x": 273,
                "y": 744,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 707, "y": 421, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [16, 574, 139, 680],
                "x": 77,
                "y": 682,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [870, 165, 992, 271],
                "x": 923,
                "y": 275,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [425, 187, 559, 293],
                "x": 489,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [223, 698, 345, 806],
                "x": 285,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [664, 316, 795, 419],
                "x": 731,
                "y": 419,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [17, 595, 150, 688],
                "x": 80,
                "y": 692,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [907, 160, 1021, 247],
                "x": 961,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [442, 190, 573, 295],
                "x": 510,
                "y": 291,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 756, "y": 413, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [16, 600, 153, 708],
                "x": 83,
                "y": 701,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [944, 127, 1051, 240],
                "x": 1000,
                "y": 232,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [476, 187, 583, 298],
                "x": 530,
                "y": 297,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [728, 294, 830, 409],
                "x": 780,
                "y": 404,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [30, 618, 142, 717],
                "x": 86,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [481, 206, 604, 302],
                "x": 551,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [742, 282, 875, 400],
                "x": 805,
                "y": 390,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [29, 608, 146, 723],
                "x": 89,
                "y": 718,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [512, 216, 625, 297],
                "x": 571,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [778, 268, 885, 370],
                "x": 829,
                "y": 370,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [43, 629, 152, 722],
                "x": 93,
                "y": 726,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [540, 217, 653, 317],
                "x": 591,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [795, 254, 923, 355],
                "x": 853,
                "y": 345,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [42, 624, 161, 741],
                "x": 96,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [543, 205, 679, 310],
                "x": 612,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [824, 206, 947, 318],
                "x": 878,
                "y": 314,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [48, 636, 154, 747],
                "x": 99,
                "y": 741,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [562, 207, 699, 306],
                "x": 632,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [847, 171, 972, 270],
                "x": 902,
                "y": 275,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 102, "y": 748, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [597, 211, 712, 320],
                "x": 653,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [861, 139, 976, 227],
                "x": 926,
                "y": 229,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [51, 651, 167, 763],
                "x": 105,
                "y": 755,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [617, 209, 730, 309],
                "x": 673,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [899, 84, 1016, 180],
                "x": 951,
                "y": 176,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [50, 655, 170, 753],
                "x": 109,
                "y": 761,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [632, 212, 751, 319],
                "x": 693,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [906, 16, 1039, 112],
                "x": 975,
                "y": 113,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [60, 674, 170, 767],
                "x": 112,
                "y": 766,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 714, "y": 309, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [942, -64, 1051, 36],
                "x": 1000,
                "y": 41,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [63, 679, 171, 770],
                "x": 115,
                "y": 772,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [669, 202, 793, 307],
                "x": 734,
                "y": 304,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [52, 673, 173, 777],
                "x": 118,
                "y": 777,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [699, 189, 810, 298],
                "x": 755,
                "y": 297,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [71, 684, 181, 774],
                "x": 121,
                "y": 781,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [706, 185, 830, 291],
                "x": 775,
                "y": 289,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [75, 696, 193, 777],
                "x": 125,
                "y": 786,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [745, 183, 851, 277],
                "x": 795,
                "y": 279,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [73, 688, 184, 780],
                "x": 128,
                "y": 790,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [752, 163, 883, 273],
                "x": 816,
                "y": 268,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [61, 694, 181, 803],
                "x": 131,
                "y": 793,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [786, 144, 896, 255],
                "x": 836,
                "y": 254,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [65, 701, 198, 802],
                "x": 134,
                "y": 797,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [790, 143, 908, 242],
                "x": 857,
                "y": 239,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [73, 710, 206, 801],
                "x": 138,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [810, 124, 941, 214],
                "x": 877,
                "y": 221,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [828, 98, 952, 199],
                "x": 897,
                "y": 202,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [855, 84, 976, 190],
                "x": 918,
                "y": 180,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 938, "y": 156, "track_id": None}
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [905, 30, 1009, 137],
                "x": 959,
                "y": 130,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [928, 4, 1032, 107],
                "x": 979,
                "y": 102,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [931, -23, 1052, 64],
                "x": 1000,
                "y": 71,
                "track_id": None,
            }
        ],
    },
]
