country_balls_amount = 15
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [939, 570, 1059, 668],
                "x": 1000,
                "y": 669,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [447, -101, 570, 0],
                "x": 508,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 731, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [939, 96, 1061, 196],
                "x": 1000,
                "y": 195,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [942, 467, 1058, 567],
                "x": 1000,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [790, -102, 908, -1],
                "x": 848,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [941, -94, 1062, 5],
                "x": 1000,
                "y": 6,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [938, 694, 1058, 797],
                "x": 1000,
                "y": 795,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 0, "y": 174, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-60, 135, 60, 238],
                "x": 0,
                "y": 236,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [-58, -23, 58, 78],
                "x": 0,
                "y": 78,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 1000, "y": 414, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 946, "y": 799, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [848, 698, 972, 801],
                "x": 910,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [788, -100, 911, 1],
                "x": 849,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [913, 545, 1030, 644],
                "x": 971,
                "y": 645,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 508, "y": 15, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 961, "y": 707, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [911, 157, 1031, 256],
                "x": 969,
                "y": 255,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [936, 481, 1055, 582],
                "x": 996,
                "y": 580,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 816, "y": 121, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [898, -55, 1015, 49],
                "x": 956,
                "y": 47,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [928, 615, 1048, 718],
                "x": 990,
                "y": 717,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-38, 118, 80, 219],
                "x": 22,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-37, 173, 84, 274],
                "x": 25,
                "y": 274,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 25, "y": 116, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [906, 302, 1026, 404],
                "x": 968,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [885, 686, 1005, 786],
                "x": 947,
                "y": 786,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 876, "y": 739, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [792, -97, 910, 3],
                "x": 852,
                "y": 1,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [882, 524, 1003, 623],
                "x": 942,
                "y": 623,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [449, -70, 567, 29],
                "x": 509,
                "y": 31,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 923, "y": 683, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 939, "y": 309, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [931, 496, 1054, 595],
                "x": 992,
                "y": 595,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [725, 120, 843, 221],
                "x": 785,
                "y": 222,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [851, -14, 973, 87],
                "x": 913,
                "y": 86,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [920, 544, 1041, 642],
                "x": 981,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-15, 158, 105, 259],
                "x": 44,
                "y": 260,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 51, "y": 309, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 50, "y": 153, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [875, 294, 997, 398],
                "x": 937,
                "y": 396,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 949, "y": 772, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [780, 579, 904, 683],
                "x": 842,
                "y": 681,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [795, -99, 915, 2],
                "x": 855,
                "y": 2,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [855, 504, 975, 601],
                "x": 914,
                "y": 603,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [451, -54, 569, 47],
                "x": 509,
                "y": 46,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [823, 558, 943, 659],
                "x": 884,
                "y": 658,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [850, 254, 968, 355],
                "x": 909,
                "y": 355,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 988, "y": 609, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 753, "y": 304, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [807, 24, 931, 124],
                "x": 869,
                "y": 124,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 971, "y": 577, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [8, 197, 124, 299],
                "x": 66,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [14, 240, 137, 341],
                "x": 76,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [15, 90, 136, 189],
                "x": 76,
                "y": 189,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [845, 293, 966, 391],
                "x": 906,
                "y": 391,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 951, "y": 757, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [746, 526, 869, 627],
                "x": 808,
                "y": 625,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [796, -98, 919, 6],
                "x": 858,
                "y": 4,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [827, 486, 943, 586],
                "x": 885,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [451, -40, 571, 64],
                "x": 510,
                "y": 62,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 846, "y": 632, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [819, 294, 936, 393],
                "x": 878,
                "y": 394,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [923, 522, 1043, 621],
                "x": 984,
                "y": 623,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 722, "y": 368, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [765, 58, 884, 158],
                "x": 826,
                "y": 160,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 962, "y": 516, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [30, 237, 150, 335],
                "x": 88,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [44, 268, 161, 370],
                "x": 102,
                "y": 368,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 101, "y": 222, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 875, "y": 388, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 953, "y": 742, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 775, "y": 572, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [802, -94, 923, 6],
                "x": 861,
                "y": 7,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 857, "y": 567, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [451, -24, 570, 77],
                "x": 510,
                "y": 78,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [749, 506, 867, 604],
                "x": 807,
                "y": 606,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [786, 328, 908, 426],
                "x": 848,
                "y": 427,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 980, "y": 636, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [629, 315, 749, 415],
                "x": 690,
                "y": 416,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 782, "y": 193, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [892, 360, 1010, 459],
                "x": 952,
                "y": 461,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 111, "y": 371, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 128, "y": 392, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [65, 153, 187, 255],
                "x": 126,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [784, 288, 904, 387],
                "x": 843,
                "y": 387,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 955, "y": 727, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [681, 424, 799, 523],
                "x": 741,
                "y": 523,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [803, -90, 926, 10],
                "x": 865,
                "y": 10,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [768, 453, 886, 554],
                "x": 828,
                "y": 552,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [452, -7, 570, 94],
                "x": 511,
                "y": 94,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 769, "y": 580, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [758, 357, 878, 455],
                "x": 818,
                "y": 455,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [918, 548, 1037, 651],
                "x": 976,
                "y": 649,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [598, 350, 718, 452],
                "x": 659,
                "y": 450,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [681, 125, 800, 227],
                "x": 739,
                "y": 225,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 943, "y": 411, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [73, 303, 195, 403],
                "x": 133,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [94, 311, 215, 413],
                "x": 153,
                "y": 413,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [92, 185, 211, 285],
                "x": 152,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [752, 287, 871, 386],
                "x": 812,
                "y": 388,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 957, "y": 711, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [649, 377, 769, 477],
                "x": 707,
                "y": 477,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 868, "y": 13, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [738, 436, 860, 538],
                "x": 800,
                "y": 537,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [453, 8, 573, 108],
                "x": 511,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [670, 457, 792, 557],
                "x": 730,
                "y": 555,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 787, "y": 477, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [912, 564, 1030, 661],
                "x": 972,
                "y": 662,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [568, 370, 688, 470],
                "x": 628,
                "y": 470,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [633, 153, 753, 252],
                "x": 695,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [871, 268, 991, 368],
                "x": 933,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [93, 330, 216, 433],
                "x": 155,
                "y": 432,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [117, 333, 238, 433],
                "x": 179,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [119, 213, 239, 313],
                "x": 177,
                "y": 311,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 781, "y": 391, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [901, 595, 1017, 697],
                "x": 959,
                "y": 695,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 674, "y": 434, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [809, -82, 932, 19],
                "x": 871,
                "y": 17,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [713, 423, 831, 522],
                "x": 771,
                "y": 524,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [451, 28, 572, 127],
                "x": 512,
                "y": 126,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [632, 431, 750, 532],
                "x": 692,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [699, 394, 816, 495],
                "x": 757,
                "y": 494,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 968, "y": 674, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [537, 378, 658, 481],
                "x": 596,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [593, 178, 712, 281],
                "x": 652,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [862, 228, 984, 326],
                "x": 924,
                "y": 327,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [118, 361, 238, 458],
                "x": 177,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [147, 345, 267, 446],
                "x": 205,
                "y": 446,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [141, 237, 263, 337],
                "x": 203,
                "y": 337,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 750, "y": 395, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 960, "y": 678, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 640, "y": 395, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [816, -80, 932, 23],
                "x": 874,
                "y": 21,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [682, 413, 801, 513],
                "x": 742,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [450, 42, 573, 145],
                "x": 512,
                "y": 143,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [592, 410, 714, 509],
                "x": 653,
                "y": 509,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [668, 408, 788, 508],
                "x": 727,
                "y": 507,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 964, "y": 685, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [507, 377, 625, 476],
                "x": 565,
                "y": 477,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 608, "y": 301, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [853, 194, 972, 295],
                "x": 914,
                "y": 293,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [139, 386, 259, 486],
                "x": 200,
                "y": 485,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 230, "y": 459, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [170, 262, 286, 360],
                "x": 228,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [660, 304, 778, 400],
                "x": 718,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [904, 563, 1021, 661],
                "x": 962,
                "y": 661,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [546, 263, 666, 363],
                "x": 606,
                "y": 361,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [816, -75, 937, 24],
                "x": 877,
                "y": 26,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [656, 400, 772, 500],
                "x": 714,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [454, 59, 572, 161],
                "x": 513,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [557, 390, 675, 489],
                "x": 615,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 696, "y": 515, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [898, 598, 1019, 695],
                "x": 960,
                "y": 696,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 533, "y": 466, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 565, "y": 320, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [846, 163, 967, 264],
                "x": 905,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [164, 407, 283, 509],
                "x": 222,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [194, 371, 316, 471],
                "x": 256,
                "y": 470,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [195, 281, 315, 381],
                "x": 253,
                "y": 380,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [625, 308, 746, 410],
                "x": 687,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [906, 542, 1025, 642],
                "x": 964,
                "y": 643,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [512, 230, 633, 330],
                "x": 572,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [822, -67, 941, 33],
                "x": 881,
                "y": 31,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [625, 394, 745, 492],
                "x": 685,
                "y": 492,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 513, "y": 175, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [518, 373, 635, 473],
                "x": 576,
                "y": 471,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [605, 418, 728, 522],
                "x": 666,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [899, 607, 1016, 706],
                "x": 957,
                "y": 707,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [444, 346, 560, 446],
                "x": 502,
                "y": 448,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [460, 233, 581, 337],
                "x": 521,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [834, 137, 955, 239],
                "x": 895,
                "y": 239,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 244, "y": 528, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [221, 378, 343, 480],
                "x": 282,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [220, 297, 337, 397],
                "x": 279,
                "y": 399,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [597, 318, 718, 417],
                "x": 656,
                "y": 418,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [904, 526, 1028, 624],
                "x": 966,
                "y": 625,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [481, 208, 600, 306],
                "x": 539,
                "y": 306,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 884, "y": 37, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [597, 384, 716, 486],
                "x": 657,
                "y": 484,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [452, 90, 572, 191],
                "x": 514,
                "y": 192,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [476, 354, 597, 454],
                "x": 538,
                "y": 455,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 636, "y": 522, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [892, 620, 1015, 720],
                "x": 953,
                "y": 718,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [409, 323, 532, 425],
                "x": 471,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [417, 248, 537, 346],
                "x": 478,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [826, 117, 948, 220],
                "x": 886,
                "y": 218,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 266, "y": 547, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 307, "y": 485, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [243, 314, 362, 413],
                "x": 304,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [564, 330, 687, 429],
                "x": 625,
                "y": 428,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [907, 506, 1029, 607],
                "x": 968,
                "y": 607,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 505, "y": 286, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [826, -59, 945, 43],
                "x": 887,
                "y": 43,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [566, 377, 687, 477],
                "x": 628,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [453, 107, 574, 211],
                "x": 514,
                "y": 209,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 500, "y": 443, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [547, 420, 665, 520],
                "x": 606,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [888, 628, 1009, 726],
                "x": 949,
                "y": 728,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [377, 296, 500, 393],
                "x": 439,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [374, 253, 493, 355],
                "x": 434,
                "y": 353,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 876, "y": 202, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [226, 462, 347, 564],
                "x": 288,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [274, 390, 395, 491],
                "x": 333,
                "y": 490,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 329, "y": 427, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [532, 339, 652, 441],
                "x": 593,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [910, 486, 1029, 590],
                "x": 970,
                "y": 588,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [409, 170, 529, 271],
                "x": 471,
                "y": 271,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [831, -52, 948, 50],
                "x": 890,
                "y": 50,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [542, 372, 659, 468],
                "x": 600,
                "y": 470,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 515, "y": 226, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [399, 337, 523, 437],
                "x": 461,
                "y": 435,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [515, 419, 635, 518],
                "x": 575,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [887, 638, 1007, 739],
                "x": 945,
                "y": 737,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [350, 264, 469, 362],
                "x": 408,
                "y": 363,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [330, 256, 449, 357],
                "x": 391,
                "y": 355,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [808, 89, 928, 188],
                "x": 867,
                "y": 190,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [252, 475, 369, 577],
                "x": 311,
                "y": 577,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [297, 395, 420, 494],
                "x": 358,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [294, 335, 413, 437],
                "x": 355,
                "y": 436,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 562, "y": 451, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [912, 470, 1031, 570],
                "x": 972,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [380, 162, 496, 264],
                "x": 438,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [834, -41, 951, 58],
                "x": 893,
                "y": 57,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [513, 364, 633, 465],
                "x": 571,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [454, 142, 578, 243],
                "x": 516,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [363, 329, 483, 429],
                "x": 423,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [483, 410, 604, 514],
                "x": 545,
                "y": 512,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 941, "y": 746, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [318, 228, 434, 330],
                "x": 376,
                "y": 330,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 347, "y": 353, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [798, 81, 915, 183],
                "x": 857,
                "y": 182,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [274, 489, 391, 587],
                "x": 333,
                "y": 589,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 384, "y": 497, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [320, 342, 441, 441],
                "x": 380,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [472, 362, 593, 463],
                "x": 531,
                "y": 464,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 973, "y": 549, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [342, 158, 463, 257],
                "x": 404,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [835, -37, 955, 66],
                "x": 897,
                "y": 65,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [484, 362, 600, 462],
                "x": 542,
                "y": 461,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 516, "y": 259, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [323, 332, 444, 431],
                "x": 384,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [457, 408, 573, 507],
                "x": 515,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [879, 655, 999, 754],
                "x": 937,
                "y": 755,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [287, 195, 403, 296],
                "x": 345,
                "y": 296,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [245, 247, 364, 344],
                "x": 304,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [786, 76, 908, 176],
                "x": 848,
                "y": 178,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [297, 500, 417, 598],
                "x": 355,
                "y": 599,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [352, 398, 472, 499],
                "x": 410,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [348, 347, 464, 446],
                "x": 406,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [440, 375, 558, 479],
                "x": 500,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [914, 428, 1036, 531],
                "x": 975,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [311, 163, 432, 263],
                "x": 370,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [841, -25, 960, 72],
                "x": 900,
                "y": 74,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 514, "y": 457, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [457, 176, 578, 276],
                "x": 517,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [286, 335, 404, 434],
                "x": 346,
                "y": 435,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [422, 396, 543, 499],
                "x": 484,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [871, 665, 995, 763],
                "x": 933,
                "y": 763,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 314, "y": 263, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 260, "y": 334, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [776, 78, 899, 180],
                "x": 838,
                "y": 178,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [319, 509, 437, 608],
                "x": 377,
                "y": 608,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [373, 399, 494, 501],
                "x": 435,
                "y": 499,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 431, "y": 448, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [410, 389, 529, 490],
                "x": 468,
                "y": 490,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [919, 410, 1037, 511],
                "x": 977,
                "y": 509,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [278, 172, 398, 272],
                "x": 337,
                "y": 271,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [842, -17, 964, 83],
                "x": 903,
                "y": 82,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [426, 355, 546, 456],
                "x": 485,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [459, 192, 576, 295],
                "x": 517,
                "y": 294,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 307, "y": 445, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [392, 387, 515, 489],
                "x": 454,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [870, 670, 989, 769],
                "x": 929,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [223, 134, 344, 232],
                "x": 282,
                "y": 232,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 217, "y": 316, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 829, "y": 181, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 400, "y": 614, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [401, 402, 519, 502],
                "x": 461,
                "y": 500,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 456, "y": 445, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 437, "y": 504, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [920, 388, 1039, 486],
                "x": 979,
                "y": 488,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [244, 187, 363, 288],
                "x": 303,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [844, -7, 968, 93],
                "x": 906,
                "y": 92,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [395, 353, 519, 453],
                "x": 457,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [458, 210, 576, 309],
                "x": 518,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [211, 360, 331, 462],
                "x": 269,
                "y": 461,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [366, 381, 484, 481],
                "x": 424,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [865, 680, 984, 781],
                "x": 925,
                "y": 779,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [191, 104, 310, 206],
                "x": 251,
                "y": 206,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [115, 191, 232, 290],
                "x": 173,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [759, 86, 880, 189],
                "x": 819,
                "y": 187,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 422, "y": 618, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [425, 401, 549, 500],
                "x": 487,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [422, 340, 540, 439],
                "x": 482,
                "y": 439,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 406, "y": 518, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 981, "y": 466, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [210, 212, 328, 308],
                "x": 269,
                "y": 310,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [848, 3, 972, 103],
                "x": 910,
                "y": 102,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [366, 352, 490, 448],
                "x": 428,
                "y": 450,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [456, 230, 578, 330],
                "x": 518,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [172, 384, 291, 483],
                "x": 230,
                "y": 483,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [334, 372, 453, 474],
                "x": 393,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [861, 687, 979, 786],
                "x": 921,
                "y": 786,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [161, 84, 280, 186],
                "x": 219,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [69, 165, 191, 265],
                "x": 130,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [749, 94, 868, 194],
                "x": 810,
                "y": 196,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [382, 518, 502, 620],
                "x": 444,
                "y": 620,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [450, 398, 570, 498],
                "x": 512,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [445, 327, 566, 429],
                "x": 507,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [317, 433, 437, 531],
                "x": 375,
                "y": 532,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [922, 343, 1042, 442],
                "x": 983,
                "y": 444,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 235, "y": 340, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [854, 13, 972, 112],
                "x": 913,
                "y": 112,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [341, 350, 460, 448],
                "x": 400,
                "y": 450,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [458, 247, 579, 347],
                "x": 519,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [134, 411, 251, 512],
                "x": 192,
                "y": 511,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 363, "y": 465, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [856, 694, 979, 795],
                "x": 917,
                "y": 793,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [128, 69, 250, 171],
                "x": 188,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [28, 129, 144, 226],
                "x": 86,
                "y": 227,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 800, "y": 208, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [405, 521, 524, 621],
                "x": 466,
                "y": 621,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [477, 401, 599, 500],
                "x": 538,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [472, 314, 593, 414],
                "x": 532,
                "y": 416,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 343, "y": 546, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 985, "y": 422, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [140, 277, 264, 376],
                "x": 202,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [855, 23, 977, 125],
                "x": 916,
                "y": 124,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [310, 348, 432, 451],
                "x": 371,
                "y": 449,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 519, "y": 364, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [94, 445, 211, 545],
                "x": 153,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [275, 360, 391, 460],
                "x": 333,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [855, 698, 973, 802],
                "x": 914,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 157, "y": 166, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-17, 83, 105, 184],
                "x": 43,
                "y": 185,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 791, "y": 223, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [428, 518, 547, 617],
                "x": 488,
                "y": 619,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 564, "y": 500, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [500, 300, 619, 401],
                "x": 558,
                "y": 399,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [251, 461, 372, 561],
                "x": 312,
                "y": 559,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 986, "y": 399, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 168, "y": 424, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [857, 34, 978, 135],
                "x": 919,
                "y": 135,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 342, "y": 450, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [461, 280, 581, 381],
                "x": 520,
                "y": 382,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 115, "y": 589, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [241, 356, 365, 453],
                "x": 303,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [64, 71, 184, 172],
                "x": 125,
                "y": 170,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-58, 38, 60, 138],
                "x": 0,
                "y": 137,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [723, 140, 843, 240],
                "x": 781,
                "y": 240,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 511, "y": 616, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [527, 400, 650, 500],
                "x": 589,
                "y": 502,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 583, "y": 378, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 281, "y": 572, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [930, 276, 1048, 377],
                "x": 988,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [76, 376, 195, 478],
                "x": 134,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [861, 47, 983, 147],
                "x": 922,
                "y": 148,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [255, 352, 374, 452],
                "x": 314,
                "y": 450,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 520, "y": 399, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [17, 540, 135, 639],
                "x": 76,
                "y": 639,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [213, 349, 332, 449],
                "x": 272,
                "y": 451,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 94, "y": 185, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 772, "y": 260, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [475, 513, 591, 609],
                "x": 533,
                "y": 611,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 615, "y": 504, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 609, "y": 353, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [188, 485, 309, 585],
                "x": 250,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [928, 253, 1051, 354],
                "x": 990,
                "y": 352,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [40, 439, 159, 538],
                "x": 101,
                "y": 540,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [864, 61, 986, 158],
                "x": 926,
                "y": 160,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [223, 351, 343, 452],
                "x": 285,
                "y": 451,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [459, 319, 580, 418],
                "x": 521,
                "y": 417,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 38, "y": 698, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [180, 352, 301, 449],
                "x": 242,
                "y": 451,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [2, 114, 121, 215],
                "x": 62,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [701, 180, 821, 281],
                "x": 762,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [493, 503, 615, 603],
                "x": 555,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [581, 407, 703, 508],
                "x": 641,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [576, 223, 694, 325],
                "x": 634,
                "y": 324,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [160, 494, 277, 597],
                "x": 218,
                "y": 596,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 992, "y": 327, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 67, "y": 611, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [869, 76, 991, 176],
                "x": 929,
                "y": 174,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [195, 353, 317, 455],
                "x": 257,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [462, 338, 583, 438],
                "x": 521,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-59, 666, 58, 763],
                "x": 0,
                "y": 765,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 212, "y": 453, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 31, "y": 255, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [694, 207, 814, 308],
                "x": 753,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [519, 497, 639, 598],
                "x": 577,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [606, 410, 727, 510],
                "x": 666,
                "y": 511,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [597, 192, 720, 293],
                "x": 659,
                "y": 291,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 187, "y": 607, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [934, 203, 1053, 305],
                "x": 994,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-26, 591, 91, 689],
                "x": 33,
                "y": 691,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [874, 90, 992, 188],
                "x": 932,
                "y": 188,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [167, 355, 288, 454],
                "x": 228,
                "y": 455,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [461, 355, 580, 455],
                "x": 522,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [123, 357, 242, 457],
                "x": 181,
                "y": 459,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 0, "y": 313, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [683, 231, 805, 335],
                "x": 743,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [541, 489, 661, 587],
                "x": 600,
                "y": 587,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 692, "y": 517, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [624, 155, 745, 253],
                "x": 685,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [98, 514, 217, 617],
                "x": 156,
                "y": 616,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [936, 176, 1058, 277],
                "x": 996,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-60, 679, 58, 782],
                "x": 0,
                "y": 780,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [876, 100, 994, 201],
                "x": 935,
                "y": 202,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [142, 355, 261, 459],
                "x": 200,
                "y": 457,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 522, "y": 472, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [89, 368, 211, 471],
                "x": 151,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [673, 261, 796, 359],
                "x": 734,
                "y": 360,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 622, "y": 575, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [659, 426, 776, 522],
                "x": 717,
                "y": 524,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [650, 114, 772, 212],
                "x": 710,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [65, 527, 186, 627],
                "x": 125,
                "y": 625,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 998, "y": 252, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [880, 117, 997, 219],
                "x": 938,
                "y": 218,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 171, "y": 459, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 523, "y": 490, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [61, 381, 183, 485],
                "x": 121,
                "y": 483,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [665, 291, 784, 388],
                "x": 724,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [582, 462, 702, 560],
                "x": 644,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [683, 431, 805, 532],
                "x": 743,
                "y": 533,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [673, 64, 793, 166],
                "x": 735,
                "y": 166,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [34, 530, 155, 631],
                "x": 93,
                "y": 632,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [939, 124, 1058, 225],
                "x": 1000,
                "y": 225,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 942, "y": 234, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [81, 360, 204, 460],
                "x": 142,
                "y": 461,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 524, "y": 509, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [31, 403, 151, 503],
                "x": 90,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [654, 322, 773, 423],
                "x": 715,
                "y": 421,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 666, "y": 548, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 769, "y": 545, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [701, 17, 822, 114],
                "x": 761,
                "y": 115,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 62, "y": 637, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [885, 152, 1005, 251],
                "x": 945,
                "y": 250,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [56, 363, 175, 465],
                "x": 114,
                "y": 464,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [463, 428, 582, 527],
                "x": 524,
                "y": 527,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 60, "y": 525, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [644, 354, 766, 451],
                "x": 705,
                "y": 452,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 688, "y": 532, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [735, 457, 856, 558],
                "x": 794,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [726, -39, 845, 59],
                "x": 786,
                "y": 60,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 31, "y": 641, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [887, 167, 1010, 266],
                "x": 948,
                "y": 267,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [25, 367, 146, 466],
                "x": 85,
                "y": 466,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [466, 448, 585, 548],
                "x": 525,
                "y": 546,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 30, "y": 554, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 696, "y": 485, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [652, 413, 772, 516],
                "x": 711,
                "y": 515,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [761, 475, 879, 575],
                "x": 820,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [751, -100, 871, -2],
                "x": 812,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-60, 543, 59, 646],
                "x": 0,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [892, 186, 1010, 287],
                "x": 951,
                "y": 285,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-2, 369, 119, 469],
                "x": 57,
                "y": 469,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 525, "y": 565, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-58, 489, 60, 589],
                "x": 0,
                "y": 589,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [626, 420, 747, 519],
                "x": 686,
                "y": 519,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [673, 394, 791, 497],
                "x": 733,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [785, 492, 906, 595],
                "x": 846,
                "y": 594,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [897, 202, 1015, 303],
                "x": 955,
                "y": 303,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-34, 372, 90, 469],
                "x": 28,
                "y": 471,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 526, "y": 584, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [619, 456, 736, 556],
                "x": 677,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [697, 376, 814, 475],
                "x": 755,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [809, 516, 933, 615],
                "x": 871,
                "y": 617,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 958, "y": 322, "track_id": None},
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-58, 373, 62, 475],
                "x": 0,
                "y": 474,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [468, 502, 586, 601],
                "x": 526,
                "y": 603,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [608, 491, 726, 588],
                "x": 667,
                "y": 589,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 777, "y": 454, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [836, 543, 955, 640],
                "x": 897,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [903, 241, 1020, 344],
                "x": 961,
                "y": 342,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [465, 524, 585, 622],
                "x": 527,
                "y": 622,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [599, 526, 718, 624],
                "x": 658,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [738, 331, 858, 429],
                "x": 800,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [861, 573, 985, 672],
                "x": 923,
                "y": 671,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [905, 260, 1025, 363],
                "x": 964,
                "y": 362,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [469, 540, 588, 639],
                "x": 527,
                "y": 641,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [588, 559, 706, 658],
                "x": 648,
                "y": 659,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [764, 305, 881, 408],
                "x": 822,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [886, 603, 1010, 701],
                "x": 948,
                "y": 703,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [906, 285, 1028, 385],
                "x": 967,
                "y": 383,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [466, 563, 590, 661],
                "x": 528,
                "y": 661,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 639, "y": 695, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [783, 282, 902, 384],
                "x": 844,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [913, 642, 1032, 738],
                "x": 974,
                "y": 740,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 971, "y": 405, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 528, "y": 680, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [568, 630, 691, 730],
                "x": 629,
                "y": 730,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 866, "y": 355, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 1000, "y": 780, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [914, 329, 1033, 429],
                "x": 974,
                "y": 427,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 529, "y": 700, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [558, 663, 678, 766],
                "x": 620,
                "y": 765,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [829, 229, 946, 328],
                "x": 888,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [915, 352, 1039, 448],
                "x": 977,
                "y": 450,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [468, 620, 588, 720],
                "x": 529,
                "y": 720,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [550, 699, 670, 799],
                "x": 611,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [850, 198, 970, 298],
                "x": 911,
                "y": 299,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 980, "y": 474, "track_id": None},
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [469, 637, 592, 741],
                "x": 530,
                "y": 739,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [875, 167, 992, 271],
                "x": 933,
                "y": 269,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 983, "y": 499, "track_id": None},
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [471, 658, 590, 757],
                "x": 530,
                "y": 759,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 955, "y": 238, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [927, 424, 1047, 525],
                "x": 987,
                "y": 524,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [473, 681, 591, 779],
                "x": 531,
                "y": 779,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 977, "y": 206, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [932, 452, 1052, 552],
                "x": 990,
                "y": 550,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [470, 702, 590, 801],
                "x": 532,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 1000, "y": 173, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [933, 476, 1051, 578],
                "x": 993,
                "y": 576,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 14,
                "bounding_box": [936, 503, 1056, 603],
                "x": 996,
                "y": 603,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 14,
                "bounding_box": [939, 531, 1062, 630],
                "x": 1000,
                "y": 631,
                "track_id": None,
            }
        ],
    },
]
