country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-22, 699, 102, 802],
                "x": 40,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 463, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-59, 491, 62, 588],
                "x": 0,
                "y": 589,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 964, "y": 0, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 0, "y": 32, "track_id": None},
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 38, "y": 790, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 972, "y": 435, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 8, "y": 558, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 965, "y": 11, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [-29, -50, 90, 51],
                "x": 31,
                "y": 49,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 37, "y": 781, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 945, "y": 408, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 16, "y": 528, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 966, "y": 22, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 62, "y": 73, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-23, 673, 95, 771],
                "x": 36,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [858, 286, 976, 386],
                "x": 918,
                "y": 384,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 24, "y": 498, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [905, -66, 1026, 32],
                "x": 967,
                "y": 34,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 93, "y": 103, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 35, "y": 762, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [831, 264, 951, 364],
                "x": 891,
                "y": 362,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 32, "y": 470, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 968, "y": 46, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 124, "y": 137, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 34, "y": 752, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 864, "y": 342, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-22, 343, 101, 441],
                "x": 40,
                "y": 443,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 969, "y": 58, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 155, "y": 174, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 33, "y": 742, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 837, "y": 325, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-11, 315, 108, 417],
                "x": 48,
                "y": 416,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [908, -27, 1032, 71],
                "x": 970,
                "y": 71,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 186, "y": 214, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-28, 632, 94, 734],
                "x": 32,
                "y": 732,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [750, 212, 870, 308],
                "x": 810,
                "y": 310,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 56, "y": 391, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 971, "y": 84, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 217, "y": 254, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 31, "y": 722, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 783, "y": 297, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 65, "y": 366, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 972, "y": 97, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [188, 197, 310, 294],
                "x": 248,
                "y": 295,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 30, "y": 712, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [698, 186, 815, 286],
                "x": 756,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [15, 244, 131, 341],
                "x": 73,
                "y": 342,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 973, "y": 110, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 279, "y": 335, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 29, "y": 702, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 729, "y": 277, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [19, 217, 141, 316],
                "x": 81,
                "y": 318,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 974, "y": 124, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [251, 272, 368, 371],
                "x": 310,
                "y": 373,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 28, "y": 691, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 702, "y": 271, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 89, "y": 296, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 975, "y": 138, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 341, "y": 409, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-33, 582, 86, 680],
                "x": 27,
                "y": 681,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 675, "y": 267, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [38, 176, 159, 277],
                "x": 97,
                "y": 275,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 976, "y": 153, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [313, 342, 432, 439],
                "x": 372,
                "y": 440,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 25, "y": 670, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 648, "y": 264, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 105, "y": 254, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 977, "y": 167, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [343, 365, 463, 468],
                "x": 403,
                "y": 466,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 24, "y": 660, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [563, 166, 682, 264],
                "x": 621,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [53, 134, 171, 233],
                "x": 113,
                "y": 234,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [916, 83, 1039, 182],
                "x": 978,
                "y": 182,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [374, 384, 494, 486],
                "x": 434,
                "y": 486,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 23, "y": 649, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 594, "y": 266, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 121, "y": 215, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 979, "y": 197, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 465, "y": 498, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 22, "y": 638, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [506, 172, 628, 272],
                "x": 567,
                "y": 270,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 130, "y": 196, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 980, "y": 213, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 496, "y": 503, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 21, "y": 627, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 540, "y": 276, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 138, "y": 179, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [921, 128, 1040, 230],
                "x": 981,
                "y": 229,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 527, "y": 498, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-42, 515, 79, 614],
                "x": 20,
                "y": 616,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 513, "y": 284, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 146, "y": 162, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 982, "y": 245, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 558, "y": 483, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 19, "y": 604, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 486, "y": 294, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [96, 44, 213, 144],
                "x": 154,
                "y": 145,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 983, "y": 262, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 589, "y": 456, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-43, 492, 76, 594],
                "x": 18,
                "y": 593,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [398, 205, 519, 306],
                "x": 459,
                "y": 307,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 162, "y": 130, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 984, "y": 279, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 620, "y": 417, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-41, 481, 78, 582],
                "x": 17,
                "y": 582,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 432, "y": 321, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 170, "y": 115, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 985, "y": 296, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [592, 265, 710, 367],
                "x": 651,
                "y": 365,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 16, "y": 570, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [344, 239, 464, 336],
                "x": 405,
                "y": 337,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 178, "y": 101, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [927, 213, 1044, 315],
                "x": 986,
                "y": 313,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 682, "y": 298, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 15, "y": 558, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 378, "y": 355, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 186, "y": 88, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [928, 231, 1046, 331],
                "x": 987,
                "y": 331,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 713, "y": 216, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 14, "y": 546, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [292, 275, 411, 374],
                "x": 351,
                "y": 374,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 195, "y": 76, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 988, "y": 349, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 744, "y": 116, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 12, "y": 534, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [266, 295, 386, 397],
                "x": 324,
                "y": 396,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 203, "y": 64, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 989, "y": 368, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 776, "y": 0, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-49, 421, 70, 522],
                "x": 11,
                "y": 522,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 297, "y": 420, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 211, "y": 53, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 990, "y": 386, "track_id": None},
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 10, "y": 510, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 270, "y": 445, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 219, "y": 42, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 991, "y": 406, "track_id": None},
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 9, "y": 498, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 243, "y": 473, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 227, "y": 32, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [932, 324, 1051, 423],
                "x": 992,
                "y": 425,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-51, 385, 69, 484],
                "x": 8,
                "y": 485,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 216, "y": 502, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 235, "y": 23, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 993, "y": 445, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 7, "y": 473, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 189, "y": 533, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 243, "y": 15, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 994, "y": 465, "track_id": None},
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 6, "y": 460, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 162, "y": 566, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 251, "y": 7, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 995, "y": 485, "track_id": None},
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 5, "y": 447, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 135, "y": 600, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [202, -101, 319, 1],
                "x": 260,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 996, "y": 506, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 4, "y": 434, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [47, 538, 167, 637],
                "x": 108,
                "y": 636,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 997, "y": 527, "track_id": None},
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 3, "y": 421, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 81, "y": 674, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [940, 447, 1060, 548],
                "x": 998,
                "y": 549,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-60, 306, 62, 408],
                "x": 2,
                "y": 408,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 54, "y": 714, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 1000, "y": 571, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-59, 296, 62, 394],
                "x": 1,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-35, 653, 89, 753],
                "x": 27,
                "y": 755,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 0, "y": 382, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-58, 701, 61, 797],
                "x": 0,
                "y": 799,
                "track_id": None,
            },
        ],
    },
]
