country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [628, 699, 755, 792],
                "x": 688,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [807, -92, 940, 4],
                "x": 871,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [362, -96, 486, 1],
                "x": 424,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [281, -107, 399, 2],
                "x": 334,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-61, 632, 59, 736],
                "x": 0,
                "y": 741,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [932, 540, 1070, 645],
                "x": 1000,
                "y": 635,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-60, 56, 57, 147],
                "x": 0,
                "y": 156,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 0, "y": 184, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [922, 694, 1031, 802],
                "x": 981,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-64, 670, 66, 760],
                "x": 0,
                "y": 762,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [604, 595, 724, 677],
                "x": 663,
                "y": 687,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [809, -103, 930, -1],
                "x": 874,
                "y": 1,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [376, -96, 497, 5],
                "x": 440,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [285, -25, 410, 63],
                "x": 347,
                "y": 66,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-34, 593, 82, 696],
                "x": 28,
                "y": 696,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [924, 521, 1028, 617],
                "x": 978,
                "y": 611,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 28, "y": 206, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-37, 70, 75, 161],
                "x": 14,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [913, 694, 1049, 800],
                "x": 981,
                "y": 796,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 32, "y": 742, "track_id": None},
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [575, 491, 698, 583],
                "x": 638,
                "y": 592,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [814, -103, 927, -1],
                "x": 877,
                "y": 2,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [394, -94, 515, 6],
                "x": 456,
                "y": 5,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [294, 30, 417, 130],
                "x": 360,
                "y": 126,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-7, 551, 120, 665],
                "x": 56,
                "y": 657,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [904, 476, 1008, 578],
                "x": 956,
                "y": 586,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-3, 142, 119, 253],
                "x": 57,
                "y": 249,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-25, 53, 95, 147],
                "x": 29,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [920, 691, 1039, 797],
                "x": 982,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [10, 634, 117, 721],
                "x": 64,
                "y": 724,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [554, 409, 676, 518],
                "x": 614,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [816, -103, 933, -2],
                "x": 881,
                "y": 3,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 472, "y": 18, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [322, 70, 436, 173],
                "x": 374,
                "y": 179,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [27, 523, 146, 615],
                "x": 85,
                "y": 621,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [880, 452, 1004, 553],
                "x": 934,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [25, 183, 136, 280],
                "x": 85,
                "y": 285,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-27, 33, 109, 141],
                "x": 43,
                "y": 137,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [930, 680, 1034, 796],
                "x": 983,
                "y": 789,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 96, "y": 708, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [520, 350, 652, 442],
                "x": 589,
                "y": 448,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [834, -86, 939, -1],
                "x": 884,
                "y": 5,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [434, -66, 549, 41],
                "x": 488,
                "y": 36,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [336, 124, 455, 225],
                "x": 387,
                "y": 226,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [43, 495, 178, 590],
                "x": 113,
                "y": 591,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [843, 444, 979, 529],
                "x": 913,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [52, 220, 171, 311],
                "x": 114,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [0, 25, 126, 134],
                "x": 58,
                "y": 131,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 983, "y": 785, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [70, 591, 183, 690],
                "x": 129,
                "y": 692,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [512, 302, 615, 405],
                "x": 565,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [824, -88, 948, 7],
                "x": 887,
                "y": 7,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [436, -35, 557, 52],
                "x": 504,
                "y": 58,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 400, "y": 267, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [85, 461, 196, 559],
                "x": 142,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [841, 427, 944, 512],
                "x": 891,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [78, 231, 209, 331],
                "x": 142,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [20, 21, 137, 129],
                "x": 72,
                "y": 131,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [918, 673, 1048, 787],
                "x": 984,
                "y": 782,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [105, 583, 214, 683],
                "x": 161,
                "y": 678,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 540, "y": 360, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [823, -82, 956, 0],
                "x": 891,
                "y": 9,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [462, -23, 576, 82],
                "x": 520,
                "y": 84,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [364, 199, 467, 296],
                "x": 414,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [101, 437, 232, 548],
                "x": 170,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [811, 404, 924, 486],
                "x": 869,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [114, 259, 224, 351],
                "x": 171,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [22, 32, 152, 144],
                "x": 87,
                "y": 134,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [924, 676, 1046, 778],
                "x": 985,
                "y": 778,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [137, 560, 245, 662],
                "x": 193,
                "y": 665,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [452, 239, 575, 333],
                "x": 516,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [825, -87, 944, 9],
                "x": 894,
                "y": 11,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [476, 5, 594, 106],
                "x": 536,
                "y": 113,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [365, 227, 491, 322],
                "x": 427,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [143, 419, 253, 528],
                "x": 199,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [782, 384, 913, 473],
                "x": 847,
                "y": 474,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [148, 273, 256, 368],
                "x": 200,
                "y": 366,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [46, 35, 161, 148],
                "x": 101,
                "y": 141,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [920, 680, 1050, 777],
                "x": 985,
                "y": 775,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 225, "y": 652, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [424, 209, 556, 318],
                "x": 491,
                "y": 319,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 898, "y": 13, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [490, 51, 604, 137],
                "x": 552,
                "y": 144,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [372, 259, 494, 349],
                "x": 441,
                "y": 358,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [173, 407, 288, 507],
                "x": 227,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [770, 357, 880, 451],
                "x": 826,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [164, 279, 287, 377],
                "x": 228,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [57, 56, 179, 157],
                "x": 116,
                "y": 152,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 986, "y": 771, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [208, 533, 327, 646],
                "x": 258,
                "y": 640,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [403, 219, 520, 310],
                "x": 466,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [834, -83, 951, 24],
                "x": 901,
                "y": 16,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [504, 68, 618, 168],
                "x": 568,
                "y": 176,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 454, "y": 378, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [189, 388, 313, 484],
                "x": 255,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [741, 328, 865, 427],
                "x": 804,
                "y": 434,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [203, 266, 308, 375],
                "x": 257,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [62, 62, 199, 159],
                "x": 130,
                "y": 167,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 987, "y": 767, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [228, 537, 347, 627],
                "x": 290,
                "y": 629,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [380, 212, 500, 306],
                "x": 442,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [854, -77, 973, 16],
                "x": 904,
                "y": 19,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [525, 107, 643, 210],
                "x": 584,
                "y": 209,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [410, 287, 532, 398],
                "x": 467,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [233, 379, 336, 487],
                "x": 284,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [730, 323, 842, 411],
                "x": 782,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [230, 283, 337, 382],
                "x": 285,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [81, 80, 206, 180],
                "x": 145,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [923, 671, 1058, 756],
                "x": 988,
                "y": 764,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [253, 516, 381, 622],
                "x": 322,
                "y": 618,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 417, "y": 322, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [844, -78, 962, 32],
                "x": 908,
                "y": 22,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [536, 140, 655, 236],
                "x": 600,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [425, 318, 531, 399],
                "x": 481,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [255, 371, 376, 488],
                "x": 312,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [699, 290, 822, 391],
                "x": 760,
                "y": 397,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 314, "y": 372, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [101, 97, 220, 204],
                "x": 159,
                "y": 205,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [928, 652, 1050, 756],
                "x": 988,
                "y": 760,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [288, 498, 424, 604],
                "x": 354,
                "y": 607,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [342, 239, 444, 347],
                "x": 393,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [842, -70, 968, 16],
                "x": 911,
                "y": 25,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [549, 178, 674, 280],
                "x": 616,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [440, 322, 548, 424],
                "x": 494,
                "y": 417,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [276, 377, 404, 480],
                "x": 341,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [680, 286, 805, 387],
                "x": 739,
                "y": 380,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [283, 261, 412, 358],
                "x": 342,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [124, 128, 236, 224],
                "x": 174,
                "y": 227,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [924, 663, 1046, 746],
                "x": 989,
                "y": 756,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [320, 491, 441, 589],
                "x": 387,
                "y": 596,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [304, 259, 436, 364],
                "x": 368,
                "y": 356,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [857, -76, 969, 37],
                "x": 915,
                "y": 29,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [568, 209, 701, 304],
                "x": 632,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [443, 322, 560, 419],
                "x": 507,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [315, 374, 433, 475],
                "x": 369,
                "y": 475,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 717, "y": 364, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [302, 264, 428, 354],
                "x": 371,
                "y": 356,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 188, "y": 253, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 990, "y": 753, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [355, 474, 486, 576],
                "x": 419,
                "y": 584,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [275, 277, 407, 373],
                "x": 344,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [867, -61, 978, 35],
                "x": 918,
                "y": 33,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [583, 231, 714, 330],
                "x": 648,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [470, 318, 585, 434],
                "x": 521,
                "y": 427,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 398, "y": 477, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [640, 243, 759, 340],
                "x": 695,
                "y": 349,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [340, 244, 457, 340],
                "x": 400,
                "y": 345,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 203, "y": 280, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [920, 657, 1042, 741],
                "x": 990,
                "y": 749,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 451, "y": 573, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [261, 313, 374, 398],
                "x": 319,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [857, -57, 990, 47],
                "x": 921,
                "y": 37,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [598, 246, 720, 357],
                "x": 664,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [467, 333, 600, 428],
                "x": 534,
                "y": 428,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 426, "y": 482, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [619, 235, 743, 346],
                "x": 673,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [366, 228, 486, 324],
                "x": 428,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [155, 212, 279, 301],
                "x": 217,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [923, 653, 1050, 736],
                "x": 991,
                "y": 745,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [425, 462, 549, 568],
                "x": 483,
                "y": 561,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [229, 325, 345, 437],
                "x": 294,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [864, -51, 978, 45],
                "x": 925,
                "y": 41,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [629, 284, 733, 383],
                "x": 680,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [492, 322, 599, 426],
                "x": 548,
                "y": 426,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 454, "y": 488, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [598, 220, 718, 316],
                "x": 652,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [406, 214, 515, 327],
                "x": 457,
                "y": 320,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [181, 245, 288, 341],
                "x": 232,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [929, 634, 1056, 747],
                "x": 992,
                "y": 741,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [458, 444, 585, 546],
                "x": 516,
                "y": 548,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [216, 358, 339, 459],
                "x": 270,
                "y": 457,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [873, -62, 987, 48],
                "x": 928,
                "y": 45,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [626, 296, 757, 387],
                "x": 696,
                "y": 389,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [492, 324, 621, 424],
                "x": 561,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [418, 393, 550, 507],
                "x": 483,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [569, 204, 699, 308],
                "x": 630,
                "y": 311,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 485, "y": 306, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [194, 270, 302, 362],
                "x": 246,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [926, 640, 1047, 728],
                "x": 992,
                "y": 738,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [487, 438, 608, 533],
                "x": 548,
                "y": 535,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [181, 379, 307, 473],
                "x": 245,
                "y": 483,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [869, -56, 989, 45],
                "x": 932,
                "y": 50,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [650, 303, 766, 401],
                "x": 712,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [518, 309, 626, 423],
                "x": 574,
                "y": 419,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [448, 417, 561, 506],
                "x": 511,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [541, 194, 658, 305],
                "x": 608,
                "y": 300,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [453, 193, 565, 286],
                "x": 514,
                "y": 293,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [196, 307, 330, 401],
                "x": 261,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [931, 626, 1044, 733],
                "x": 993,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [526, 430, 630, 523],
                "x": 580,
                "y": 520,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [171, 400, 281, 506],
                "x": 221,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [877, -39, 998, 52],
                "x": 935,
                "y": 55,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [659, 308, 787, 402],
                "x": 728,
                "y": 401,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [536, 315, 641, 411],
                "x": 588,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [472, 423, 604, 515],
                "x": 540,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [531, 200, 637, 283],
                "x": 586,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [486, 173, 598, 289],
                "x": 542,
                "y": 280,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [225, 327, 339, 432],
                "x": 275,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [941, 627, 1060, 720],
                "x": 994,
                "y": 730,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [544, 395, 670, 501],
                "x": 612,
                "y": 504,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [141, 428, 263, 535],
                "x": 196,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [872, -41, 989, 56],
                "x": 938,
                "y": 60,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [683, 286, 796, 403],
                "x": 744,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [543, 311, 670, 398],
                "x": 601,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [516, 436, 619, 533],
                "x": 568,
                "y": 533,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [496, 184, 625, 289],
                "x": 565,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [516, 179, 621, 276],
                "x": 571,
                "y": 269,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [228, 377, 353, 462],
                "x": 290,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [928, 628, 1065, 725],
                "x": 995,
                "y": 726,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [589, 387, 703, 494],
                "x": 645,
                "y": 487,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [107, 434, 234, 538],
                "x": 172,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [887, -40, 1004, 64],
                "x": 942,
                "y": 66,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [702, 273, 824, 382],
                "x": 760,
                "y": 383,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [560, 310, 684, 404],
                "x": 615,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [543, 449, 656, 538],
                "x": 597,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [491, 182, 611, 271],
                "x": 543,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [531, 156, 654, 258],
                "x": 600,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [237, 403, 362, 494],
                "x": 304,
                "y": 503,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [943, 624, 1049, 714],
                "x": 995,
                "y": 722,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 677, "y": 469, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [90, 447, 202, 549],
                "x": 147,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [876, -22, 1012, 68],
                "x": 945,
                "y": 71,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [707, 265, 828, 368],
                "x": 776,
                "y": 361,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [577, 297, 679, 404],
                "x": 628,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [555, 465, 695, 566],
                "x": 625,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [466, 179, 575, 265],
                "x": 521,
                "y": 270,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 628, "y": 250, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [252, 446, 382, 532],
                "x": 319,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [926, 626, 1056, 722],
                "x": 996,
                "y": 718,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [653, 357, 769, 445],
                "x": 709,
                "y": 449,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [66, 463, 186, 552],
                "x": 122,
                "y": 556,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [897, -30, 1008, 73],
                "x": 949,
                "y": 77,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 792, "y": 330, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [575, 280, 694, 395],
                "x": 641,
                "y": 389,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 653, "y": 581, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [438, 165, 570, 275],
                "x": 500,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [606, 148, 722, 235],
                "x": 657,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [278, 478, 387, 562],
                "x": 333,
                "y": 568,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [944, 623, 1048, 708],
                "x": 997,
                "y": 714,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [686, 329, 804, 421],
                "x": 741,
                "y": 427,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [41, 445, 153, 550],
                "x": 98,
                "y": 552,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 952, "y": 84, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [756, 185, 858, 278],
                "x": 808,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [585, 280, 717, 389],
                "x": 655,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [620, 493, 743, 600],
                "x": 682,
                "y": 599,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [412, 162, 532, 272],
                "x": 478,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [623, 151, 737, 243],
                "x": 685,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [295, 509, 407, 602],
                "x": 348,
                "y": 600,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [938, 602, 1061, 713],
                "x": 997,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [708, 304, 842, 401],
                "x": 774,
                "y": 404,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [22, 429, 125, 535],
                "x": 73,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [901, -15, 1017, 85],
                "x": 955,
                "y": 90,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [765, 131, 875, 239],
                "x": 824,
                "y": 235,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [599, 272, 727, 370],
                "x": 668,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [658, 526, 780, 618],
                "x": 710,
                "y": 618,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [399, 154, 526, 271],
                "x": 456,
                "y": 261,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [658, 138, 766, 235],
                "x": 714,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [304, 520, 413, 622],
                "x": 362,
                "y": 630,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [929, 606, 1052, 709],
                "x": 998,
                "y": 706,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [751, 268, 862, 370],
                "x": 806,
                "y": 378,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-20, 412, 105, 509],
                "x": 49,
                "y": 515,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [895, -7, 1022, 107],
                "x": 959,
                "y": 97,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [779, 70, 903, 170],
                "x": 840,
                "y": 169,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [627, 277, 738, 382],
                "x": 681,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [676, 527, 793, 638],
                "x": 739,
                "y": 637,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [371, 167, 491, 252],
                "x": 434,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [689, 141, 793, 252],
                "x": 742,
                "y": 248,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [319, 567, 439, 665],
                "x": 377,
                "y": 659,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [939, 598, 1062, 706],
                "x": 999,
                "y": 702,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [788, 259, 908, 355],
                "x": 838,
                "y": 350,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-26, 386, 79, 486],
                "x": 24,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [901, 0, 1020, 105],
                "x": 962,
                "y": 104,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [804, -13, 917, 92],
                "x": 856,
                "y": 91,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [626, 277, 749, 382],
                "x": 695,
                "y": 375,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 767, "y": 656, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 413, "y": 262, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [720, 164, 821, 267],
                "x": 771,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [338, 592, 460, 689],
                "x": 391,
                "y": 687,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [943, 609, 1070, 698],
                "x": 1000,
                "y": 699,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [804, 229, 933, 310],
                "x": 870,
                "y": 319,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 0, "y": 434, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [913, 4, 1023, 106],
                "x": 966,
                "y": 111,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [811, -103, 932, 6],
                "x": 873,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [657, 284, 774, 382],
                "x": 708,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [734, 568, 857, 682],
                "x": 796,
                "y": 675,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [329, 160, 458, 266],
                "x": 391,
                "y": 264,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 800, "y": 272, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [338, 611, 458, 721],
                "x": 406,
                "y": 712,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [843, 191, 961, 282],
                "x": 903,
                "y": 286,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 969, "y": 118, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [667, 280, 780, 387],
                "x": 722,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [770, 588, 888, 705],
                "x": 824,
                "y": 695,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 369, "y": 269, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [766, 192, 887, 300],
                "x": 828,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [357, 632, 480, 741],
                "x": 420,
                "y": 735,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [871, 142, 999, 244],
                "x": 935,
                "y": 251,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [902, 29, 1030, 117],
                "x": 972,
                "y": 126,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [673, 276, 798, 376],
                "x": 735,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [787, 618, 903, 712],
                "x": 852,
                "y": 714,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [283, 171, 403, 276],
                "x": 347,
                "y": 274,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [806, 218, 915, 320],
                "x": 857,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [374, 655, 491, 764],
                "x": 435,
                "y": 756,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [908, 104, 1030, 216],
                "x": 967,
                "y": 212,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [910, 42, 1034, 142],
                "x": 976,
                "y": 134,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [689, 302, 814, 398],
                "x": 748,
                "y": 394,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [812, 625, 934, 726],
                "x": 881,
                "y": 732,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [261, 176, 390, 277],
                "x": 326,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [828, 260, 953, 346],
                "x": 885,
                "y": 350,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [387, 667, 513, 782],
                "x": 449,
                "y": 774,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [931, 79, 1069, 177],
                "x": 1000,
                "y": 170,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [926, 34, 1034, 144],
                "x": 979,
                "y": 143,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [699, 317, 827, 410],
                "x": 762,
                "y": 407,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 909, "y": 750, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [246, 184, 355, 288],
                "x": 304,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [850, 282, 975, 383],
                "x": 914,
                "y": 388,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [400, 693, 529, 794],
                "x": 464,
                "y": 788,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [919, 51, 1049, 144],
                "x": 983,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [718, 319, 845, 418],
                "x": 775,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 938, "y": 768, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 282, "y": 302, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [879, 331, 992, 436],
                "x": 942,
                "y": 435,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [412, 701, 531, 794],
                "x": 479,
                "y": 800,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [932, 70, 1037, 153],
                "x": 986,
                "y": 160,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [721, 347, 847, 438],
                "x": 788,
                "y": 444,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [902, 692, 1026, 776],
                "x": 966,
                "y": 784,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [209, 208, 316, 321],
                "x": 260,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [913, 391, 1030, 484],
                "x": 971,
                "y": 489,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [920, 72, 1059, 161],
                "x": 989,
                "y": 169,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [734, 362, 869, 476],
                "x": 802,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [936, 704, 1053, 810],
                "x": 995,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [188, 230, 291, 338],
                "x": 239,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [942, 446, 1063, 545],
                "x": 1000,
                "y": 552,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [938, 72, 1060, 176],
                "x": 993,
                "y": 179,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [762, 390, 869, 507],
                "x": 815,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [159, 248, 276, 351],
                "x": 217,
                "y": 345,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [928, 85, 1057, 195],
                "x": 996,
                "y": 188,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [776, 439, 883, 540],
                "x": 829,
                "y": 534,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [133, 270, 258, 367],
                "x": 195,
                "y": 362,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [943, 92, 1062, 195],
                "x": 1000,
                "y": 198,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [779, 469, 901, 584],
                "x": 842,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [113, 289, 241, 379],
                "x": 173,
                "y": 382,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [796, 526, 925, 631],
                "x": 855,
                "y": 621,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 152, "y": 404, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [804, 564, 921, 672],
                "x": 869,
                "y": 674,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [73, 331, 185, 421],
                "x": 130,
                "y": 427,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 882, "y": 733, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [56, 355, 172, 444],
                "x": 108,
                "y": 453,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [841, 706, 957, 798],
                "x": 896,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [21, 384, 139, 478],
                "x": 86,
                "y": 480,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [13, 411, 128, 504],
                "x": 65,
                "y": 510,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [-14, 436, 98, 546],
                "x": 43,
                "y": 542,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [-48, 466, 73, 574],
                "x": 21,
                "y": 576,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [-70, 506, 67, 607],
                "x": 0,
                "y": 612,
                "track_id": None,
            }
        ],
    },
]
