country_balls_amount = 15
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [941, 582, 1062, 675],
                "x": 1000,
                "y": 677,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 121, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [936, 108, 1060, 204],
                "x": 1000,
                "y": 208,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [741, -98, 859, 5],
                "x": 800,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [330, 695, 451, 805],
                "x": 392,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [878, 705, 1001, 800],
                "x": 939,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [940, 369, 1057, 469],
                "x": 1000,
                "y": 467,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 606, "y": 799, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [944, 400, 1064, 496],
                "x": 1000,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [944, 360, 1057, 454],
                "x": 1000,
                "y": 457,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [941, 656, 1059, 758],
                "x": 1000,
                "y": 754,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 0, "y": 102, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [-58, -8, 57, 91],
                "x": 0,
                "y": 92,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [943, 57, 1056, 165],
                "x": 1000,
                "y": 161,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [937, 532, 1065, 636],
                "x": 1000,
                "y": 636,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [902, 516, 1030, 609],
                "x": 967,
                "y": 613,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [936, 14, 1061, 113],
                "x": 997,
                "y": 114,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [905, 113, 1031, 212],
                "x": 967,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [747, -98, 862, -1],
                "x": 803,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [351, 655, 469, 751],
                "x": 407,
                "y": 751,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [885, 689, 1004, 795],
                "x": 942,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [932, 390, 1054, 495],
                "x": 995,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [541, 684, 666, 782],
                "x": 604,
                "y": 784,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [905, 321, 1030, 420],
                "x": 965,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 985, "y": 517, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [918, 550, 1032, 658],
                "x": 975,
                "y": 655,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-28, 47, 89, 155],
                "x": 30,
                "y": 150,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 2, "y": 114, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [916, 81, 1037, 180],
                "x": 978,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [916, 568, 1037, 671],
                "x": 977,
                "y": 667,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 935, "y": 551, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [936, 2, 1058, 106],
                "x": 994,
                "y": 107,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 935, "y": 216, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [743, -99, 871, 3],
                "x": 807,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [357, 607, 482, 707],
                "x": 422,
                "y": 708,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [884, 680, 1010, 780],
                "x": 945,
                "y": 783,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [930, 420, 1050, 520],
                "x": 991,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [541, 663, 661, 768],
                "x": 603,
                "y": 768,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [875, 272, 993, 369],
                "x": 931,
                "y": 370,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [907, 469, 1028, 572],
                "x": 971,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [893, 473, 1010, 574],
                "x": 951,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-5, 99, 117, 193],
                "x": 60,
                "y": 197,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 5, "y": 137, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [893, 110, 1013, 204],
                "x": 957,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [896, 591, 1015, 693],
                "x": 955,
                "y": 693,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [838, 391, 958, 493],
                "x": 903,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [929, 2, 1048, 105],
                "x": 991,
                "y": 101,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 903, "y": 219, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 810, "y": 2, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [379, 573, 494, 675],
                "x": 437,
                "y": 671,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [884, 670, 1013, 773],
                "x": 948,
                "y": 773,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 987, "y": 542, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [545, 655, 662, 747],
                "x": 602,
                "y": 752,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [836, 241, 954, 337],
                "x": 897,
                "y": 338,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 957, "y": 613, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 927, "y": 494, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [27, 146, 151, 247],
                "x": 90,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-49, 58, 63, 163],
                "x": 7,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [874, 130, 997, 229],
                "x": 936,
                "y": 226,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [870, 610, 993, 710],
                "x": 933,
                "y": 713,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [808, 338, 931, 442],
                "x": 870,
                "y": 437,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [931, -1, 1053, 99],
                "x": 988,
                "y": 94,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [811, 126, 929, 222],
                "x": 870,
                "y": 221,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 814, "y": 4, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [388, 539, 516, 640],
                "x": 452,
                "y": 639,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 951, "y": 763, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [927, 466, 1039, 561],
                "x": 983,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [543, 637, 658, 734],
                "x": 601,
                "y": 736,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [808, 226, 925, 318],
                "x": 863,
                "y": 322,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [883, 554, 1000, 648],
                "x": 942,
                "y": 649,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [838, 328, 963, 430],
                "x": 902,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [66, 187, 182, 283],
                "x": 121,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-51, 82, 74, 177],
                "x": 10,
                "y": 180,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [857, 144, 976, 247],
                "x": 914,
                "y": 243,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 911, "y": 729, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [774, 284, 893, 386],
                "x": 838,
                "y": 385,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 985, "y": 87, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 838, "y": 222, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [759, -88, 883, 10],
                "x": 818,
                "y": 7,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [404, 508, 531, 609],
                "x": 468,
                "y": 612,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 954, "y": 753, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [914, 488, 1034, 589],
                "x": 979,
                "y": 586,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [545, 620, 662, 723],
                "x": 600,
                "y": 720,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 829, "y": 321, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [868, 584, 992, 681],
                "x": 928,
                "y": 679,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 878, "y": 376, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [88, 226, 214, 319],
                "x": 151,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-49, 100, 68, 205],
                "x": 13,
                "y": 201,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [834, 156, 948, 258],
                "x": 893,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [826, 641, 943, 736],
                "x": 888,
                "y": 740,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 806, "y": 337, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 983, "y": 81, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [741, 119, 867, 224],
                "x": 806,
                "y": 224,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [763, -85, 877, 8],
                "x": 821,
                "y": 11,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [427, 487, 538, 591],
                "x": 483,
                "y": 590,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [894, 636, 1020, 739],
                "x": 957,
                "y": 741,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 975, "y": 606, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [535, 602, 660, 706],
                "x": 598,
                "y": 703,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [734, 228, 859, 329],
                "x": 794,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [855, 597, 971, 703],
                "x": 914,
                "y": 702,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 854, "y": 332, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [125, 257, 238, 362],
                "x": 181,
                "y": 360,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 15, "y": 222, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 872, "y": 270, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [803, 648, 922, 744],
                "x": 866,
                "y": 746,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [715, 197, 829, 288],
                "x": 774,
                "y": 293,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [924, -30, 1042, 73],
                "x": 980,
                "y": 75,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [717, 130, 836, 222],
                "x": 774,
                "y": 225,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 825, "y": 16, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [443, 468, 563, 569],
                "x": 498,
                "y": 572,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [898, 628, 1018, 725],
                "x": 960,
                "y": 729,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 971, "y": 625, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [540, 588, 661, 686],
                "x": 597,
                "y": 687,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [698, 255, 823, 353],
                "x": 760,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [838, 614, 962, 722],
                "x": 900,
                "y": 718,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [773, 192, 894, 291],
                "x": 829,
                "y": 296,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [152, 293, 276, 395],
                "x": 212,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-45, 144, 79, 248],
                "x": 18,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [786, 185, 906, 281],
                "x": 851,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [785, 650, 899, 752],
                "x": 844,
                "y": 747,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [676, 151, 798, 248],
                "x": 741,
                "y": 252,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [917, -32, 1035, 65],
                "x": 977,
                "y": 69,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [684, 125, 796, 222],
                "x": 741,
                "y": 226,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [769, -83, 894, 26],
                "x": 829,
                "y": 21,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [453, 462, 572, 559],
                "x": 513,
                "y": 558,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 963, "y": 715, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [909, 547, 1026, 649],
                "x": 967,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [536, 575, 656, 675],
                "x": 596,
                "y": 670,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [661, 284, 788, 381],
                "x": 726,
                "y": 381,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [826, 632, 949, 730],
                "x": 885,
                "y": 729,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [748, 163, 865, 265],
                "x": 805,
                "y": 268,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 242, "y": 427, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [-40, 161, 81, 262],
                "x": 21,
                "y": 263,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 829, "y": 291, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [761, 649, 884, 745],
                "x": 822,
                "y": 745,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [646, 113, 765, 214],
                "x": 709,
                "y": 215,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 974, "y": 63, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 709, "y": 227, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [773, -75, 889, 28],
                "x": 832,
                "y": 28,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 528, "y": 547, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 966, "y": 702, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [907, 565, 1028, 660],
                "x": 963,
                "y": 661,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 595, "y": 653, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 692, "y": 412, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [813, 628, 926, 731],
                "x": 871,
                "y": 733,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [716, 146, 844, 244],
                "x": 781,
                "y": 248,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [214, 354, 332, 453],
                "x": 272,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-41, 185, 84, 283],
                "x": 23,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [743, 203, 867, 300],
                "x": 808,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [739, 640, 865, 736],
                "x": 800,
                "y": 740,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 677, "y": 183, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 971, "y": 58, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [613, 131, 733, 225],
                "x": 677,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [777, -66, 899, 39],
                "x": 836,
                "y": 36,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [487, 442, 603, 540],
                "x": 544,
                "y": 540,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [914, 591, 1030, 685],
                "x": 969,
                "y": 687,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 959, "y": 678, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [538, 531, 654, 634],
                "x": 594,
                "y": 636,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 658, "y": 445, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [792, 629, 915, 735],
                "x": 857,
                "y": 733,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [699, 137, 820, 239],
                "x": 757,
                "y": 235,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 303, "y": 482, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [-37, 199, 84, 305],
                "x": 26,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [729, 206, 845, 304],
                "x": 787,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [720, 628, 839, 735],
                "x": 777,
                "y": 730,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 645, "y": 155, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [905, -44, 1033, 50],
                "x": 968,
                "y": 52,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [582, 137, 704, 232],
                "x": 645,
                "y": 232,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [774, -55, 899, 46],
                "x": 839,
                "y": 44,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 559, "y": 536, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 972, "y": 671, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [896, 597, 1018, 688],
                "x": 955,
                "y": 693,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [527, 521, 648, 624],
                "x": 592,
                "y": 619,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [560, 373, 685, 482],
                "x": 624,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [784, 627, 904, 726],
                "x": 843,
                "y": 727,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [670, 129, 789, 225],
                "x": 732,
                "y": 227,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [275, 408, 392, 506],
                "x": 333,
                "y": 506,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 28, "y": 321, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 765, "y": 308, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [692, 618, 810, 715],
                "x": 755,
                "y": 718,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 612, "y": 132, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [907, -56, 1027, 47],
                "x": 966,
                "y": 47,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [554, 138, 667, 238],
                "x": 612,
                "y": 235,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [781, -46, 907, 48],
                "x": 843,
                "y": 53,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [512, 430, 636, 537],
                "x": 574,
                "y": 534,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [915, 557, 1034, 657],
                "x": 975,
                "y": 655,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [892, 604, 1016, 709],
                "x": 951,
                "y": 708,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 591, "y": 601, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [534, 406, 648, 505],
                "x": 589,
                "y": 505,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [765, 622, 892, 720],
                "x": 828,
                "y": 717,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [648, 128, 768, 226],
                "x": 708,
                "y": 225,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [302, 425, 424, 532],
                "x": 363,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-26, 237, 93, 336],
                "x": 31,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [685, 212, 802, 313],
                "x": 744,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [677, 606, 793, 702],
                "x": 733,
                "y": 703,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [523, 11, 644, 116],
                "x": 580,
                "y": 113,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [901, -60, 1024, 41],
                "x": 963,
                "y": 42,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 580, "y": 240, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 847, "y": 64, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [532, 430, 647, 534],
                "x": 589,
                "y": 534,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [917, 542, 1039, 639],
                "x": 978,
                "y": 638,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [892, 624, 1006, 725],
                "x": 947,
                "y": 721,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [534, 485, 654, 587],
                "x": 590,
                "y": 584,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 555, "y": 527, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [756, 605, 871, 702],
                "x": 814,
                "y": 703,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [621, 128, 740, 233],
                "x": 684,
                "y": 228,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [337, 449, 456, 543],
                "x": 393,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-21, 258, 89, 359],
                "x": 34,
                "y": 358,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [661, 211, 785, 308],
                "x": 723,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [649, 583, 768, 690],
                "x": 711,
                "y": 685,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [492, 1, 609, 96],
                "x": 548,
                "y": 99,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [900, -63, 1022, 42],
                "x": 960,
                "y": 37,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 548, "y": 246, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [787, -21, 910, 70],
                "x": 850,
                "y": 75,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 604, "y": 536, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 981, "y": 620, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [886, 631, 1004, 733],
                "x": 943,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [528, 461, 648, 565],
                "x": 589,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [460, 439, 583, 540],
                "x": 521,
                "y": 540,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [739, 581, 863, 685],
                "x": 800,
                "y": 684,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [596, 137, 721, 240],
                "x": 659,
                "y": 235,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [364, 460, 482, 560],
                "x": 424,
                "y": 559,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 36, "y": 376, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [639, 214, 766, 312],
                "x": 702,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [624, 565, 749, 669],
                "x": 688,
                "y": 665,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 516, "y": 90, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 957, "y": 32, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [457, 151, 580, 256],
                "x": 516,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [790, -13, 909, 83],
                "x": 854,
                "y": 87,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [565, 435, 685, 542],
                "x": 620,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [922, 498, 1046, 596],
                "x": 984,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [884, 643, 1001, 742],
                "x": 939,
                "y": 746,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [528, 443, 644, 548],
                "x": 588,
                "y": 548,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 487, "y": 541, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [731, 563, 845, 661],
                "x": 786,
                "y": 662,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [575, 144, 696, 250],
                "x": 635,
                "y": 246,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 454, "y": 571, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [-21, 299, 103, 390],
                "x": 39,
                "y": 394,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [615, 215, 736, 311],
                "x": 680,
                "y": 313,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 666, "y": 643, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [420, -12, 543, 88],
                "x": 483,
                "y": 87,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [898, -71, 1013, 30],
                "x": 954,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [422, 160, 546, 259],
                "x": 483,
                "y": 263,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 858, "y": 101, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [577, 445, 693, 541],
                "x": 635,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [925, 481, 1052, 585],
                "x": 987,
                "y": 581,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [877, 656, 993, 756],
                "x": 935,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [527, 428, 646, 527],
                "x": 587,
                "y": 530,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 453, "y": 528, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 771, "y": 637, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [554, 163, 666, 264],
                "x": 611,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [423, 474, 541, 576],
                "x": 484,
                "y": 579,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-14, 312, 106, 412],
                "x": 42,
                "y": 411,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [600, 209, 724, 309],
                "x": 659,
                "y": 312,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 644, "y": 620, "track_id": None},
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 451, "y": 88, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [895, -80, 1012, 23],
                "x": 951,
                "y": 23,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 451, "y": 275, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 861, "y": 115, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 650, "y": 549, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [931, 466, 1046, 558],
                "x": 990,
                "y": 561,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 931, "y": 767, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [522, 409, 645, 507],
                "x": 585,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [361, 394, 482, 494],
                "x": 418,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [701, 508, 821, 614],
                "x": 757,
                "y": 610,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [528, 177, 648, 279],
                "x": 586,
                "y": 274,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [457, 479, 579, 588],
                "x": 515,
                "y": 584,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 44, "y": 428, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [579, 211, 697, 307],
                "x": 638,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [557, 495, 681, 598],
                "x": 622,
                "y": 595,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [358, -5, 482, 94],
                "x": 419,
                "y": 96,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [890, -78, 1005, 23],
                "x": 949,
                "y": 19,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [356, 189, 477, 289],
                "x": 419,
                "y": 289,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [810, 28, 922, 131],
                "x": 865,
                "y": 130,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 665, "y": 555, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [934, 443, 1048, 542],
                "x": 993,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [866, 678, 985, 776],
                "x": 927,
                "y": 776,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [528, 398, 639, 493],
                "x": 584,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [320, 350, 446, 445],
                "x": 384,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [685, 474, 803, 577],
                "x": 743,
                "y": 579,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 562, "y": 291, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [484, 488, 601, 591],
                "x": 545,
                "y": 586,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-16, 343, 110, 443],
                "x": 47,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [555, 202, 681, 306],
                "x": 617,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [540, 468, 659, 567],
                "x": 600,
                "y": 569,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [323, 11, 448, 108],
                "x": 387,
                "y": 108,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 946, "y": 15, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [331, 204, 444, 302],
                "x": 387,
                "y": 305,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [806, 47, 924, 152],
                "x": 869,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [615, 457, 742, 560],
                "x": 680,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [941, 419, 1054, 513],
                "x": 996,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [865, 690, 978, 785],
                "x": 923,
                "y": 785,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 583, "y": 475, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 350, "y": 375, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [674, 448, 788, 549],
                "x": 729,
                "y": 547,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 538, "y": 309, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [513, 486, 631, 580],
                "x": 575,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-14, 366, 110, 464],
                "x": 49,
                "y": 461,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 595, "y": 302, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [514, 446, 635, 545],
                "x": 577,
                "y": 541,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [295, 32, 409, 131],
                "x": 354,
                "y": 127,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [886, -86, 1000, 8],
                "x": 943,
                "y": 11,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 354, "y": 324, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [814, 62, 932, 162],
                "x": 872,
                "y": 164,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [631, 471, 760, 570],
                "x": 696,
                "y": 566,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 1000, "y": 493, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [854, 698, 981, 790],
                "x": 919,
                "y": 793,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 582, "y": 457, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 316, "y": 279, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [657, 415, 775, 513],
                "x": 714,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [455, 230, 579, 328],
                "x": 514,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [542, 484, 669, 578],
                "x": 606,
                "y": 580,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-5, 380, 107, 480],
                "x": 52,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [514, 197, 630, 303],
                "x": 574,
                "y": 298,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 555, "y": 514, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [267, 56, 380, 152],
                "x": 322,
                "y": 152,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 940, "y": 7, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [266, 249, 379, 347],
                "x": 322,
                "y": 345,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [813, 87, 934, 182],
                "x": 876,
                "y": 183,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [651, 469, 766, 567],
                "x": 711,
                "y": 570,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [857, 704, 979, 797],
                "x": 915,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [525, 342, 636, 440],
                "x": 581,
                "y": 438,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 282, "y": 154, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [645, 373, 757, 473],
                "x": 700,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [430, 244, 546, 342],
                "x": 489,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [574, 468, 691, 573],
                "x": 636,
                "y": 571,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-5, 394, 113, 494],
                "x": 55,
                "y": 493,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 553, "y": 293, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [475, 388, 591, 490],
                "x": 533,
                "y": 486,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [226, 83, 351, 182],
                "x": 290,
                "y": 182,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [875, -100, 1002, 6],
                "x": 937,
                "y": 3,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [234, 270, 349, 367],
                "x": 290,
                "y": 370,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [814, 107, 942, 206],
                "x": 879,
                "y": 202,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [668, 469, 787, 577],
                "x": 726,
                "y": 574,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [524, 321, 642, 417],
                "x": 579,
                "y": 419,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 248, "y": 0, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [621, 343, 751, 443],
                "x": 686,
                "y": 440,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [410, 260, 522, 357],
                "x": 465,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [603, 458, 724, 562],
                "x": 666,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [-6, 404, 118, 504],
                "x": 57,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [468, 184, 588, 283],
                "x": 531,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [452, 362, 568, 462],
                "x": 511,
                "y": 458,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [203, 116, 316, 222],
                "x": 258,
                "y": 219,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [872, -105, 995, 1],
                "x": 935,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [193, 298, 314, 397],
                "x": 258,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [826, 128, 943, 226],
                "x": 883,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [678, 477, 800, 575],
                "x": 741,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [515, 300, 639, 402],
                "x": 578,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [613, 308, 733, 399],
                "x": 671,
                "y": 403,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 441, "y": 373, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [633, 443, 752, 549],
                "x": 696,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [2, 424, 115, 524],
                "x": 60,
                "y": 523,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 510, "y": 282, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 488, "y": 431, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [167, 165, 282, 258],
                "x": 225,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [164, 329, 288, 432],
                "x": 225,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [831, 140, 945, 243],
                "x": 887,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [692, 478, 814, 576],
                "x": 756,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [513, 281, 641, 386],
                "x": 577,
                "y": 381,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [602, 264, 719, 364],
                "x": 657,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [351, 288, 481, 381],
                "x": 416,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [667, 424, 782, 523],
                "x": 727,
                "y": 524,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 63, "y": 538, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [425, 177, 550, 275],
                "x": 489,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [408, 305, 521, 400],
                "x": 466,
                "y": 403,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 193, "y": 313, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 193, "y": 465, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 890, "y": 268, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 772, "y": 574, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 576, "y": 362, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [586, 231, 702, 331],
                "x": 643,
                "y": 327,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [327, 289, 448, 390],
                "x": 392,
                "y": 393,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [692, 400, 814, 500],
                "x": 757,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [2, 456, 123, 550],
                "x": 65,
                "y": 552,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [411, 173, 528, 276],
                "x": 468,
                "y": 271,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 444, "y": 377, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 161, "y": 370, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [96, 404, 220, 509],
                "x": 161,
                "y": 505,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 894, "y": 292, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [728, 465, 845, 573],
                "x": 787,
                "y": 570,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [515, 240, 632, 346],
                "x": 575,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [574, 194, 691, 292],
                "x": 629,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [303, 299, 426, 395],
                "x": 368,
                "y": 397,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 787, "y": 474, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [5, 467, 123, 567],
                "x": 68,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [381, 169, 508, 267],
                "x": 446,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [361, 250, 477, 350],
                "x": 422,
                "y": 352,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 129, "y": 433, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [73, 446, 186, 553],
                "x": 129,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [833, 222, 954, 320],
                "x": 898,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [744, 463, 857, 566],
                "x": 802,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [516, 218, 628, 322],
                "x": 573,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [553, 155, 673, 257],
                "x": 614,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [286, 300, 407, 395],
                "x": 343,
                "y": 397,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [759, 345, 874, 439],
                "x": 818,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [5, 477, 131, 577],
                "x": 70,
                "y": 580,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 425, "y": 259, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [343, 234, 465, 324],
                "x": 400,
                "y": 329,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [34, 399, 154, 499],
                "x": 96,
                "y": 504,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 96, "y": 596, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [844, 242, 962, 346],
                "x": 901,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [752, 449, 877, 551],
                "x": 817,
                "y": 552,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 572, "y": 304, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [541, 119, 657, 213],
                "x": 600,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [260, 287, 380, 390],
                "x": 319,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [788, 309, 912, 404],
                "x": 848,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [10, 491, 131, 590],
                "x": 73,
                "y": 593,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [349, 150, 467, 253],
                "x": 404,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [315, 204, 433, 309],
                "x": 377,
                "y": 307,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [3, 480, 119, 579],
                "x": 64,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [8, 547, 126, 651],
                "x": 64,
                "y": 648,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [847, 274, 968, 369],
                "x": 905,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [768, 434, 894, 539],
                "x": 832,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [509, 182, 628, 284],
                "x": 571,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [527, 85, 651, 186],
                "x": 586,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [239, 281, 351, 382],
                "x": 295,
                "y": 381,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [814, 269, 934, 370],
                "x": 878,
                "y": 370,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [11, 502, 140, 608],
                "x": 76,
                "y": 606,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [322, 144, 443, 245],
                "x": 382,
                "y": 249,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 355, "y": 287, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 32, "y": 668, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 32, "y": 705, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 909, "y": 400, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [792, 417, 910, 515],
                "x": 848,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [513, 165, 625, 260],
                "x": 570,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [513, 50, 633, 153],
                "x": 572,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [209, 262, 332, 367],
                "x": 271,
                "y": 363,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [844, 229, 973, 332],
                "x": 909,
                "y": 327,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [13, 515, 142, 616],
                "x": 78,
                "y": 619,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [301, 139, 416, 245],
                "x": 361,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [273, 173, 397, 268],
                "x": 333,
                "y": 269,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-62, 660, 63, 766],
                "x": 0,
                "y": 761,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 768, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [849, 329, 973, 435],
                "x": 912,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [799, 402, 927, 498],
                "x": 863,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [507, 150, 634, 246],
                "x": 569,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [497, 24, 614, 116],
                "x": 557,
                "y": 121,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [183, 242, 311, 341],
                "x": 246,
                "y": 338,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 939, "y": 280, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 81, "y": 631, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [283, 140, 401, 239],
                "x": 340,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [249, 158, 374, 250],
                "x": 311,
                "y": 254,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [851, 357, 974, 460],
                "x": 916,
                "y": 461,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [816, 374, 938, 475],
                "x": 878,
                "y": 472,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 568, "y": 225, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [484, -5, 600, 88],
                "x": 543,
                "y": 93,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [164, 208, 286, 303],
                "x": 222,
                "y": 305,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 969, "y": 228, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [26, 543, 141, 646],
                "x": 84,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [258, 138, 378, 240],
                "x": 319,
                "y": 236,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 288, "y": 241, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [854, 388, 980, 489],
                "x": 919,
                "y": 493,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 893, "y": 440, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [508, 105, 622, 208],
                "x": 566,
                "y": 205,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [466, -33, 584, 72],
                "x": 529,
                "y": 68,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [139, 162, 257, 269],
                "x": 198,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [945, 68, 1062, 176],
                "x": 1000,
                "y": 172,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [30, 553, 147, 659],
                "x": 86,
                "y": 655,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [232, 130, 359, 233],
                "x": 297,
                "y": 233,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [205, 134, 331, 229],
                "x": 266,
                "y": 232,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 923, "y": 527, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [845, 305, 963, 406],
                "x": 908,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [505, 84, 621, 181],
                "x": 565,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [458, -57, 577, 52],
                "x": 515,
                "y": 47,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [113, 112, 238, 210],
                "x": 173,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [30, 563, 149, 671],
                "x": 89,
                "y": 667,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [211, 130, 334, 227],
                "x": 276,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [186, 127, 307, 222],
                "x": 244,
                "y": 226,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [866, 466, 990, 561],
                "x": 927,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [861, 258, 983, 359],
                "x": 924,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [507, 68, 627, 168],
                "x": 564,
                "y": 164,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 500, "y": 29, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [93, 54, 212, 150],
                "x": 149,
                "y": 153,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [29, 583, 153, 673],
                "x": 91,
                "y": 678,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [194, 130, 313, 235],
                "x": 255,
                "y": 230,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 222, "y": 224, "track_id": None},
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 930, "y": 598, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [877, 215, 994, 308],
                "x": 939,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [499, 45, 628, 141],
                "x": 563,
                "y": 144,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 486, "y": 15, "track_id": None},
            {
                "cb_id": 10,
                "bounding_box": [64, -18, 183, 78],
                "x": 125,
                "y": 82,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [38, 592, 158, 686],
                "x": 94,
                "y": 689,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [177, 135, 297, 231],
                "x": 234,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [139, 130, 259, 225],
                "x": 200,
                "y": 226,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [874, 540, 998, 636],
                "x": 934,
                "y": 636,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [899, 156, 1009, 254],
                "x": 954,
                "y": 257,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 562, "y": 124, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [417, -90, 534, 9],
                "x": 472,
                "y": 5,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 101, "y": 0, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 97, "y": 700, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 212, "y": 231, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 177, "y": 232, "track_id": None},
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [877, 580, 1001, 676],
                "x": 938,
                "y": 675,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [913, 92, 1034, 196],
                "x": 969,
                "y": 195,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 560, "y": 103, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 458, "y": 0, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 99, "y": 710, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 191, "y": 233, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [91, 146, 210, 241],
                "x": 155,
                "y": 242,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [885, 613, 999, 714],
                "x": 941,
                "y": 715,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [929, 21, 1040, 121],
                "x": 984,
                "y": 126,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 559, "y": 83, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [38, 620, 157, 718],
                "x": 102,
                "y": 721,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [109, 133, 225, 238],
                "x": 170,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [78, 159, 189, 256],
                "x": 133,
                "y": 258,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [883, 661, 1005, 758],
                "x": 945,
                "y": 757,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 50, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 558, "y": 62, "track_id": None},
            {"cb_id": 12, "bounding_box": [], "x": 105, "y": 730, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 148, "y": 242, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [56, 181, 173, 280],
                "x": 111,
                "y": 278,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [887, 703, 1006, 804],
                "x": 949,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [495, -62, 612, 46],
                "x": 557,
                "y": 41,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [52, 642, 167, 743],
                "x": 107,
                "y": 740,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 127, "y": 248, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [30, 203, 144, 308],
                "x": 88,
                "y": 304,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 7,
                "bounding_box": [494, -78, 621, 16],
                "x": 556,
                "y": 20,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 110, "y": 749, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [50, 154, 162, 256],
                "x": 106,
                "y": 256,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 66, "y": 335, "track_id": None},
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {"cb_id": 7, "bounding_box": [], "x": 555, "y": 0, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [51, 658, 168, 753],
                "x": 112,
                "y": 758,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [24, 170, 148, 269],
                "x": 85,
                "y": 266,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [-16, 276, 100, 369],
                "x": 44,
                "y": 373,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 12,
                "bounding_box": [57, 668, 180, 767],
                "x": 115,
                "y": 767,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 63, "y": 278, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [-40, 311, 82, 412],
                "x": 22,
                "y": 416,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 12,
                "bounding_box": [58, 681, 175, 777],
                "x": 118,
                "y": 776,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-19, 191, 101, 288],
                "x": 42,
                "y": 291,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 0, "y": 467, "track_id": None},
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 12,
                "bounding_box": [65, 688, 180, 780],
                "x": 120,
                "y": 784,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-34, 205, 82, 302],
                "x": 21,
                "y": 307,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {"cb_id": 12, "bounding_box": [], "x": 123, "y": 792, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 0, "y": 325, "track_id": None},
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {"cb_id": 12, "bounding_box": [], "x": 126, "y": 800, "track_id": None}
        ],
    },
]
