country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [839, 697, 962, 799],
                "x": 901,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [940, 72, 1061, 175],
                "x": 1000,
                "y": 174,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [942, 61, 1059, 164],
                "x": 1000,
                "y": 163,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 1000, "y": 162, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [816, 698, 935, 800],
                "x": 876,
                "y": 799,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [848, 691, 964, 792],
                "x": 906,
                "y": 791,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [916, 191, 1035, 289],
                "x": 975,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [902, 188, 1018, 286],
                "x": 960,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [887, 231, 1009, 332],
                "x": 947,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [813, 656, 937, 755],
                "x": 875,
                "y": 757,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 911, "y": 783, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [890, 291, 1009, 391],
                "x": 951,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [861, 278, 980, 377],
                "x": 920,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [833, 355, 955, 454],
                "x": 894,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [816, 616, 936, 715],
                "x": 875,
                "y": 716,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 916, "y": 774, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [867, 374, 986, 477],
                "x": 927,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [820, 340, 941, 442],
                "x": 881,
                "y": 440,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 842, "y": 529, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [816, 574, 935, 672],
                "x": 875,
                "y": 674,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [861, 664, 981, 762],
                "x": 921,
                "y": 764,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [841, 447, 961, 547],
                "x": 903,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [781, 379, 903, 477],
                "x": 841,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [730, 465, 851, 568],
                "x": 789,
                "y": 567,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [816, 531, 934, 635],
                "x": 875,
                "y": 633,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [867, 652, 986, 755],
                "x": 927,
                "y": 753,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [818, 507, 938, 606],
                "x": 878,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [744, 394, 863, 495],
                "x": 802,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [675, 475, 795, 574],
                "x": 736,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [816, 490, 933, 591],
                "x": 874,
                "y": 591,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 932, "y": 742, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [796, 551, 916, 649],
                "x": 854,
                "y": 651,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [703, 391, 821, 492],
                "x": 762,
                "y": 490,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [622, 454, 746, 553],
                "x": 684,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [813, 449, 932, 553],
                "x": 874,
                "y": 551,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [879, 631, 999, 728],
                "x": 937,
                "y": 730,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [768, 583, 889, 687],
                "x": 830,
                "y": 685,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [661, 372, 783, 468],
                "x": 722,
                "y": 470,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [573, 414, 691, 514],
                "x": 631,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [816, 408, 936, 510],
                "x": 874,
                "y": 510,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [884, 617, 1000, 717],
                "x": 942,
                "y": 717,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [747, 608, 868, 708],
                "x": 806,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [624, 336, 743, 437],
                "x": 683,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [518, 362, 636, 460],
                "x": 578,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [812, 367, 936, 468],
                "x": 874,
                "y": 469,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [889, 604, 1008, 702],
                "x": 947,
                "y": 704,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [720, 620, 843, 723],
                "x": 781,
                "y": 722,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [582, 297, 705, 396],
                "x": 643,
                "y": 397,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 526, "y": 401, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [811, 330, 933, 431],
                "x": 873,
                "y": 429,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [891, 590, 1014, 690],
                "x": 953,
                "y": 690,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [699, 628, 817, 724],
                "x": 757,
                "y": 726,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [546, 249, 664, 348],
                "x": 604,
                "y": 349,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [412, 240, 532, 341],
                "x": 473,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [811, 290, 934, 391],
                "x": 873,
                "y": 389,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [898, 576, 1020, 677],
                "x": 958,
                "y": 676,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [671, 623, 794, 722],
                "x": 733,
                "y": 722,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [506, 197, 624, 299],
                "x": 564,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [361, 182, 480, 284],
                "x": 421,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [814, 249, 933, 350],
                "x": 873,
                "y": 349,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [904, 560, 1025, 661],
                "x": 963,
                "y": 660,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 709, "y": 709, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [465, 149, 585, 245],
                "x": 525,
                "y": 247,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [308, 138, 429, 238],
                "x": 368,
                "y": 238,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [812, 207, 932, 309],
                "x": 873,
                "y": 309,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [908, 544, 1030, 642],
                "x": 968,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [625, 592, 744, 692],
                "x": 685,
                "y": 690,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [427, 101, 544, 199],
                "x": 485,
                "y": 200,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [255, 112, 376, 208],
                "x": 315,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [814, 171, 934, 271],
                "x": 872,
                "y": 270,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [912, 528, 1032, 629],
                "x": 973,
                "y": 628,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 660, "y": 664, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [387, 59, 506, 157],
                "x": 445,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [205, 103, 321, 204],
                "x": 263,
                "y": 205,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [814, 129, 933, 230],
                "x": 872,
                "y": 231,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [918, 510, 1041, 610],
                "x": 979,
                "y": 610,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [576, 533, 695, 635],
                "x": 636,
                "y": 633,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [348, 28, 467, 125],
                "x": 406,
                "y": 127,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [150, 129, 272, 230],
                "x": 210,
                "y": 230,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 872, "y": 192, "track_id": None},
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [926, 492, 1045, 592],
                "x": 984,
                "y": 592,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [550, 498, 672, 595],
                "x": 612,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [308, 8, 425, 107],
                "x": 366,
                "y": 108,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [98, 188, 215, 288],
                "x": 157,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [811, 55, 932, 152],
                "x": 872,
                "y": 153,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [927, 475, 1047, 572],
                "x": 989,
                "y": 573,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 588, "y": 557, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [267, 6, 389, 105],
                "x": 327,
                "y": 106,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [46, 293, 167, 391],
                "x": 105,
                "y": 393,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 871, "y": 114, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 994, "y": 553, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [501, 414, 623, 513],
                "x": 563,
                "y": 514,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 287, "y": 122, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-6, 441, 113, 541],
                "x": 52,
                "y": 543,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 871, "y": 76, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [942, 434, 1058, 531],
                "x": 1000,
                "y": 532,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [478, 368, 597, 467],
                "x": 539,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [189, 62, 308, 159],
                "x": 247,
                "y": 161,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-62, 650, 59, 746],
                "x": 0,
                "y": 748,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [811, -63, 931, 38],
                "x": 871,
                "y": 37,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [453, 321, 576, 420],
                "x": 515,
                "y": 421,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 208, "y": 225, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [810, -98, 931, -2],
                "x": 871,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [431, 274, 551, 374],
                "x": 491,
                "y": 372,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [107, 218, 226, 319],
                "x": 168,
                "y": 318,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [408, 224, 526, 324],
                "x": 467,
                "y": 324,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [71, 341, 187, 442],
                "x": 129,
                "y": 442,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [380, 174, 502, 274],
                "x": 442,
                "y": 275,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [28, 500, 147, 603],
                "x": 89,
                "y": 602,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [358, 127, 480, 226],
                "x": 418,
                "y": 228,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-10, 698, 110, 799],
                "x": 50,
                "y": 800,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [333, 83, 455, 182],
                "x": 394,
                "y": 184,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [310, 40, 430, 139],
                "x": 370,
                "y": 141,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [283, 2, 403, 105],
                "x": 345,
                "y": 103,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [260, -32, 380, 69],
                "x": 321,
                "y": 69,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [238, -58, 358, 40],
                "x": 297,
                "y": 40,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [215, -86, 331, 16],
                "x": 273,
                "y": 16,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [189, -98, 309, 2],
                "x": 249,
                "y": 0,
                "track_id": None,
            }
        ],
    },
]
