country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-58, 146, 62, 243],
                "x": 0,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-62, 367, 60, 468],
                "x": 0,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-33, -99, 88, 2],
                "x": 26,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 1000, "y": 363, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [335, -98, 456, 2],
                "x": 397,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-62, 566, 62, 669],
                "x": 0,
                "y": 667,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 1000, "y": 681, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [939, 98, 1061, 198],
                "x": 1000,
                "y": 197,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 640, "y": 800, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-59, 393, 58, 491],
                "x": 0,
                "y": 493,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-40, 118, 83, 218],
                "x": 21,
                "y": 219,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 40, "y": 470, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 47, "y": 15, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 978, "y": 438, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [358, 27, 478, 125],
                "x": 418,
                "y": 127,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-24, 443, 98, 540],
                "x": 38,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [916, 572, 1033, 672],
                "x": 975,
                "y": 671,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [898, 115, 1020, 215],
                "x": 960,
                "y": 217,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [565, 476, 682, 579],
                "x": 623,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-40, 451, 82, 547],
                "x": 21,
                "y": 549,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-17, 97, 104, 200],
                "x": 43,
                "y": 198,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [21, 368, 142, 469],
                "x": 80,
                "y": 470,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [11, -70, 127, 29],
                "x": 69,
                "y": 30,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [897, 402, 1017, 502],
                "x": 956,
                "y": 503,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 440, "y": 230, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [15, 347, 137, 444],
                "x": 76,
                "y": 445,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 951, "y": 662, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [862, 140, 979, 240],
                "x": 920,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [547, 309, 665, 410],
                "x": 606,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-19, 499, 101, 596],
                "x": 42,
                "y": 597,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [3, 83, 123, 182],
                "x": 65,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [60, 366, 180, 466],
                "x": 120,
                "y": 468,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 90, "y": 46, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [873, 462, 996, 560],
                "x": 934,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [403, 212, 521, 310],
                "x": 461,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [55, 273, 175, 373],
                "x": 115,
                "y": 371,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 926, "y": 653, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [822, 163, 942, 264],
                "x": 880,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [528, 188, 649, 287],
                "x": 590,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [3, 537, 124, 636],
                "x": 63,
                "y": 636,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [27, 67, 147, 168],
                "x": 86,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [98, 363, 221, 463],
                "x": 160,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [52, -39, 174, 64],
                "x": 112,
                "y": 63,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [852, 508, 971, 606],
                "x": 913,
                "y": 607,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [423, 271, 544, 373],
                "x": 483,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [91, 221, 212, 321],
                "x": 153,
                "y": 320,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [843, 544, 962, 646],
                "x": 902,
                "y": 644,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 840, "y": 289, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [513, 105, 634, 206],
                "x": 573,
                "y": 205,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [23, 567, 147, 668],
                "x": 85,
                "y": 668,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [50, 57, 167, 159],
                "x": 108,
                "y": 157,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [140, 361, 261, 458],
                "x": 200,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [74, -22, 192, 80],
                "x": 134,
                "y": 80,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [833, 548, 952, 645],
                "x": 891,
                "y": 646,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 504, "y": 416, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [131, 189, 250, 287],
                "x": 192,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [818, 536, 940, 635],
                "x": 878,
                "y": 636,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 800, "y": 314, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [495, 62, 619, 159],
                "x": 557,
                "y": 160,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [48, 593, 168, 693],
                "x": 106,
                "y": 693,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [72, 50, 188, 149],
                "x": 130,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [182, 357, 298, 456],
                "x": 240,
                "y": 455,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [93, -5, 215, 95],
                "x": 155,
                "y": 97,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [809, 580, 931, 678],
                "x": 869,
                "y": 678,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [466, 340, 585, 441],
                "x": 526,
                "y": 442,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 230, "y": 273, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [795, 527, 915, 628],
                "x": 853,
                "y": 628,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [701, 238, 819, 339],
                "x": 760,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [481, 47, 599, 147],
                "x": 540,
                "y": 146,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [68, 611, 186, 710],
                "x": 127,
                "y": 712,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [92, 48, 212, 146],
                "x": 152,
                "y": 146,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [221, 347, 339, 449],
                "x": 280,
                "y": 448,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [115, 13, 236, 112],
                "x": 177,
                "y": 114,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [789, 599, 907, 702],
                "x": 847,
                "y": 701,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [487, 353, 608, 453],
                "x": 547,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [211, 173, 327, 275],
                "x": 269,
                "y": 273,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 829, "y": 619, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [660, 263, 781, 362],
                "x": 720,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [464, 59, 586, 158],
                "x": 524,
                "y": 157,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 149, "y": 724, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [111, 45, 235, 144],
                "x": 173,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [260, 340, 379, 441],
                "x": 320,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [138, 34, 258, 133],
                "x": 199,
                "y": 132,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [766, 619, 884, 720],
                "x": 826,
                "y": 718,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [511, 354, 630, 453],
                "x": 569,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [245, 186, 365, 286],
                "x": 307,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [745, 513, 866, 611],
                "x": 804,
                "y": 611,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [619, 289, 742, 388],
                "x": 680,
                "y": 388,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [447, 89, 565, 187],
                "x": 507,
                "y": 188,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 170, "y": 730, "track_id": None},
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 195, "y": 147, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [299, 331, 419, 434],
                "x": 360,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [160, 51, 280, 148],
                "x": 220,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [746, 629, 862, 728],
                "x": 804,
                "y": 728,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [530, 344, 649, 445],
                "x": 590,
                "y": 443,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 346, "y": 310, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [721, 505, 839, 606],
                "x": 780,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [578, 311, 700, 411],
                "x": 640,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [428, 136, 551, 233],
                "x": 490,
                "y": 234,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [132, 632, 251, 732],
                "x": 191,
                "y": 731,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [158, 49, 278, 152],
                "x": 217,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [338, 322, 462, 425],
                "x": 400,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [181, 70, 304, 166],
                "x": 242,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [724, 634, 840, 732],
                "x": 782,
                "y": 732,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 612, "y": 423, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [326, 241, 442, 343],
                "x": 384,
                "y": 341,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 756, "y": 596, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [538, 328, 658, 431],
                "x": 600,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [416, 191, 532, 290],
                "x": 474,
                "y": 289,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 212, "y": 727, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [179, 58, 298, 156],
                "x": 239,
                "y": 157,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 440, "y": 416, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [206, 87, 325, 184],
                "x": 264,
                "y": 186,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 760, "y": 729, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [574, 298, 695, 399],
                "x": 633,
                "y": 397,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [363, 276, 484, 378],
                "x": 423,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [670, 490, 792, 589],
                "x": 731,
                "y": 589,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [498, 347, 619, 449],
                "x": 560,
                "y": 447,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 457, "y": 349, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [175, 618, 294, 721],
                "x": 234,
                "y": 719,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [199, 63, 318, 166],
                "x": 260,
                "y": 165,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [419, 305, 538, 407],
                "x": 480,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [223, 106, 346, 206],
                "x": 285,
                "y": 205,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 739, "y": 722, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [596, 263, 713, 367],
                "x": 655,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [401, 316, 521, 417],
                "x": 461,
                "y": 418,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [646, 480, 765, 581],
                "x": 707,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [459, 359, 582, 459],
                "x": 520,
                "y": 461,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [379, 309, 500, 405],
                "x": 441,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [197, 605, 313, 704],
                "x": 255,
                "y": 706,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [224, 77, 342, 176],
                "x": 282,
                "y": 175,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [458, 298, 578, 400],
                "x": 520,
                "y": 399,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 307, "y": 223, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [658, 611, 778, 709],
                "x": 717,
                "y": 709,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 676, "y": 331, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [439, 360, 561, 458],
                "x": 500,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [621, 474, 743, 573],
                "x": 682,
                "y": 575,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 480, "y": 471, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [366, 359, 483, 460],
                "x": 424,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [215, 590, 336, 689],
                "x": 276,
                "y": 691,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 304, "y": 187, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 560, "y": 391, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [270, 143, 391, 242],
                "x": 329,
                "y": 241,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [636, 590, 755, 694],
                "x": 695,
                "y": 692,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [640, 194, 759, 297],
                "x": 698,
                "y": 296,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 538, "y": 500, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [597, 467, 716, 568],
                "x": 658,
                "y": 569,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 440, "y": 477, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [350, 397, 467, 501],
                "x": 408,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [239, 572, 359, 674],
                "x": 298,
                "y": 672,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 326, "y": 200, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [542, 282, 658, 382],
                "x": 600,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [288, 161, 409, 258],
                "x": 350,
                "y": 259,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 673, "y": 671, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [660, 160, 780, 260],
                "x": 720,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [516, 437, 638, 538],
                "x": 576,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [576, 464, 692, 563],
                "x": 634,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [342, 378, 462, 479],
                "x": 400,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [332, 422, 453, 523],
                "x": 391,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [257, 549, 380, 650],
                "x": 319,
                "y": 651,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 347, "y": 215, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [582, 279, 702, 375],
                "x": 640,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [311, 178, 431, 279],
                "x": 372,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [590, 546, 714, 645],
                "x": 652,
                "y": 646,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 741, "y": 231, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 615, "y": 567, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [551, 457, 671, 557],
                "x": 609,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [302, 375, 419, 472],
                "x": 360,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [313, 420, 436, 524],
                "x": 374,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [280, 529, 398, 625],
                "x": 340,
                "y": 627,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [308, 132, 427, 230],
                "x": 369,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [619, 273, 742, 370],
                "x": 680,
                "y": 372,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 393, "y": 295, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [569, 517, 690, 619],
                "x": 630,
                "y": 617,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [704, 106, 823, 204],
                "x": 763,
                "y": 204,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 653, "y": 590, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [525, 450, 646, 550],
                "x": 585,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [260, 361, 378, 462],
                "x": 320,
                "y": 463,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [296, 393, 420, 497],
                "x": 358,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [301, 500, 419, 603],
                "x": 361,
                "y": 602,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [331, 144, 453, 248],
                "x": 391,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [660, 269, 779, 366],
                "x": 720,
                "y": 368,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [355, 214, 475, 314],
                "x": 415,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [550, 488, 670, 584],
                "x": 608,
                "y": 586,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [724, 85, 844, 184],
                "x": 784,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [634, 501, 754, 603],
                "x": 692,
                "y": 602,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [501, 448, 618, 546],
                "x": 560,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [219, 346, 338, 444],
                "x": 280,
                "y": 446,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [279, 334, 401, 436],
                "x": 341,
                "y": 434,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 383, "y": 576, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 413, "y": 263, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [702, 265, 822, 363],
                "x": 760,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [379, 230, 495, 329],
                "x": 437,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [528, 452, 648, 552],
                "x": 586,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [748, 74, 867, 171],
                "x": 806,
                "y": 173,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [671, 502, 789, 600],
                "x": 730,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [476, 441, 596, 539],
                "x": 536,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [179, 325, 301, 423],
                "x": 240,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [264, 233, 386, 334],
                "x": 325,
                "y": 335,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 404, "y": 549, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [373, 179, 496, 281],
                "x": 434,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [738, 266, 861, 363],
                "x": 800,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [398, 249, 516, 346],
                "x": 458,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [505, 416, 627, 517],
                "x": 565,
                "y": 517,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 827, "y": 173, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 769, "y": 584, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [452, 436, 572, 538],
                "x": 512,
                "y": 537,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 200, "y": 392, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 308, "y": 192, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [365, 424, 486, 523],
                "x": 425,
                "y": 522,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [396, 200, 517, 299],
                "x": 456,
                "y": 298,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 840, "y": 364, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 480, "y": 365, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [483, 379, 601, 481],
                "x": 543,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [788, 83, 909, 183],
                "x": 849,
                "y": 185,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 807, "y": 551, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 487, "y": 533, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [100, 254, 220, 355],
                "x": 160,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [233, -99, 353, -2],
                "x": 292,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [386, 395, 506, 495],
                "x": 447,
                "y": 495,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 478, "y": 316, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [822, 267, 940, 365],
                "x": 880,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [444, 282, 563, 384],
                "x": 502,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [460, 341, 583, 441],
                "x": 521,
                "y": 441,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 870, "y": 211, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [788, 397, 904, 495],
                "x": 846,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [404, 428, 524, 530],
                "x": 463,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [60, 208, 181, 308],
                "x": 120,
                "y": 306,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 468, "y": 469, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [438, 232, 558, 334],
                "x": 500,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [860, 273, 981, 372],
                "x": 920,
                "y": 372,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [464, 297, 584, 396],
                "x": 523,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [438, 302, 560, 403],
                "x": 500,
                "y": 401,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [833, 155, 954, 252],
                "x": 892,
                "y": 254,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 884, "y": 422, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [380, 425, 500, 525],
                "x": 439,
                "y": 526,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 80, "y": 249, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [427, 346, 547, 446],
                "x": 489,
                "y": 444,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 521, "y": 351, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 960, "y": 379, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [487, 316, 605, 415],
                "x": 545,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [420, 263, 538, 364],
                "x": 478,
                "y": 362,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [855, 213, 972, 316],
                "x": 913,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [865, 221, 985, 324],
                "x": 923,
                "y": 322,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [352, 424, 472, 523],
                "x": 414,
                "y": 523,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-21, 85, 100, 184],
                "x": 40,
                "y": 183,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [451, 322, 568, 422],
                "x": 510,
                "y": 421,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [482, 268, 604, 367],
                "x": 543,
                "y": 368,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 1000, "y": 389, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [507, 328, 628, 430],
                "x": 567,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [394, 220, 517, 323],
                "x": 456,
                "y": 322,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 935, "y": 396, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 961, "y": 195, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [328, 418, 449, 519],
                "x": 390,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-61, 9, 58, 109],
                "x": 0,
                "y": 108,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [472, 300, 592, 397],
                "x": 532,
                "y": 399,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [503, 285, 623, 382],
                "x": 565,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [528, 345, 648, 444],
                "x": 588,
                "y": 444,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 434, "y": 283, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [898, 400, 1015, 500],
                "x": 956,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [942, -62, 1058, 38],
                "x": 1000,
                "y": 39,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [306, 416, 426, 519],
                "x": 365,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [493, 280, 613, 379],
                "x": 553,
                "y": 381,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 586, "y": 399, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 610, "y": 458, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [351, 147, 474, 245],
                "x": 413,
                "y": 245,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [917, 525, 1039, 627],
                "x": 978,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [280, 416, 402, 516],
                "x": 341,
                "y": 516,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 574, "y": 365, "track_id": None},
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [547, 311, 666, 415],
                "x": 608,
                "y": 413,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 632, "y": 472, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [332, 106, 453, 208],
                "x": 391,
                "y": 208,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [939, 678, 1059, 781],
                "x": 1000,
                "y": 780,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [256, 415, 375, 517],
                "x": 317,
                "y": 515,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [534, 254, 657, 352],
                "x": 596,
                "y": 352,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [568, 327, 691, 426],
                "x": 630,
                "y": 425,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [591, 386, 715, 484],
                "x": 653,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [310, 73, 431, 172],
                "x": 369,
                "y": 172,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 292, "y": 514, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [559, 243, 676, 342],
                "x": 617,
                "y": 344,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [593, 337, 712, 437],
                "x": 652,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [615, 397, 735, 495],
                "x": 675,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [285, 39, 408, 137],
                "x": 347,
                "y": 139,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [206, 411, 328, 515],
                "x": 268,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [579, 239, 696, 341],
                "x": 638,
                "y": 340,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [611, 347, 735, 446],
                "x": 673,
                "y": 446,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [634, 406, 755, 508],
                "x": 696,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [267, 8, 387, 107],
                "x": 326,
                "y": 109,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [181, 413, 303, 515],
                "x": 243,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [598, 242, 717, 340],
                "x": 659,
                "y": 340,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [633, 352, 757, 455],
                "x": 695,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [657, 418, 778, 520],
                "x": 718,
                "y": 519,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [243, -21, 362, 79],
                "x": 304,
                "y": 81,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [160, 412, 280, 516],
                "x": 219,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [620, 245, 741, 345],
                "x": 681,
                "y": 346,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [656, 357, 777, 458],
                "x": 717,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [679, 429, 800, 529],
                "x": 740,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [222, -42, 344, 57],
                "x": 282,
                "y": 57,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [136, 414, 256, 516],
                "x": 195,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [644, 256, 760, 356],
                "x": 702,
                "y": 358,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [680, 360, 798, 459],
                "x": 739,
                "y": 461,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [702, 440, 821, 538],
                "x": 761,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [199, -65, 322, 38],
                "x": 260,
                "y": 37,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [110, 414, 230, 514],
                "x": 170,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [663, 276, 782, 375],
                "x": 723,
                "y": 376,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [698, 361, 819, 463],
                "x": 760,
                "y": 462,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 783, "y": 547, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [181, -80, 300, 23],
                "x": 239,
                "y": 21,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [87, 416, 205, 516],
                "x": 146,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [683, 302, 806, 402],
                "x": 745,
                "y": 401,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [721, 361, 842, 462],
                "x": 782,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [746, 454, 863, 554],
                "x": 805,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [155, -90, 278, 12],
                "x": 217,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [63, 420, 179, 522],
                "x": 121,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [707, 331, 827, 433],
                "x": 766,
                "y": 433,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [742, 356, 863, 455],
                "x": 804,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [768, 459, 886, 559],
                "x": 826,
                "y": 560,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 195, "y": 4, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 97, "y": 523, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [728, 374, 846, 473],
                "x": 787,
                "y": 472,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [767, 348, 885, 445],
                "x": 826,
                "y": 446,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [786, 468, 906, 565],
                "x": 848,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [112, -98, 234, 1],
                "x": 173,
                "y": 3,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [14, 427, 133, 525],
                "x": 73,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [746, 419, 867, 519],
                "x": 808,
                "y": 520,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [786, 334, 905, 436],
                "x": 847,
                "y": 435,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 870, "y": 570, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [91, -94, 211, 9],
                "x": 152,
                "y": 8,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 48, "y": 531, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 830, "y": 576, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [811, 318, 928, 421],
                "x": 869,
                "y": 420,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 891, "y": 573, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [71, -78, 188, 21],
                "x": 130,
                "y": 20,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 24, "y": 535, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [789, 540, 913, 641],
                "x": 851,
                "y": 641,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [831, 300, 949, 402],
                "x": 891,
                "y": 401,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [855, 477, 975, 575],
                "x": 913,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [46, -62, 169, 36],
                "x": 108,
                "y": 38,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-59, 441, 60, 542],
                "x": 0,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [812, 614, 933, 713],
                "x": 872,
                "y": 715,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 913, "y": 378, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 935, "y": 576, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [24, -34, 147, 66],
                "x": 86,
                "y": 64,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 894, "y": 799, "track_id": None},
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 934, "y": 351, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 956, "y": 575, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [6, -3, 127, 99],
                "x": 65,
                "y": 97,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 956, "y": 320, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [920, 473, 1036, 572],
                "x": 978,
                "y": 574,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 43, "y": 139, "track_id": None},
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [918, 183, 1040, 285],
                "x": 978,
                "y": 285,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [941, 470, 1058, 572],
                "x": 1000,
                "y": 570,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-39, 88, 83, 191],
                "x": 21,
                "y": 189,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [941, 146, 1060, 242],
                "x": 1000,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-61, 150, 61, 250],
                "x": 0,
                "y": 248,
                "track_id": None,
            },
        ],
    },
]
