country_balls_amount = 15
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 1000, "y": 626, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [684, 701, 803, 801],
                "x": 752,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [933, 69, 1059, 173],
                "x": 1000,
                "y": 174,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [937, 167, 1064, 274],
                "x": 1000,
                "y": 272,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-51, 496, 51, 610],
                "x": 0,
                "y": 602,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [114, -105, 233, -9],
                "x": 173,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [493, -97, 612, -7],
                "x": 546,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-66, 212, 59, 316],
                "x": 0,
                "y": 316,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [946, -32, 1060, 66],
                "x": 1000,
                "y": 73,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-68, -17, 68, 91],
                "x": 0,
                "y": 87,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [937, -49, 1055, 45],
                "x": 1000,
                "y": 49,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [941, 424, 1067, 525],
                "x": 1000,
                "y": 524,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 1000, "y": 751, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [-58, 429, 61, 526],
                "x": 0,
                "y": 525,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 1000, "y": 375, "track_id": None},
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [918, 534, 1037, 623],
                "x": 984,
                "y": 631,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [658, 696, 777, 804],
                "x": 724,
                "y": 795,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 974, "y": 216, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [907, 128, 1030, 233],
                "x": 961,
                "y": 225,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-27, 454, 102, 545],
                "x": 33,
                "y": 549,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [100, -105, 222, -3],
                "x": 169,
                "y": 2,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 547, "y": 3, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-25, 236, 85, 330],
                "x": 34,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [889, 3, 1022, 90],
                "x": 958,
                "y": 100,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-62, 16, 60, 126],
                "x": 3,
                "y": 119,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [899, 81, 1023, 191],
                "x": 956,
                "y": 186,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [902, 453, 1033, 544],
                "x": 967,
                "y": 543,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 997, "y": 719, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [-41, 469, 64, 564],
                "x": 13,
                "y": 574,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [932, 278, 1067, 391],
                "x": 998,
                "y": 388,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [915, 529, 1038, 625],
                "x": 968,
                "y": 631,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [635, 680, 754, 787],
                "x": 696,
                "y": 783,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 948, "y": 255, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [865, 93, 987, 188],
                "x": 923,
                "y": 196,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 66, "y": 505, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [98, -87, 215, 6],
                "x": 165,
                "y": 6,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [482, -99, 605, 1],
                "x": 548,
                "y": 8,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [8, 256, 137, 340],
                "x": 68,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [851, 23, 985, 131],
                "x": 916,
                "y": 126,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-51, 60, 66, 153],
                "x": 6,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [858, 210, 977, 293],
                "x": 913,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [878, 450, 996, 555],
                "x": 935,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [929, 596, 1050, 698],
                "x": 995,
                "y": 688,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-33, 509, 79, 625],
                "x": 26,
                "y": 616,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 996, "y": 402, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [886, 532, 1007, 632],
                "x": 952,
                "y": 626,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [599, 657, 720, 766],
                "x": 668,
                "y": 764,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 923, "y": 289, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [815, 75, 942, 183],
                "x": 884,
                "y": 183,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [32, 371, 151, 458],
                "x": 100,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [98, -90, 217, 15],
                "x": 161,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [486, -92, 610, 22],
                "x": 549,
                "y": 14,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [48, 265, 170, 365],
                "x": 103,
                "y": 364,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 875, "y": 151, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-56, 74, 76, 183],
                "x": 9,
                "y": 182,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [811, 309, 929, 401],
                "x": 869,
                "y": 399,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 903, "y": 573, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [931, 567, 1060, 661],
                "x": 993,
                "y": 658,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [-31, 550, 99, 645],
                "x": 39,
                "y": 651,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 995, "y": 415, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 936, "y": 617, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [589, 642, 703, 734],
                "x": 640,
                "y": 739,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [838, 219, 959, 326],
                "x": 897,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [782, 81, 898, 190],
                "x": 846,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [64, 336, 188, 447],
                "x": 133,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [98, -85, 213, 21],
                "x": 157,
                "y": 14,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 550, "y": 21, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [85, 279, 188, 385],
                "x": 137,
                "y": 381,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [766, 77, 883, 183],
                "x": 833,
                "y": 176,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-52, 110, 82, 203],
                "x": 13,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [756, 379, 881, 471],
                "x": 826,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [816, 490, 934, 577],
                "x": 870,
                "y": 583,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [935, 520, 1050, 620],
                "x": 991,
                "y": 628,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 52, "y": 678, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [938, 321, 1052, 438],
                "x": 993,
                "y": 428,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [856, 509, 982, 608],
                "x": 920,
                "y": 604,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 612, "y": 709, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [811, 246, 927, 338],
                "x": 871,
                "y": 345,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 807, "y": 198, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [109, 319, 226, 406],
                "x": 166,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [92, -87, 205, 22],
                "x": 153,
                "y": 18,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [500, -75, 620, 24],
                "x": 551,
                "y": 28,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 172, "y": 398, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 791, "y": 201, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-38, 143, 70, 249],
                "x": 16,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [732, 430, 850, 539],
                "x": 782,
                "y": 537,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [777, 484, 892, 596],
                "x": 838,
                "y": 591,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 989, "y": 599, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [-4, 596, 116, 700],
                "x": 65,
                "y": 698,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [933, 332, 1044, 446],
                "x": 992,
                "y": 441,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 904, "y": 587, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 584, "y": 675, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 846, "y": 368, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 769, "y": 223, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [144, 302, 250, 402],
                "x": 200,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [98, -83, 199, 15],
                "x": 149,
                "y": 23,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [483, -66, 612, 47],
                "x": 552,
                "y": 37,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 206, "y": 414, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [693, 127, 803, 236],
                "x": 750,
                "y": 226,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 19, "y": 270, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 739, "y": 581, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [742, 489, 875, 595],
                "x": 806,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [924, 461, 1055, 569],
                "x": 986,
                "y": 571,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 78, "y": 712, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [929, 349, 1051, 461],
                "x": 990,
                "y": 453,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [827, 471, 957, 558],
                "x": 888,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [501, 526, 619, 633],
                "x": 557,
                "y": 636,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [758, 292, 871, 393],
                "x": 820,
                "y": 387,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [679, 165, 780, 262],
                "x": 730,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [169, 284, 287, 387],
                "x": 233,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [82, -67, 210, 35],
                "x": 145,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [498, -60, 607, 41],
                "x": 553,
                "y": 46,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 241, "y": 430, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 708, "y": 249, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-38, 189, 82, 303],
                "x": 23,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [639, 507, 747, 610],
                "x": 695,
                "y": 611,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [714, 510, 824, 596],
                "x": 774,
                "y": 600,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [917, 441, 1046, 553],
                "x": 984,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [36, 626, 160, 723],
                "x": 91,
                "y": 719,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [939, 374, 1051, 462],
                "x": 989,
                "y": 466,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [818, 437, 934, 536],
                "x": 872,
                "y": 542,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 529, "y": 595, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [739, 308, 846, 410],
                "x": 794,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [641, 202, 746, 293],
                "x": 692,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [198, 283, 332, 376],
                "x": 266,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [83, -67, 207, 31],
                "x": 141,
                "y": 33,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [486, -48, 608, 65],
                "x": 554,
                "y": 56,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [216, 350, 342, 437],
                "x": 275,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [600, 164, 717, 275],
                "x": 666,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-36, 229, 93, 317],
                "x": 26,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [594, 529, 719, 621],
                "x": 652,
                "y": 629,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [672, 496, 799, 608],
                "x": 741,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [925, 414, 1040, 517],
                "x": 982,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [51, 622, 172, 727],
                "x": 104,
                "y": 721,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [934, 370, 1052, 482],
                "x": 987,
                "y": 478,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [797, 426, 911, 525],
                "x": 856,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [440, 453, 560, 551],
                "x": 501,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [707, 309, 831, 406],
                "x": 769,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [595, 251, 710, 349],
                "x": 653,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [245, 277, 350, 365],
                "x": 300,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [79, -60, 188, 49],
                "x": 137,
                "y": 39,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [495, -42, 610, 69],
                "x": 555,
                "y": 67,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [256, 357, 376, 468],
                "x": 310,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [567, 194, 677, 300],
                "x": 625,
                "y": 295,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-28, 247, 85, 355],
                "x": 29,
                "y": 351,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [540, 539, 669, 631],
                "x": 608,
                "y": 634,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 709, "y": 600, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [926, 392, 1030, 483],
                "x": 980,
                "y": 490,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [65, 610, 187, 722],
                "x": 117,
                "y": 717,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [916, 400, 1054, 496],
                "x": 986,
                "y": 490,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [781, 390, 905, 478],
                "x": 840,
                "y": 486,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [414, 416, 527, 505],
                "x": 473,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [673, 331, 796, 417],
                "x": 743,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [547, 291, 676, 401],
                "x": 615,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [269, 272, 385, 386],
                "x": 333,
                "y": 376,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 133, "y": 45, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 556, "y": 79, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [291, 367, 399, 470],
                "x": 344,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [513, 215, 649, 307],
                "x": 583,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-19, 271, 95, 368],
                "x": 32,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [503, 533, 628, 622],
                "x": 565,
                "y": 630,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [608, 488, 746, 597],
                "x": 677,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [915, 372, 1037, 466],
                "x": 978,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [71, 614, 189, 705],
                "x": 130,
                "y": 708,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 984, "y": 502, "track_id": None},
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 824, "y": 454, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [384, 352, 511, 452],
                "x": 445,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [656, 329, 783, 428],
                "x": 717,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [510, 359, 645, 448],
                "x": 576,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [304, 289, 418, 374],
                "x": 366,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [63, -46, 187, 44],
                "x": 129,
                "y": 52,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [492, -10, 623, 100],
                "x": 557,
                "y": 92,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 379, "y": 483, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [489, 236, 599, 339],
                "x": 541,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-30, 290, 100, 398],
                "x": 36,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [467, 516, 585, 621],
                "x": 521,
                "y": 616,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 645, "y": 592, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [914, 342, 1025, 434],
                "x": 975,
                "y": 440,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 143, "y": 694, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 983, "y": 513, "track_id": None},
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [743, 319, 867, 424],
                "x": 808,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [362, 312, 485, 418],
                "x": 417,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [633, 331, 756, 429],
                "x": 692,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [469, 401, 591, 509],
                "x": 538,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [335, 301, 464, 383],
                "x": 400,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [62, -47, 193, 54],
                "x": 125,
                "y": 59,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [499, 10, 615, 107],
                "x": 558,
                "y": 105,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [356, 393, 468, 486],
                "x": 413,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [430, 252, 565, 358],
                "x": 500,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-13, 330, 92, 431],
                "x": 39,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 478, "y": 595, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [556, 484, 682, 594],
                "x": 612,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [916, 316, 1024, 408],
                "x": 973,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [96, 578, 208, 670],
                "x": 156,
                "y": 676,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [927, 421, 1048, 522],
                "x": 981,
                "y": 525,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [731, 274, 847, 379],
                "x": 792,
                "y": 384,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 389, "y": 368, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [596, 348, 732, 438],
                "x": 666,
                "y": 438,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 500, "y": 561, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [364, 301, 498, 409],
                "x": 433,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [67, -25, 186, 67],
                "x": 121,
                "y": 66,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 559, "y": 119, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 448, "y": 502, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [401, 278, 518, 384],
                "x": 458,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-23, 339, 98, 436],
                "x": 42,
                "y": 446,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 434, "y": 569, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [527, 479, 638, 576],
                "x": 580,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [916, 284, 1025, 393],
                "x": 971,
                "y": 391,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 169, "y": 653, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [915, 433, 1036, 536],
                "x": 980,
                "y": 536,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 776, "y": 347, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [308, 231, 425, 316],
                "x": 362,
                "y": 324,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [579, 337, 707, 449],
                "x": 641,
                "y": 439,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 461, "y": 613, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [412, 316, 517, 414],
                "x": 466,
                "y": 419,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [67, -31, 170, 75],
                "x": 117,
                "y": 74,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [490, 31, 627, 124],
                "x": 560,
                "y": 134,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 482, "y": 508, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [365, 304, 468, 401],
                "x": 416,
                "y": 398,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 46, "y": 468, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 391, "y": 537, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 548, "y": 568, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [914, 258, 1033, 361],
                "x": 969,
                "y": 368,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [115, 525, 232, 623],
                "x": 182,
                "y": 626,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [910, 453, 1028, 539],
                "x": 978,
                "y": 547,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [691, 214, 830, 319],
                "x": 760,
                "y": 309,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 334, "y": 282, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 615, "y": 437, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [354, 550, 476, 660],
                "x": 423,
                "y": 660,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [441, 344, 569, 436],
                "x": 500,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [58, -7, 175, 73],
                "x": 114,
                "y": 83,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [500, 49, 615, 153],
                "x": 561,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [460, 403, 571, 512],
                "x": 517,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [314, 308, 430, 410],
                "x": 375,
                "y": 416,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-13, 389, 108, 483],
                "x": 49,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [287, 409, 412, 494],
                "x": 347,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [451, 459, 585, 551],
                "x": 516,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [912, 256, 1028, 347],
                "x": 967,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [135, 489, 260, 599],
                "x": 195,
                "y": 596,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [916, 454, 1047, 561],
                "x": 977,
                "y": 558,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 744, "y": 270, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [253, 143, 374, 248],
                "x": 306,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [537, 338, 646, 433],
                "x": 589,
                "y": 434,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [333, 603, 451, 694],
                "x": 384,
                "y": 701,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [470, 365, 591, 455],
                "x": 533,
                "y": 455,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [46, -2, 171, 93],
                "x": 110,
                "y": 91,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [506, 62, 625, 176],
                "x": 562,
                "y": 166,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [487, 416, 614, 520],
                "x": 551,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [275, 337, 391, 425],
                "x": 333,
                "y": 434,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-6, 417, 110, 515],
                "x": 52,
                "y": 509,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 304, "y": 466, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 483, "y": 546, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [901, 225, 1018, 318],
                "x": 964,
                "y": 324,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [144, 458, 273, 563],
                "x": 208,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [907, 461, 1028, 570],
                "x": 975,
                "y": 568,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [667, 124, 791, 232],
                "x": 728,
                "y": 230,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 278, "y": 207, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 564, "y": 429, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 346, "y": 734, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [506, 373, 628, 479],
                "x": 566,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [50, 0, 173, 92],
                "x": 106,
                "y": 100,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 563, "y": 183, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [531, 417, 641, 510],
                "x": 586,
                "y": 514,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 291, "y": 450, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-13, 430, 124, 534],
                "x": 55,
                "y": 528,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [194, 326, 312, 432],
                "x": 260,
                "y": 429,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 451, "y": 534, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [893, 202, 1019, 292],
                "x": 962,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [167, 435, 285, 536],
                "x": 221,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [920, 484, 1025, 587],
                "x": 973,
                "y": 579,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [660, 97, 779, 201],
                "x": 712,
                "y": 191,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 250, "y": 175, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [477, 316, 601, 431],
                "x": 538,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [255, 666, 372, 750],
                "x": 307,
                "y": 758,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [539, 391, 658, 505],
                "x": 600,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [42, 16, 169, 116],
                "x": 102,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [514, 103, 625, 203],
                "x": 564,
                "y": 201,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [552, 417, 688, 513],
                "x": 620,
                "y": 510,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [197, 368, 305, 471],
                "x": 250,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [2, 454, 119, 541],
                "x": 59,
                "y": 547,
                "track_id": None,
            },
            {"cb_id": 10, "bounding_box": [], "x": 217, "y": 393, "track_id": None},
            {"cb_id": 11, "bounding_box": [], "x": 419, "y": 521, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [907, 183, 1026, 291],
                "x": 960,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [181, 381, 291, 494],
                "x": 234,
                "y": 489,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 972, "y": 589, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [630, 61, 755, 151],
                "x": 696,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [154, 55, 286, 154],
                "x": 222,
                "y": 149,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 512, "y": 417, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [212, 670, 324, 769],
                "x": 269,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [570, 415, 702, 512],
                "x": 633,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [37, 16, 151, 120],
                "x": 98,
                "y": 120,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [496, 120, 617, 227],
                "x": 565,
                "y": 219,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 655, "y": 504, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 208, "y": 480, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-7, 466, 128, 559],
                "x": 62,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [107, 263, 233, 351],
                "x": 173,
                "y": 360,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 387, "y": 507, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [888, 161, 1016, 264],
                "x": 958,
                "y": 261,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [187, 341, 311, 451],
                "x": 247,
                "y": 448,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [918, 500, 1031, 600],
                "x": 970,
                "y": 599,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [630, 14, 749, 103],
                "x": 680,
                "y": 112,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [134, 38, 263, 135],
                "x": 194,
                "y": 128,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [428, 307, 556, 399],
                "x": 487,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [164, 673, 293, 778],
                "x": 230,
                "y": 771,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [613, 446, 734, 549],
                "x": 666,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [38, 26, 150, 134],
                "x": 94,
                "y": 130,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [512, 136, 626, 233],
                "x": 566,
                "y": 238,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [627, 393, 754, 501],
                "x": 689,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [104, 389, 228, 491],
                "x": 166,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [3, 474, 126, 589],
                "x": 65,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [78, 225, 181, 324],
                "x": 130,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [284, 384, 407, 489],
                "x": 354,
                "y": 492,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [890, 144, 1013, 245],
                "x": 956,
                "y": 241,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 260, "y": 406, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [904, 506, 1020, 603],
                "x": 969,
                "y": 609,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 664, "y": 73, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 167, "y": 114, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [409, 299, 530, 398],
                "x": 461,
                "y": 401,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [140, 647, 246, 754],
                "x": 192,
                "y": 756,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [642, 470, 756, 566],
                "x": 700,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [32, 35, 143, 131],
                "x": 90,
                "y": 141,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 567, "y": 258, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [667, 378, 782, 482],
                "x": 724,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [68, 396, 177, 508],
                "x": 125,
                "y": 505,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [18, 493, 121, 597],
                "x": 69,
                "y": 599,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [17, 208, 145, 309],
                "x": 86,
                "y": 305,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [265, 385, 380, 472],
                "x": 322,
                "y": 477,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 953, "y": 222, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [213, 259, 338, 370],
                "x": 273,
                "y": 362,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 967, "y": 619, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [594, -66, 701, 45],
                "x": 648,
                "y": 36,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [77, 0, 190, 112],
                "x": 139,
                "y": 108,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [384, 296, 501, 391],
                "x": 435,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [91, 618, 203, 733],
                "x": 153,
                "y": 726,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [678, 484, 783, 581],
                "x": 733,
                "y": 580,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [16, 51, 150, 157],
                "x": 86,
                "y": 152,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [508, 174, 626, 283],
                "x": 568,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [702, 371, 823, 466],
                "x": 758,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [19, 412, 151, 507],
                "x": 83,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [16, 508, 132, 615],
                "x": 72,
                "y": 614,
                "track_id": None,
            },
            {
                "cb_id": 10,
                "bounding_box": [-27, 191, 103, 278],
                "x": 43,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [233, 355, 345, 454],
                "x": 290,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [891, 103, 1015, 207],
                "x": 951,
                "y": 204,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [225, 215, 340, 311],
                "x": 286,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [916, 528, 1030, 636],
                "x": 966,
                "y": 629,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [574, -109, 685, -5],
                "x": 633,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [52, 14, 171, 119],
                "x": 111,
                "y": 109,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [350, 278, 467, 375],
                "x": 410,
                "y": 383,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [48, 586, 172, 672],
                "x": 115,
                "y": 677,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [705, 492, 836, 597],
                "x": 766,
                "y": 599,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [26, 62, 136, 166],
                "x": 82,
                "y": 164,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [508, 193, 622, 310],
                "x": 569,
                "y": 300,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [727, 347, 846, 436],
                "x": 793,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-28, 431, 94, 521],
                "x": 41,
                "y": 526,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 75, "y": 629, "track_id": None},
            {"cb_id": 10, "bounding_box": [], "x": 0, "y": 278, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [192, 357, 317, 442],
                "x": 258,
                "y": 447,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 949, "y": 186, "track_id": None},
            {
                "cb_id": 13,
                "bounding_box": [232, 169, 349, 272],
                "x": 299,
                "y": 271,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [901, 536, 1017, 645],
                "x": 964,
                "y": 638,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [25, 15, 141, 120],
                "x": 83,
                "y": 119,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 384, "y": 375, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 76, "y": 608, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [747, 506, 862, 614],
                "x": 800,
                "y": 616,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [22, 83, 144, 181],
                "x": 78,
                "y": 176,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 570, "y": 321, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [773, 318, 892, 426],
                "x": 827,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-52, 438, 68, 530],
                "x": 0,
                "y": 535,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [23, 545, 138, 643],
                "x": 78,
                "y": 644,
                "track_id": None,
            },
            {"cb_id": 11, "bounding_box": [], "x": 225, "y": 432, "track_id": None},
            {
                "cb_id": 12,
                "bounding_box": [884, 70, 1013, 161],
                "x": 947,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [249, 125, 362, 232],
                "x": 312,
                "y": 225,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [907, 546, 1032, 639],
                "x": 963,
                "y": 647,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 55, "y": 138, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [290, 273, 423, 360],
                "x": 358,
                "y": 366,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-22, 410, 99, 527],
                "x": 38,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [774, 539, 894, 635],
                "x": 833,
                "y": 631,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [24, 81, 128, 192],
                "x": 74,
                "y": 189,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [504, 244, 626, 345],
                "x": 571,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [804, 284, 932, 382],
                "x": 862,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [29, 552, 135, 654],
                "x": 82,
                "y": 657,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [126, 328, 248, 409],
                "x": 193,
                "y": 418,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [881, 54, 1015, 147],
                "x": 945,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [266, 86, 377, 187],
                "x": 325,
                "y": 179,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 961, "y": 656, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 27, "y": 168, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [267, 261, 393, 360],
                "x": 333,
                "y": 358,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-51, 304, 70, 398],
                "x": 0,
                "y": 406,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 866, "y": 644, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [10, 96, 123, 208],
                "x": 70,
                "y": 202,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 572, "y": 366, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [836, 254, 965, 360],
                "x": 896,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [22, 566, 151, 679],
                "x": 85,
                "y": 670,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [106, 308, 215, 406],
                "x": 161,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [873, 36, 1012, 136],
                "x": 942,
                "y": 135,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 338, "y": 133, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [908, 562, 1029, 675],
                "x": 960,
                "y": 665,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-69, 104, 63, 216],
                "x": 0,
                "y": 209,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [241, 248, 373, 341],
                "x": 307,
                "y": 351,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [837, 562, 970, 661],
                "x": 900,
                "y": 653,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [8, 115, 117, 212],
                "x": 66,
                "y": 215,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [509, 290, 628, 385],
                "x": 573,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [861, 220, 1000, 325],
                "x": 931,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [28, 575, 147, 676],
                "x": 88,
                "y": 682,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [61, 297, 194, 387],
                "x": 129,
                "y": 389,
                "track_id": None,
            },
            {"cb_id": 12, "bounding_box": [], "x": 940, "y": 119, "track_id": None},
            {"cb_id": 13, "bounding_box": [], "x": 351, "y": 87, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [901, 578, 1022, 667],
                "x": 958,
                "y": 674,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [214, 234, 339, 338],
                "x": 282,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [883, 561, 985, 662],
                "x": 933,
                "y": 659,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-8, 126, 119, 232],
                "x": 62,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [507, 314, 642, 423],
                "x": 574,
                "y": 414,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 965, "y": 279, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [30, 588, 145, 695],
                "x": 92,
                "y": 694,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [28, 285, 152, 386],
                "x": 96,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [875, 5, 1007, 98],
                "x": 938,
                "y": 104,
                "track_id": None,
            },
            {"cb_id": 13, "bounding_box": [], "x": 364, "y": 43, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [897, 588, 1010, 672],
                "x": 957,
                "y": 682,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 256, "y": 339, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [912, 569, 1019, 672],
                "x": 966,
                "y": 662,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-12, 151, 111, 236],
                "x": 58,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [520, 344, 634, 445],
                "x": 575,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [934, 136, 1052, 222],
                "x": 1000,
                "y": 232,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 95, "y": 705, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [2, 257, 133, 372],
                "x": 64,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [886, -15, 987, 84],
                "x": 936,
                "y": 89,
                "track_id": None,
            },
            {
                "cb_id": 13,
                "bounding_box": [310, -98, 446, 2],
                "x": 377,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [896, 587, 1009, 692],
                "x": 955,
                "y": 690,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 230, "y": 334, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 660, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 55, "y": 259, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [515, 356, 644, 457],
                "x": 576,
                "y": 463,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [28, 607, 163, 716],
                "x": 98,
                "y": 715,
                "track_id": None,
            },
            {
                "cb_id": 11,
                "bounding_box": [-37, 247, 89, 350],
                "x": 32,
                "y": 352,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [867, -22, 1000, 82],
                "x": 934,
                "y": 75,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 954, "y": 698, "track_id": None},
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [143, 230, 259, 330],
                "x": 205,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-15, 182, 114, 272],
                "x": 51,
                "y": 275,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 577, "y": 489, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 101, "y": 725, "track_id": None},
            {
                "cb_id": 11,
                "bounding_box": [-50, 244, 57, 345],
                "x": 0,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [873, -30, 991, 66],
                "x": 931,
                "y": 61,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [882, 597, 1004, 701],
                "x": 952,
                "y": 706,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [114, 223, 243, 339],
                "x": 179,
                "y": 331,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 47, "y": 291, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 578, "y": 515, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [44, 626, 158, 727],
                "x": 105,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [871, -47, 987, 38],
                "x": 929,
                "y": 48,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [897, 615, 1020, 714],
                "x": 950,
                "y": 714,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [91, 228, 212, 322],
                "x": 153,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-24, 215, 105, 314],
                "x": 43,
                "y": 307,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 579, "y": 541, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [39, 640, 178, 740],
                "x": 108,
                "y": 742,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [861, -74, 987, 32],
                "x": 927,
                "y": 35,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [881, 615, 1017, 732],
                "x": 949,
                "y": 722,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [59, 235, 196, 327],
                "x": 128,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-18, 214, 101, 325],
                "x": 39,
                "y": 324,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [512, 458, 645, 575],
                "x": 580,
                "y": 568,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [51, 655, 181, 750],
                "x": 111,
                "y": 750,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [870, -80, 993, 30],
                "x": 925,
                "y": 23,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [890, 633, 1017, 737],
                "x": 947,
                "y": 729,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [49, 241, 170, 335],
                "x": 102,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-29, 252, 96, 333],
                "x": 35,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [517, 496, 640, 595],
                "x": 581,
                "y": 596,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [56, 649, 182, 764],
                "x": 115,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [859, -87, 988, 21],
                "x": 923,
                "y": 11,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [886, 643, 1003, 744],
                "x": 946,
                "y": 736,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 2, "bounding_box": [], "x": 76, "y": 348, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [-26, 256, 86, 360],
                "x": 31,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [523, 520, 635, 623],
                "x": 582,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [49, 659, 169, 757],
                "x": 118,
                "y": 764,
                "track_id": None,
            },
            {
                "cb_id": 12,
                "bounding_box": [855, -96, 971, 10],
                "x": 921,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [894, 645, 1003, 741],
                "x": 944,
                "y": 743,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [-9, 265, 121, 349],
                "x": 51,
                "y": 358,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-37, 271, 94, 384],
                "x": 27,
                "y": 379,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 583, "y": 652, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [62, 667, 188, 774],
                "x": 121,
                "y": 770,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 943, "y": 750, "track_id": None},
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [-28, 265, 93, 382],
                "x": 25,
                "y": 372,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 23, "y": 398, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [534, 577, 639, 673],
                "x": 584,
                "y": 681,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [58, 666, 193, 784],
                "x": 124,
                "y": 775,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [883, 666, 991, 750],
                "x": 941,
                "y": 757,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [-61, 279, 60, 387],
                "x": 0,
                "y": 389,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-36, 310, 72, 413],
                "x": 19,
                "y": 418,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [519, 609, 637, 714],
                "x": 585,
                "y": 710,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 128, "y": 780, "track_id": None},
            {"cb_id": 14, "bounding_box": [], "x": 940, "y": 764, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [-43, 330, 67, 446],
                "x": 15,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [536, 644, 641, 749],
                "x": 586,
                "y": 739,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [77, 687, 199, 794],
                "x": 131,
                "y": 784,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [876, 666, 993, 779],
                "x": 938,
                "y": 770,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [-42, 359, 72, 468],
                "x": 11,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [529, 675, 647, 765],
                "x": 587,
                "y": 769,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [79, 683, 186, 782],
                "x": 134,
                "y": 788,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [884, 683, 1000, 771],
                "x": 937,
                "y": 776,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 5, "bounding_box": [], "x": 7, "y": 480, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 588, "y": 799, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [71, 689, 193, 784],
                "x": 138,
                "y": 791,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [873, 672, 985, 775],
                "x": 935,
                "y": 782,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [-63, 401, 55, 501],
                "x": 3,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [87, 691, 194, 784],
                "x": 141,
                "y": 794,
                "track_id": None,
            },
            {
                "cb_id": 14,
                "bounding_box": [871, 679, 1003, 781],
                "x": 934,
                "y": 788,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [-69, 435, 69, 517],
                "x": 0,
                "y": 525,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 144, "y": 796, "track_id": None},
            {
                "cb_id": 14,
                "bounding_box": [878, 698, 1001, 788],
                "x": 932,
                "y": 794,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 9,
                "bounding_box": [91, 693, 217, 788],
                "x": 147,
                "y": 798,
                "track_id": None,
            },
            {"cb_id": 14, "bounding_box": [], "x": 931, "y": 800, "track_id": None},
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {"cb_id": 9, "bounding_box": [], "x": 151, "y": 799, "track_id": None}
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 9,
                "bounding_box": [93, 701, 218, 796],
                "x": 154,
                "y": 800,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {"cb_id": 9, "bounding_box": [], "x": 157, "y": 800, "track_id": None}
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 9,
                "bounding_box": [104, 692, 223, 796],
                "x": 161,
                "y": 800,
                "track_id": None,
            }
        ],
    },
]
