country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 967, "y": 0, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [14, 701, 139, 807],
                "x": 70,
                "y": 800,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 179, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [746, 702, 882, 807],
                "x": 813,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [934, -54, 1058, 45],
                "x": 1000,
                "y": 55,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [881, -65, 1001, 40],
                "x": 937,
                "y": 44,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [40, 622, 155, 740],
                "x": 95,
                "y": 730,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [925, 108, 1048, 212],
                "x": 991,
                "y": 204,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 782, "y": 753, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [932, 16, 1043, 106],
                "x": 991,
                "y": 113,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [855, -24, 970, 88],
                "x": 908,
                "y": 82,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [68, 580, 177, 670],
                "x": 121,
                "y": 671,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [922, 125, 1033, 236],
                "x": 983,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [699, 602, 816, 716],
                "x": 752,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [929, 68, 1033, 163],
                "x": 983,
                "y": 168,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [817, 20, 948, 118],
                "x": 879,
                "y": 116,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 147, "y": 622, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [923, 149, 1028, 266],
                "x": 975,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [664, 562, 786, 669],
                "x": 722,
                "y": 668,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [918, 113, 1034, 222],
                "x": 975,
                "y": 221,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [788, 38, 907, 147],
                "x": 849,
                "y": 144,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 173, "y": 583, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [915, 190, 1029, 276],
                "x": 967,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [622, 528, 760, 627],
                "x": 692,
                "y": 629,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 967, "y": 271, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [770, 65, 880, 170],
                "x": 820,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [129, 454, 250, 559],
                "x": 199,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [892, 210, 1029, 301],
                "x": 959,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [593, 497, 730, 593],
                "x": 662,
                "y": 593,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [900, 211, 1021, 328],
                "x": 959,
                "y": 318,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [725, 97, 850, 192],
                "x": 791,
                "y": 188,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [155, 432, 292, 539],
                "x": 225,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [897, 242, 1018, 345],
                "x": 951,
                "y": 335,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 632, "y": 561, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [894, 268, 1001, 357],
                "x": 951,
                "y": 363,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [692, 103, 811, 197],
                "x": 761,
                "y": 204,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [184, 414, 312, 523],
                "x": 250,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [874, 260, 996, 356],
                "x": 943,
                "y": 362,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 602, "y": 531, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [880, 310, 1002, 403],
                "x": 943,
                "y": 405,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 732, "y": 217, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [206, 406, 345, 506],
                "x": 276,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [874, 297, 989, 379],
                "x": 935,
                "y": 388,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [507, 398, 632, 511],
                "x": 572,
                "y": 504,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [877, 337, 1004, 444],
                "x": 935,
                "y": 445,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [646, 122, 767, 229],
                "x": 703,
                "y": 228,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [240, 405, 371, 501],
                "x": 302,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [868, 305, 996, 422],
                "x": 927,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [490, 377, 609, 474],
                "x": 542,
                "y": 480,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 926, "y": 483, "track_id": None},
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [607, 142, 724, 230],
                "x": 673,
                "y": 235,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [269, 410, 387, 502],
                "x": 328,
                "y": 509,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 919, "y": 441, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 511, "y": 460, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [850, 409, 969, 521],
                "x": 918,
                "y": 518,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [582, 136, 710, 249],
                "x": 644,
                "y": 240,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 354, "y": 517, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [858, 362, 975, 469],
                "x": 911,
                "y": 467,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [423, 337, 535, 442],
                "x": 481,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [850, 458, 963, 551],
                "x": 910,
                "y": 551,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [551, 143, 666, 236],
                "x": 615,
                "y": 244,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 380, "y": 529, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [834, 384, 953, 491],
                "x": 903,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [390, 325, 511, 428],
                "x": 451,
                "y": 429,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 902, "y": 581, "track_id": None},
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [534, 140, 656, 250],
                "x": 586,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [349, 438, 469, 539],
                "x": 405,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [834, 428, 958, 528],
                "x": 895,
                "y": 518,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 421, "y": 419, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [833, 503, 960, 615],
                "x": 894,
                "y": 609,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 556, "y": 248, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [366, 461, 501, 557],
                "x": 431,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [822, 447, 952, 534],
                "x": 887,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [325, 321, 458, 423],
                "x": 391,
                "y": 413,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [831, 544, 954, 628],
                "x": 886,
                "y": 635,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 527, "y": 248, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [391, 470, 520, 569],
                "x": 457,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [822, 472, 944, 565],
                "x": 879,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [303, 307, 424, 406],
                "x": 361,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [826, 566, 943, 668],
                "x": 878,
                "y": 659,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 498, "y": 249, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [424, 487, 538, 601],
                "x": 483,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [814, 488, 931, 586],
                "x": 871,
                "y": 594,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [269, 320, 401, 406],
                "x": 331,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [807, 583, 939, 677],
                "x": 870,
                "y": 681,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 468, "y": 249, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [452, 513, 578, 612],
                "x": 509,
                "y": 617,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [811, 514, 914, 610],
                "x": 863,
                "y": 618,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [241, 310, 361, 420],
                "x": 301,
                "y": 415,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 862, "y": 701, "track_id": None},
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [374, 161, 489, 254],
                "x": 439,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [471, 533, 595, 637],
                "x": 535,
                "y": 635,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 855, "y": 643, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [207, 319, 332, 430],
                "x": 271,
                "y": 423,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 853, "y": 719, "track_id": None},
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [354, 153, 461, 253],
                "x": 410,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [506, 551, 621, 654],
                "x": 560,
                "y": 653,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [784, 569, 897, 657],
                "x": 847,
                "y": 667,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [176, 328, 304, 434],
                "x": 240,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [775, 644, 896, 737],
                "x": 845,
                "y": 735,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 380, "y": 256, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [527, 560, 636, 667],
                "x": 586,
                "y": 668,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 839, "y": 690, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [155, 346, 273, 443],
                "x": 210,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [779, 645, 899, 754],
                "x": 837,
                "y": 750,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [299, 155, 415, 265],
                "x": 351,
                "y": 261,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [545, 570, 676, 678],
                "x": 612,
                "y": 680,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 831, "y": 713, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [123, 375, 236, 474],
                "x": 180,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [760, 670, 893, 766],
                "x": 829,
                "y": 762,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [257, 168, 375, 276],
                "x": 322,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [568, 596, 695, 684],
                "x": 638,
                "y": 689,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [759, 634, 874, 733],
                "x": 823,
                "y": 735,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [98, 397, 220, 500],
                "x": 150,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [771, 671, 878, 774],
                "x": 821,
                "y": 773,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [223, 169, 355, 268],
                "x": 293,
                "y": 278,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 664, "y": 694, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [745, 648, 882, 747],
                "x": 815,
                "y": 757,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 120, "y": 527, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 813, "y": 782, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [200, 197, 319, 293],
                "x": 263,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [635, 603, 759, 684],
                "x": 690,
                "y": 694,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [739, 689, 859, 787],
                "x": 807,
                "y": 779,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [32, 461, 150, 557],
                "x": 90,
                "y": 560,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 805, "y": 789, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 234, "y": 307, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [649, 590, 773, 694],
                "x": 715,
                "y": 688,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [732, 701, 851, 793],
                "x": 799,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-1, 499, 118, 601],
                "x": 60,
                "y": 598,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 797, "y": 795, "track_id": None},
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [150, 226, 255, 324],
                "x": 205,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [687, 576, 793, 676],
                "x": 741,
                "y": 675,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-32, 533, 83, 650],
                "x": 30,
                "y": 640,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 789, "y": 799, "track_id": None},
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [122, 254, 242, 346],
                "x": 175,
                "y": 350,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 767, "y": 656, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-63, 597, 61, 698],
                "x": 0,
                "y": 688,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [83, 269, 203, 387],
                "x": 146,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [734, 522, 847, 620],
                "x": 793,
                "y": 628,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [65, 318, 181, 406],
                "x": 117,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [761, 500, 880, 595],
                "x": 819,
                "y": 592,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [37, 338, 139, 456],
                "x": 87,
                "y": 448,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [789, 442, 897, 553],
                "x": 845,
                "y": 546,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-2, 385, 119, 501],
                "x": 58,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [809, 399, 920, 499],
                "x": 870,
                "y": 491,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-37, 437, 88, 533],
                "x": 29,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [830, 324, 947, 414],
                "x": 896,
                "y": 424,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-63, 503, 52, 605],
                "x": 0,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [865, 239, 980, 356],
                "x": 922,
                "y": 346,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 948, "y": 256, "track_id": None}
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [915, 43, 1029, 161],
                "x": 974,
                "y": 153,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [934, -70, 1061, 28],
                "x": 1000,
                "y": 36,
                "track_id": None,
            }
        ],
    },
]
